### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by reliak** [statiqdev/Statiq#102]
Hi,

I have a problem with the RazorAndMarkdownBlog-Example. When I run it, I get the following exception
`System.ArgumentException: Document source must be unique within the pipeline`

The 'GeneratedBlog'-example is working fine.
Any help appreciated.

**Comment by daveaglick** [comment]
Quick question to help narrow this down: are you using the .zip file of the most recent release?

If so, it has a known bug for this example that's been fixed in the develop branch (see #78). You can either build from source or I can send you a new .zip of the most recent develop build. I'm hoping to get a new official release out soon, but this next one is big and there's still one or two things to finish.

If you did build from source and are on an up to date develop branch, then we'll need to continue trouble shooting.

**Comment by reliak** [comment]
Thanks for your quick reply. With the version from the development branch, everything is working fine :)

**Comment by daveaglick** [comment]
:thumbsup:
