### ISSUE TITLE
Moving MetadataKeys from Core to Common

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#131]
If I remember correctly Modules should only reference Common.

But it would be convenient to use constants instead of strings for common metadata keys like DestinationFilePath. Unfortunately they are defined in core.

Maybe they should also have comments describing them (e.g. contains Path relative to inputfolder or ProjectFolder).

**Comment by daveaglick** [comment]
I've gone back and forth on this. I actually started out with MetadataKeys in Common, but moved them to Core after thinking about long-term sustainability. My thinking at the time was that I wanted Common to rarely change, but Core to have the freedom to change more frequently. This would help third-party module authors since they'll all need to update their Common references when that library gets a new version. If Common rarely changes (once we get to a more stable release), then those third-party modules should work across lots of versions of the Core library. In contrast, I wanted the freedom to add new metadata and even new modules to Core without having an effect on Common.

That said, I do agree it would be **much** nicer to have const strings for the common Core metadata keys in Common. Maybe the answer is a kind of hybrid where we put all the keys we know about for a given Common release there, but we can add new keys after the fact by adding them to the Core MetadataKeys class. Then whenever we have a more important change to make to Common, we can move over the pending keys at that point. That way Common doesn't change just because of new keys, but will add the new keys when it needs to change for other reasons.

What do you think?

**Comment by LokiMidgard** [comment]
Now I understand.

Maybe it is just to late so I can't think straight, but what would happen if we create a new Project just with const strings for metadata. This would frequently updated with new keys.

As long as we don't change keys but only add new ones, the version of this library that was used is irrelevant. As long it has the desired keys for the modules it is ok. No need to update this dependency.

This would result in having many Module library's that uses different versions of the const module. Not sure if this would be a problem. I need to sleep over this.
