### ISSUE TITLE
Unable to pass IMetadata to an external assembly from razor template

### ISSUE THREAD

**Issue by martinvobr** [statiqdev/Statiq#137]
I'm trying to put some business logic code into external assembly which will be called from razor templates. I would need an access to metadata collection.

Is it possible? 

cshtml snippet would look like this:

```
This works: @ExtensionLib.WyamExtensionClass.SomeMethod()
This throws exception: @ExtensionLib.WyamExtensionClass.SomeMethod(Model)
```
#### IMetadata param

  // this throws System.MissingMethodException: Method not found: 'System.String ExtensionLib.WyamExtensionClass.MethodNotFound(Wyam.Common.IMetadata)'.

```
public static string MethodNotFoundProblem(Wyam.Common.IMetadata metadata)
```
### Object param with subsequest cast to IMetadata

// System.InvalidCastException: Unable to cast object of type 'Wyam.Core.Documents.Metadata' to type 'Wyam.Common.IMetadata'.

```
        public static string CastProblem(object metadata)
    {
        // will throw  System.InvalidCastException: Unable to cast object of type 'Wyam.Core.Documents.Metadata' to type 'Wyam.Common.IMetadata'.
        IMetadata md = (IMetadata) metadata;

        return md.String("SourceFileDir");
    }
```

I'm attaching sample project with repro: 
http://www.vobr.cz/wyam/wyam-repro.zip

**Comment by daveaglick** [comment]
Thanks for providing a repro - that's extremely helpful. The error that first caught my eye is the `InvalidCastException`. It seems odd since the `BaseRazorPage` itself only exposes an `IMetadata` for the `Model` property: https://github.com/Wyamio/Wyam/blob/develop/Wyam.Modules.Razor/Mvc/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L51

My best guess at the moment is that the `ExtensionLib` is referencing a different version of the `Wyam.Common` library than the `wyam.exe` is using. Where are each of these coming from? Specifically:
- Where did the `wyam.exe` you're using coming from? Was it downloaded from the releases page on GitHub or built from source (and if built, which branch)?
- Where did the `Wyam.Common.dll` assembly come from? Was it downloaded from the releases page, fetched from NuGet, or built from source (and if built, which branch)?

We'll get to the bottom of this...

**Comment by martinvobr** [comment]
Thanks for a quick turnaround! The version of wyam assemblies should be the same. 

I've retested it with wyam 0.10.0-beta binaries downloaded from https://github.com/Wyamio/Wyam/releases few moments ago. Complete archive (with all referenced binaries and compiled assembly) can be downloaded here:

http://www.vobr.cz/wyam/wyam-repro-1.zip

The strange thing is that when I've first encountered it I've tried last source code version downloaded from github. Same result. While having source code tried changing visibility of Wyam.Core.Documents.Metadata from internal to public and it started working. But before creating a simplified repro I had to done few other things and I can't get it work again :-(. Probably I overlooked something and it did not worked in fact.

**Comment by daveaglick** [comment]
Okay, thanks. I'll play with it some and get back to you. There hasn't been much testing around bringing in external assemblies, so it wouldn't surprise me if there's a bug in there somewhere. I like what you're trying to do though - it could be a very nice way of creating powerful custom Razor helpers. The good news for everyone is that now you're helping track down the bugs. The bad news for you is that you get to be the guinea pig :smile:.

**Comment by martinvobr** [comment]
No problem being a guinea pig :-), when bugs are fixed. I've just started converting one of our internal documentation project from a home-grown T4-based solution to Wyam. It consists from more than 300 web pages. Some of them are static, some are generated from several external sources - from XML files, business logic assemblies, taken via web services from external databases. It will be a lot of opportunities to test a lot of things. I'll be happy to help Wyam improve.

**Comment by daveaglick** [comment]
Figured this one out (sort of). It has to do with assembly binding (which isn't a strong point for me) and which assembly the extension library picks. If you call `Console.WriteLine(typeof(IModule).Assembly.Location.ToString())` from the Razor page, you get the expected `Wyam.Common.dll` from wherever you happened to call Wyam from. However, if you make the same call from within the extension lib, you get the `Wyam.Common.dll` from the extension lib's output folder (which is there because "Copy Local" is true).

The problem is that it appears extension libraries are going to pick and load a referenced assembly from their own location on disk, even if an assembly with a matching identity is already in the AppDomain. And when it does, even if the alternate assembly is actually the same, the types don't match up (which is still confusing to me - need to learn a little more to understand why).

**A quick fix is to change "Copy Local" to false for the extension library and make sure to delete the `Wyam.Common.dll` from it's output folder.** After doing that, all three calls to the library work fine. I'm still going to research this a little more to see if I can force the binding over to the already-loaded common library for libraries loaded from Razor so this isn't an issue even if the alternate assembly is in the library output folder.

**Comment by daveaglick** [comment]
For reference, I've tracked down the root of this problem. When Wyam initially runs, it loads assemblies with `Assembly.Load()` which loads the assemblies into a particular context. It looks like this context is different than the context that gets used when the extension library finds the assembly in it's own folder. When that happens, we end up with the Wyam.Common assembly being loaded twice in different contexts. The resulting behavior matches what would be expected in this situation, described here: https://msdn.microsoft.com/en-us/library/dd153782.aspx#avoid_loading_into_multiple_contexts

So now the question is: how to make sure Wyam loads assemblies in the same context as extension libraries will (or vice versa)?

**Comment by martinvobr** [comment]
Workaround with CopyLocal=false solved it for me. Thanks.

I'm no expert on assembly loading, and have read the linked article only briefly. One of it's links (https://msdn.microsoft.com/en-us/library/dd153782.aspx#switch_to_default) suggest in the last paragraph using AppDomain, setting PrivateBinPath to semicolons separated list of directories and than using Assembly.LoadFrom. Because in such case they are in the probing path and should be loaded into the default context. Maybe this would help?

**Comment by daveaglick** [comment]
You were on to something, and I was thinking I could add all the explicitly specified assemblies to the `PrivateBinPath`, but then I read this:

> If the directories specified for PrivateBinPath are not under ApplicationBase, they are ignored.

Doh!

I do mix `Assembly.Load()` and `Assembly.LoadFrom()` when loading assemblies specified in the config file depending on if they're given by name or by path - I think the key is going to be figuring out how to get them all into the same context, be it default or LoadFrom.

**Comment by daveaglick** [comment]
Okay, I've got a fix and can now get this to run without exceptions even when the Wyam.Common assembly exists in the extension lib folder. Just want to do some more tests and then I'll merge it in. Thanks a lot for reporting this - it would have bitten us sooner or later one way or the other, so I'm glad we got it taken care of now.
