### ISSUE TITLE
how to set the current culture in the config.wyam file?

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#142]
in which section of the file is it recommended to do it?

**Comment by daveaglick** [comment]
That's a good question. The config file has three parts: the setup, the declarations, and the config (http://wyam.io/getting-started/configuration). The declarations section is just concatenated with the config section, after wrapping the config section in a method and then generating some invisible helpers. The setup section gets evaluated first, so that's probably where you want to put it though it would probably also work at the top of the config section.

The bigger question is going to be how to enforce a different culture. My understanding is that the culture gets "reset" for every thread. Wyam does a fair amount of parallel processing using the thread pool. I think you can use `CultureInfo.DefaultThreadCurrentCulture` to set it for the entire AppDomain, which should persist across thread boundaries. If you give it a try let me know if it works.

**Comment by alfadormx** [comment]
For the time being I added a using System.Globalization; in the declarations section.
Then I added 

CultureInfo.DefaultThreadCurrentCulture = 
    CultureInfo.CreateSpecificCulture("en-US");

in the config section above any Pipeline configuration. It seems to be working fine.

**Comment by daveaglick** [comment]
Great - I'll add a note about this to the docs.
