### ISSUE TITLE
New module to create a tree from documents in pipeline

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#150]
This would be helpful in a lot of different use cases where the documents in the pipeline naturally make a tree and you want to process them that way. For example, the current ReadFiles module reads all the documents for a file system tree into the output document sequence. We then rely on a metadata value to tell us where the document sits in the tree. Other modules like CodeAnalysis also have a tree-like relationship but use metadata to represent the tree (I.e., namespace relationships).

On the other hand, we've seen in the CodeAnalysis module how storing sequences of documents within a container document can work very well. I'd like to adopt this strategy for this new module. Here's how it should work:
- You specify a metadata value to look at along with a delimiter. For example, to make a tree from documents output by ReadFiles, you would use the SourceFilePath metadata value and a path separator delimiter.
- The module will split the specified metadata value (as converted to a string) for each input document according to the specified delimiter.
- A new Children metadata value (or other user-specified metadata key) will be added to all documents in the tree that have child documents. This contains an `IReadOnlyList<IDocument>` of all child documents in the order in which they appear in the input document sequence.
- New documents with empty content will be created for roots and branches in the tree that don't have an existing document to represent them. I.e., when processing output from ReadFiles, all the input documents will be files so new empty documents for each directory will end up being created.

A new `ReadFiles.OutputTree()` method should also be added to automatically output the result from ReadFiles in this way rather than the default flat output sequence.

**Comment by avishnyakov** [comment]
Fair enough, all makes sense.

User stories would not be only about metadata but also around folder structure.
In Wyam web site the ToC is built around metadata and groups (comes from metadata too), however building ToC based on the folder structure is another desired case.

Having said that, there are also hybrid cases: a tree is constructed in highly custom ways partly with metadata, partly based on the folders structure, index.html files, partly with the fallbacks (if no metadata, then use filename) and so on.

All that leads to the idea of having not only default ReadFiles.OutputTree() extension, but also a callback so that you can own the lookup logic. Something like "ReadFiles.OutputTree(config)" where the config would be a set of functions to customize the lookup logic.

Here is a SO discussion about "Nice & universal way to convert List of items to Tree":
http://stackoverflow.com/questions/19648166/nice-universal-way-to-convert-list-of-items-to-tree
"GenerateTree" method seems just about right, does not it?

**Comment by LokiMidgard** [comment]
After Updating my config to the current Wyam Version (Wyam version 0.12.3-beta) I've found some old code for a Module that creates Trees from Filessystem.

I tried to Update the code so it could be used for this Module, but run into some Problems:
The Module adds Metadata for Children (ReadonlyList<IDocuments>) and Parent (IDocument). It also adds some others to navigate between siblings. But the Problem is that Documents are readonly.
When I add the first documents, those haven't set the TreeMetadata. As a result someone can't navigate in the Tree like getting all Children of the Parent.
The same is true if a pipeline updates Documents with new metadata, resulting in replacing the actual documents. In this case the treestructure also has the old values.

**Comment by daveaglick** [comment]
@LokiMidgard This must be really old code, documents have been immutable for a while :) Thankfully, I've got you covered!

The CodeAnalysis module also needs to do "lazy" loading of metadata because as it generates symbols for semantic information it doesn't know how things are related until it has all the symbols. For example, a document that represents a class symbol needs metadata that points to the containing namespace document, but that namespace document also needs metadata that points to all of the documents that represent child classes. At first glance, this sounds similar to your problem.

Wyam has a built-in mechanism for solving problems like this, though it's not well documented yet. The trick is to add metadata objects that implement `IMetadataValue` ([API docs here](http://wyam.io/api/Wyam.Common.Meta/0BFBB658/), though I notice they don't even have code comments - yikes!).

When a document goes to get a metadata value, it first checks if the object at the requested key implements `IMetadataValue`. If it does, then it calls the `IMetadataValue.Get()` method at the point when the request is made. Then casting and type conversion happens the way it normally does, _as if_ the object returned by `IMetadataValue.Get()` was in the metadata collection from the beginning. This lets you defer calculating the actual value of the metadata key until it's used later, which is handy for cases when you either don't know enough about the value at the time you want to add it or the value is expensive to calculate and may never be needed down the line so you want to save the cycles.

There's also a couple helper classes for this that implement `IMetadataValue` (though you can also make your own implementations). `DelegateMetadataValue` ([API docs](http://wyam.io/api/Wyam.Common.Meta/4854B78E/)) lets you specify a delegate and `CachedDelegateMetadataValue` ([API docs](http://wyam.io/api/Wyam.Common.Meta/B2F39640/)) does the same, but caches the value after the first request.

Hopefully that all made sense?

**Comment by LokiMidgard** [comment]
Yes it made sense.
I'll upload the Module for Feedback.
