### ISSUE TITLE
CopyFiles module potential bug

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#158]
Aiming to copy all images from src to des leaving patsh by default.
Have 4 *.gif files under /folder/subfolder/img and here is what's happening:

0 docs, but 4 docs were expected:

``` cs
Pipelines.Add("site-resources-images",
    CopyFiles(@"*.gif"),
    CopyFiles(@"*.jpeg"),
    CopyFiles(@"*.jpg"),
    CopyFiles(@"*.png")
);

 Executing pipeline "site-resources-images" (5/6) with 4 child module(s)
        Executed pipeline "site-resources-images" (5/6) in 1066 ms resulting in 0 output document(s
)
```

4 docs, as expected:

``` cs
Pipelines.Add("site-resources-images",
    CopyFiles(@"*.gif")
//  CopyFiles(@"*.jpeg"),
//  CopyFiles(@"*.jpg"),
//  CopyFiles(@"*.png")
);

  Executing pipeline "site-resources-images" (5/6) with 1 child module(s)
        Executed pipeline "site-resources-images" (5/6) in 12 ms resulting in 4 output document(s)
)
```

Hm... why :)

**Comment by daveaglick** [comment]
The CopyFiles module outputs new documents containing information from each file that was copied. There's no "pass-through" of information from the input documents. In other words, the input documents are lost (to keep them, wrap the subsiquent CopyFiles modules in a Concat module).

In your case, the first CopyFiles should have actually copied the files and output documents for each, but the following ones didn't copy anything and thus output empty document sets (that's why you saw the 4 outputs when commenting out the other ones).

This could be documented better, so I'll leave this issue open as a reminder until I update the docs.

**Comment by avishnyakov** [comment]
I meant that the files weren't there at all.
Double check that, thanks.

**Comment by daveaglick** [comment]
Ah, okay. I misunderstood. If CopyFiles actually isn't copying the .gif files when other modules follow it, that's not good at all. What console output do you get with the `--verbose` flag?

**Comment by daveaglick** [comment]
I cannot reproduce this one. I am able to get the "resulting in 0 documents" message (as expected when stringing multiple CopyFiles modules together when the last one doesn't yield anything). However, the four GIF files still make it to the output folder:

![2015-12-28_11h04_37](https://cloud.githubusercontent.com/assets/1020407/12021267/1107305c-ad53-11e5-90a2-5935f7da3548.png)

Do you have a reproducible zip file that you could attach?

**Comment by daveaglick** [comment]
With the additional documentation and an extra change I just made to ensure CopyFiles doesn't operate on input documents when plain search patterns are specified, I'm going to guess this one is resolved. Feel free to reopen if the problem looks like it's still there.
