### ISSUE TITLE
Consider 'retry' logic for Razor() and some other modules to avoid IOException exceptions

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#167]
While editing and saving files with Wyam running under --watch option, there might be some random IOException as following.

```
Executing pipeline "site-md-content" (1/8) with 10 child module(s)
            Error while executing module Razor: System.IO.IOException: The process cannot access the 
file 'C:\Docs\Views\Shared\TheDocs\Layouts\_Flued37.cshtml' because it is being used by another process.
```

Wyam can have some kind of re-try logic to handle such cases and be more IO-resilient. That would improve the while processing flow making it rock solid!

Maybe a few try-catch with sleep for 100-250ms might do some good, not sure what it'll be :)

**Comment by daveaglick** [comment]
Interesting - it looks like this is being caused by concurrent access to a Razor layout. I'm surprised Razor itself doesn't handle this (though I replaced a good bit of the file system handling code, so it may have and I just screwed it up). In any case, you're right, we shouldn't be getting exceptions. Have you seen this happen with reads other than Razor or just when reading Razor layouts?

**Comment by avishnyakov** [comment]
Yea, copy files module sometimes gives similar thing on css/images/js, on the content files.

**Comment by daveaglick** [comment]
Okay, thanks. In the CopyFiles case, retry logic is probably the thing to do.

**Comment by daveaglick** [comment]
Hopefully this will resolve the issue (or at least mostly mitigate it). Feel free to reopen the issue if it looks like it doesn't help.
