### ISSUE TITLE
Yaml module should trace the name of the document being processed

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#177]
Yaml module produces the following trace and does not include the name of the document it processes. Here is a normal trace:

```
 Executing module Yaml with 1 input document(s)
```

Here is a trace with an exception caused by a malformed front matter. The trace indicates the exception, however lacks the name of the doc. Its nearly impossible to trace back the document and fix the issue with front matter. 

```
 Executing module Yaml with 1 input document(s)
                Error while executing module Yaml: YamlDotNet.Core.SyntaxErrorException: (Line: 1, Col: 8, Idx: 7) - (Line: 3, Col: 1, Idx: 59): While scanning a 
quoted scalar, find unexpected end of stream.
   at YamlDotNet.Core.Scanner.ScanFlowScalar(Boolean isSingleQuoted) in c:\projects\yamldotnet\YamlDotNet\Core\Scanner.cs:line 1602
   at YamlDotNet.Core.Scanner.FetchFlowScalar(Boolean isSingleQuoted) in c:\projects\yamldotnet\YamlDotNet\Core\Scanner.cs:line 1568
```

Would be nice if the Yaml module (potentially all modules) would indicate the name of the document being processed. Troubleshooting would become much easier.

**Comment by avishnyakov** [comment]
Lightning fast!

**Comment by daveaglick** [comment]
I aim to please :)

This is actually really hard to do across the board because of the way some modules process documents in parallel (if we let the exception bubble-up there would be no way to know which document was at fault). That said, it's pretty easy to address these one-by-one, so if you see another case where more error info would be helpful, just let me know!

**Comment by avishnyakov** [comment]
Too easy, thank you @daveaglick :)
