### ISSUE TITLE
Consider potential "publishing" modules

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#179]
A broader discussion regarding Wyam workflow and publishing "best practices". 

Wyam can build stuff, what about publishing? 
There is a CI script to get thing running with AppVeyor / github pages, it's fine. What about other options?
Does Wyam roadmap / vision on how it would cover "publishing" area?

The thing is that I am working on publishing bits for AWS S3. Hence started wondering if that can be (should be) seen as a Wyam module - getting "Output" folder published somewhere - or should it be "separated" from Wyam? 

Understood that Wyam should be platform-agnostic, that's fine.
However, how do you see publishing workflow implemented with Wyam?

**Comment by daveaglick** [comment]
It's an interesting question: where does the responsibility of the site/content generator end and that of the deployment tools begin?

I tend to be pragmatic about these things - if features that blur the lines between generation and publication make the tool for valuable, then I'd say they're in-scope. There's been some talk about scaffolding deployment scripts (#64), and I think that's a good start.

There's no roadmap for any of this (yet) - my best collection of thoughts at the moment is in the linked issue. I suspect that this may be something I start looking at piecemeal with 0.13.0 (the release after next).

**Comment by avishnyakov** [comment]
Does not seem to be Wyam responsibility.

However, the "CI" and the publishing workflow does not seem to be completed without such publishing features. Yea, github pages solves that. Once you go custom such S3 or Rackspace or something else - nope, the workflow is incomplete.

That's the main driver behind the ticket - thoughts on the complete generation / publishing workflow.

**Comment by avishnyakov** [comment]
Getting back to this convo, I did a dead simple S3 publishing. Gonna wrap it up into new Wyam module and see how it might work within pipelines.

Comes extremely handy within dev/test/prod publishing, publishing to many S3 buckets and, finally, we stay under the Wyam config / same script or unit test (CI) - that's not a bad thing to have.

**Comment by daveaglick** [comment]
FYI - as an update to this issue, my plan is to provide direct support for Cake to act as the recommended publishing tool for Wyam sites. That will shift the responsibility for doing things like uploading finished sites to hosting providers onto the Cake build script. To the extent we can improve Cake by writing addins that will support behaviors that make sense for Wyam, everyone wins.

Since there's now a strategy in place, I'm going to close this issue. We can reopen more targeted issues as any work to extend Cake gets underway (probably in other repositories under the Wyam org).
