### ISSUE TITLE
Are there any instructions to running this on Azure?

### ISSUE THREAD

**Issue by FMastro** [statiqdev/Statiq#181]
Are there any instructions to running this on Azure?

**Comment by LokiMidgard** [comment]
I had created a deployment script for one of my Projects. it clones the Wyam repo and builds Wyam to create the website from the Wyam Project.

If you already have somewhere on your server you just need to call wyam exe with parameters for your output directory.

This is the deployment file I use: https://github.com/LokiMidgard/nota/blob/master/deploy.cmd
If you use this repo as continues deployment repository in Azure it should automatically build the site.
But beware there was a bug that not all temp files will be delete. So if you use it you maybe want to delete some files manually to save space.

I hope this somehow answers your question.

**Comment by FMastro** [comment]
Yes, I'll see if I can give this a try. On the bug you mention is this a bug with the script or a bug with Wyam?

**Comment by AlanBarber** [comment]
Here's a slightly simpler setup that doesn't rebuild wyam each time... https://github.com/AlanBarber/alanwyam

**Comment by daveaglick** [comment]
Thanks @LokiMidgard and @AlanBarber! FYI - I'm also planning on creating Cake addins (see #129) so that running Wyam as part of a larger Cake-driven build and deployment script becomes easier. There's also been some talk of integrating deployment support directly into Wyam (#179, #64), so this is definitely going to get easier in the future.

I'm going to close this issue for now since it looks like you've gotten some good feedback. Just reopen it or open a new issue if you have follow-on questions.
