### ISSUE TITLE
Continues build broken

### ISSUE THREAD

**Issue by AndiRudi** [statiqdev/Statiq#193]
The continues build is broken because the filename of the v0.11.1-beta is not WYAM.Zip and cannot be downloaded then.

**Comment by daveaglick** [comment]
Sorry about that - I thought I had added this change to the release notes, but now I see I missed it.

I had several reports of confusion since every zip version had the same zip name. The file name now includes the version, which was presumably needed anyway in a continuous build to get the correct release folder.

If that doesn't work for you, just let me know and I can also put a plain wyam.zip in every release alongside the versioned file name. Just let me know what works best.

**Comment by AndiRudi** [comment]
You should update the script (http://wyam.io/knowledgebase/continuous-integration) because it references the wyam.zip without the version number.

**Comment by daveaglick** [comment]
Good call - the script here works: https://github.com/Wyamio/Wyam.Web/blob/develop/appveyor.yml but the website is out of date. I'm going to reopen this issue to remind me to do that. Are you good to go now? Thanks!

**Comment by daveaglick** [comment]
The example AppVeyor script on the site is now fixed, and a note has been made on the release page. Thanks again for bringing this to my attention. Just let me know if you need anything else.
