### ISSUE TITLE
Thoughts on File System Resources

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#214]
I think that the changes to the file system library will help this, but I want to make sure that we stop thinking in terms of:

```
[input directory] --> [output directory]
```

I think it's limiting to think that we're going to copy everything from a single input location to a single output location.
#### Output

I came to this line of thought when writing the GenerateCloudSearchData module  (#213).  I realized that I needed to generate a file, but _the file shouldn't be in the web root_.  The file needed to be written somewhere, but it wouldn't be served by the web server.

This led me to think that I would write to an "outer" directory which could contain data, and a "root" directory that would be the root of the website.  This is what lead me to add the "--root" command line switch (same PR as prior...accidentally) so the preview server could bind to that "inner" directory.

```
[output directory]
   search_data.json
   [web root directory]
       [web files]
```

But I think this is even simplistic.  I should be able to write across the file system in a controlled way (meaning, not a ton of hard-coded paths all through my config).
#### Input

I need/want to be able to draw from multiple sources.  My "content" (meaning my Markdown files) should be stored away from all my "code" (meaning my .cshtml and all the supporting web files).  The workflow for these two types of files are different, and they get versioned and managed differently.  For content, Dropbox versioning is enough.  For code, Git is necessary.

Additionally, I can think of multiple scenarios where input file locations are varied.  You might read files in from locations A, B, and C.
#### Solutions?

I feel like it would be handy to "alias" different "roots."  So we could define a "content root" and a "template root" and an "assets root" and somehow use these aliases in the code and the config to determine where to read/write to/from.

Completely hypothetical code...

```
FileSystemLocations.Add("ContentRoot", "C:\somewhere...")
FileSystemLocations.Add("AssetsRoot", "C:\somewhereElse...")
FileSystemLocations.Add("WebRoot", "C:\somewhereElse...")
...
ReadFiles("ContentRoot", "*.md")
...
CopyFiles("AssetsRoot", "*.*", "WebRoot")
...
WriteFiles("WebRoot", "directory_name/index.html")
```

I see Wyam as a great tool for "content integration" (see my [blog post](http://gadgetopia.com/post/9272) about this) which seeks to unify content from disparate locations. At the most basic level, I'd like to see Wyam be able to easily draw resources in from widely disparate locations on the file system.

Does this make sense?  Will this be easier with the new file system abstraction

**Comment by deanebarker** [comment]
We can go one more step down the rabbit hole, of course, and consider things in terms of `IInputProvider` and `IOutputProvider`.  An input provider takes an obbject key (a file path, a database ID) and provides an array of bytes.  An output provider takes an object key (a file path, something else?) and an array of bytes, and does stuff with it.

```
InputProviders.Add("ContentRoot", new FileSystemInputProvider("C:\...");
InputProviders.Add("BigSqlServer", new SqlServerInputProvider() { ConnectionString = "..." });
```

Things like the file system a SQL Server could be both.  We could abstract them to "tubes."  You either get something out of a tube, or shove something down a tube.  Where the other end of the tube comes or goes, isn't Wyam's concern.

(The idea of Wyam writing directly to an Azure-hosted Redis cache makes my heart jump a bit in my chest...)

Wyam becomes "tube middleware" -- it manages the process of taking things from a tube, transforming it, and putting it into another tube.  Configuration dictates where the tubes begin and end.

**Comment by daveaglick** [comment]
The new IO abstraction will _partially_ cover what you're talking about here, but you've also raised some really good use cases that I hadn't considered yet. The good news is that this got me thinking and with a few small changes to my existing plan, I should be able to create an abstraction that is extremely flexible but also easy to use. Now is also the time to make the changes before the IO stuff gets baked into the next release.

Notes to self:
- Instead of exposing an `IConfigurableFileSystem` from `Engine.FileSystem` expose either a `DefaultFileSystem` class or an `IDefaultFileSystem` interface (not sure the extra interface is needed here since it will only be accessible from the CLI script and embedded scenarios, a concrete class may be sufficient). We also shouldn't need `IConfigurableFileSystem` in Wyam.Common - the plain `IFileSystem` interface should be enough.
- Remove all but the `GetXyzFile()` and `GetXyzDirectory()` methods from the `IFileSystem` interface (including removing `GetInputDirectories()`). Idea is that `IFileSystem` should be agnostic of how the particular files and directories are found and shouldn't know or care that the default implementation uses multiple input paths.
- Add fluent methods to the default file system. These methods will create a new instance of the default file system with adjust paths as specified. The purpose is to create a new file system that looks at different folders without having to entirely implement `IFileSystem` (reason why in next bullet).
  - `WithRootPath()`
  - `WithInputPath()`
  - `WithInputPaths()`
  - `WithAdditionalInputPath()`
  - `WithAdditionalInputPaths()`
  - `WithOutputPath()`
- Create extension method `WithFileSystem()` on `IPipeline` and `IModule` that allow you to substitute an alternate file system for the entire pipeline or a single module.

These changes together will let us write config files like:

```
Pipelines.Add("Foo",
    ReadFiles("*.md"),
    Markdown(),
    WriteFiles("*.html")
        .WithFileSystem(FileSystem.WithOutputPath(@"C:\SomeOtherOutputPath"))
);
```

Because it's all based around `IFileSystem` which returns `IDirectory` and `IFile`, you could even swap in totally custom file systems that do crazy things:

```
Pipelines.Add("Foo",
    ReadFiles("*.md"),
    Markdown(),
    WriteFiles("*.html")
        .WithFileSystem(new GitHubFileSystem("Wyamio/Wyam"))
);
```

Note that for custom file systems to work, adjustments might need to be made to `DirectoryPath` and `FilePath` (or an abstraction introduced) since they currently only support file-like path strings and operations like combining assume as much. There might also need to be some sort of connection between the file system and the kind of path (I.e., passing in a GitHub-style path string wouldn't make any sense to the default file system). Perhaps there should be two "flavours" of path strings, the normal one and URIs. Then the `DirectoryPath` and `FilePath` could accept either and act accordingly, seamlessly converting to a file-based string when requested and throwing exceptions if you try and do something you shouldn't. For example, if you pass a file string based DirectoryPath to the `GitHubFileSystem` and not the appropriate URI format.

**Comment by daveaglick** [comment]
Even better - remove the distinction between input files and output files in a single file system and use separate file systems for input files, output files, and root. Then `IFileSystem` just needs `GetDirectory()` and `GetFile()` methods.

**Comment by daveaglick** [comment]
Had a long thought on this over the weekend and came up with a better approach. Notes follow (mostly for my own sake, but feel free to comment):
![image](https://cloud.githubusercontent.com/assets/1020407/13408822/ce4b0176-defd-11e5-9f6a-f073bb7e2eb3.png)
(copied from OneNote - not sure why it wants to paste a png, but who am I to argue?)

**Comment by daveaglick** [comment]
This is now (mostly) implemented. The remaining functionality of changing the file system per-pipeline or per-module is being tracked in #270.
