### ISSUE TITLE
Unable to find Razor partials in the current dir [0.11.2-beta]

### ISSUE THREAD

**Issue by martinvobr** [statiqdev/Statiq#244]
Prerequisites:
- input dir is not named 'input'
- config.wyam is inside the input dir
- current dir is same as input dir
- input dir named 'input' is removed in config.wyam as suggested in https://github.com/Wyamio/Wyam/issues/241

Example files

```
/web.src/
/web.src/wyam.config
/web.src/SomeDir/index.cshtml
/web.src/SomeDir/_localPartial.cshtml
/web.src/Shared/_sharedPartial.cshtml
```

Content of /web.src/SomeDir/index.cshtml:

```
@Html.Partial("_localPartial")
@Html.Partial("_sharedPartial")
```

_SharedPartial is found, no problem.

_localPartial throws following exception:

```

            Error while executing module Razor
        Error while executing pipeline ContentTest
Exception during execution: System.InvalidOperationException: Partial view ./_localPartial not found in
/../SomeDir/_localPartial.cshtml
/../SomeDir/Shared/_localPartial.cshtml
/../SomeDir/Views/_localPartial.cshtml
/../SomeDir/Views/Shared/_localPartial.cshtml
/../_localPartial.cshtml
/../Shared/_localPartial.cshtml
/../Views/_localPartial.cshtml
/../Views/Shared/_localPartial.cshtml
/_localPartial.cshtml
/Shared/_localPartial.cshtml
/Views/_localPartial.cshtml
/Views/Shared/_localPartial.cshtml.
   at Wyam.Modules.Razor.HtmlHelper.<RenderPartialCoreAsync>d__6.MoveNext() 
```

I've used https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx to check which files are in fact loaded.

Exception message uses this path:
/../SomeDir/_localPartial.cshtml

ProcMon sees this path:
/../_localPartial.cshtml

(the `SomeDir` folder is missing).

Repro archive can be downloaded from http://www.vobr.cz/wyam/wyam-repro-partial-in-current-dir.zip

**Comment by daveaglick** [comment]
Thanks for the detailed report and reproduction. Starting to look at this now...

**Comment by daveaglick** [comment]
Found the problem - the root cause is that when the input (or output) path is a simple ".", some of the path helpers don't deal with that very well. I added a fix that will resolve the problem in this case.

Thankfully, this is one of the main reasons why I'm switching to a more abstract IO library. The new stuff deals with paths that have ".", "..", etc. much, much better. Once everything is switched over, the code I patched won't be needed any more.

For now though, the latest develop branch has this fix and it'll be in the next release. Thanks again for the very detailed report - saved me _tons_ of time digging into this.
