### ISSUE TITLE
WriteFiles question 

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#261]
Hello guys, 

We started having the following message while Wyam generates the web site:

```
An extension or delegate was specified for the WriteFiles module, but the metadata key WritePath took precedence for the document with source ..\FAQ.md. Call UseWriteMetadata(false) to prevent the special write metadata keys from overriding WriteFiles constructor values
```

Not too sure why it is happening and what might be a solution for that.

**Comment by daveaglick** [comment]
The deal here is that WriteFiles will always use the value of the "WritePath" metadata if it is present, even if a constructor is used that specifies a path that would contradict with the metadata value. Since WriteFiles also has an empty constructor that's designed to look at the "WritePath" metadata, using one of the alternate non-empty constructors triggers a warning since you may not have meant to override the behavior you specified in the constructor (like setting an extension).

The warning won't break the build, but you can get rid of it in one of three ways:
- Use the empty constructor for WriteFiles, but this would assume _all_ the input documents have the correct "WritePath" metadata.
- Don't set (or clear) "WritePath" on all of the input documents, in which case the behavior in the non-empty constructor will be used (whether that's changing the extension or using a delegate to get the path).
- Use the fluent method `UseWriteMetadata(false)` to invert the precedence and use the behavior in the constructor over a metadata value for "WritePath" if it exists.

I'm pretty sure this was always the behavior of the module, the warning just makes it obvious now when there might be an unintended conflict.

**Comment by avishnyakov** [comment]
.UseWriteMetadata(false) does the job, thanks!. Solved.

**Comment by avishnyakov** [comment]
Kinda weird. Have no ideas why Wyam thinks we change WritePath - it is not changed.
We have MD files with FileName attr in the MD, and later before WriteFiles we say:

```
FileName("FileName").WithAllowedCharacters(new[] {".", "-"}),
```

That gives tons of warnings (why?)

Later then, okay, we put .UseWriteMetadata(false) and it removes the log message and ignores FileName attr in the MD. Sweet, we don't need that. Adding .UseWriteMetadata(true) suggests to use  FileName attr in the MD and brings back the warnings.

How come all that makes sense?

**Comment by daveaglick** [comment]
That's because the FileName module actually doesn't add a "FileName" metadata key. It adds "WriteFileName" and "WritePath", properly formatted for use as a file system filename (see the bottom of http://wyam.io/modules/filename).

The idea here is that if you use the FileName module to set "WritePath", then you probably want to use the filename that the FileName module came up with (otherwise, why use the module at all). However, by using a non-empty constructor in the following WriteFiles module, you're also saying, "hey, I want my output filenames to look like this" (whether it's by specifying an extension or delegate to the WriteFiles module). It'll still use the "WritePath" that the FileName module came up with since that takes precedence over the WriteFiles constructor (unless `UseWriteMetadata(false)` is called). 

However, there's probably a conflict and we may not be doing what the user intended - the user specified both a "WritePath" metadata value for the document _and_ a WriteFiles constructor. We can only use one of those options. Hence the warning.

**Comment by daveaglick** [comment]
@avishnyakov Are you good on this question now (I.e., is it okay to close)? If not, that's fine - what can I help clarify further?
