### ISSUE TITLE
HelperResult question

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#262]
Is it possibly to craft something like that in the Razor template? 

The thing is that RenderBody returns Wyam's HelperResult class and we aren't too sure where to go with it. So is body is empty (like empty page is there), pushing dummy warning.

```
@{
                var body = RenderBody();                   
            }

            @if (!string.IsNullOrEmpty(body.ToString()))
            {
                @body.ToString()
            }
            else
            {
                <div class="well well-lg">
                    Body is empty!
                </div>
            }
```

**Comment by daveaglick** [comment]
This part is directly from Razor (it's only been reimplemented for compatibility reasons, but the `HelperResult` and `RenderBody()` code remains the same as what ASP.NET uses). The `HelperResult` class primarily serves as a wrapper around a delegate that can write to the result stream (that way the code contained in the body and any nested bodies doesn't have to be evaluated more than once). It's fundamental to the way Razor works.

You _could_ force rendering of the returned `HelperResult` by calling something like this:

```
TextWriter writer = new TextWriter();
HelperResult result = RenderBody();
result.WriteAction(writer);
// ...
```

What I don't know is if that will "consume" the Razor pages that are being written. It's possible that by calling the write action the page can't be rendered when Razor goes to process it. In that case, you'll want to be sure to take the rendered text content and output it directly in your page with `Html.Raw()`.

Hope that helps. It's very unlikely I will add more functionality around this in Wyam since the intent is to track the ASP.NET Razor libraries as closely as possible. Idealy, I'll even be able to rip out a lot of the reimplementation once the final versions of ASP.NET Core ship.
