### ISSUE TITLE
Wyam 0.12 file pattern matching behavior changed

### ISSUE THREAD

**Issue by miere43** [statiqdev/Statiq#267]
For example, we have this project structure:

```
config.wyam
input/cc.md
input/123/copy.js
```

In Wyam 0.11.5, when we pass pattern `"*"` to `CopyFiles` constructor, then we will get all files in all nested folders:

```
input/cc.md
input/123/copy.js
```

In Wyam 0.12, we will get only file from top directory:

```
input/cc.md
```

config.wyam

``` c#
===

---
Pipelines.Add("Copy files",
    CopyFiles("*").Where(file =>
    {
        string x = file.Path.FullPath;
        Console.WriteLine(x);

        return true;
    })
);
```

**Comment by daveaglick** [comment]
Yeah, a lot changes in 0.12. Since I was going to have to make a couple breaking changes, I went ahead and took the opportunity to rethink several things that should change for the better. I'm working on putting together clear migration docs before it goes live, but you can get an idea here:
https://github.com/Wyamio/Wyam.Web/blob/develop/Input/knowledgebase/0-12-0-migration.md

In this specific case, the difference is due to the use of a new globbing engine. In the long run it provides a _much_ more powerful and flexible file search capability. In the near-term it means that existing sites will have to be migrated to the new globbing syntax. Thankfully this isn't too rough.
- `*` now means any number of characters in a directory or file name without descending
- `**` means any number of characters in a directory at any depth

In your case, the search string should probably now be `/**/*`

Another source of examples of the new globbing engine is the unit tests: https://github.com/Wyamio/Wyam/blob/develop/src/Wyam.Core.Tests/IO/Globbing/GlobberTests.cs

**Comment by daveaglick** [comment]
And we're out! The new globbing syntax is more fully described here: http://wyam.io/getting-started/io#globbing
