### ISSUE TITLE
Build on Azure using Cake not working.

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#287]
Hi,

I tried to update my website to use the current Wyme build and deploy via Cake.
But Wyam no longer works on the website, it just freeze without doing anything.
The output looks like this

```
========================================
Build
========================================
Executing task: Build
Wyam version 0.12.2-beta
An error occured when executing task 'Build'.
Error: Wyam: Process returned an error (exit code -1).
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
One or more errors occurred.
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
```

locally everything works fine. But on Azure the application stops right after writing the Version to the logs. Even the ASCII art is not displayed.

I haven't updated for a long time, so I don't know since when this behavior happens.

**Comment by daveaglick** [comment]
It's interesting that you're getting the version stamp but not the ASCII art. That suggests the problem has something to do with the command line parsing since that's the only thing that happens in between the version stamp and the logo.

What does your Build task look like?

Could you also try swapping out the build task with the following - I'm curious if it'll even print the command line help:

```
Task("Build")
    .Does(() =>
    {
        Wyam(new WyamSettings
        {
            ArgumentCustomization = args => args.Append("--help")
        });
    });
```

And one more question so I can try to replicate - what Azure service are you using to build this?

Thanks, and sorry for the trouble. I know it's a lot of cheese-moving right now - that should die down soon.

**Comment by LokiMidgard** [comment]
Thats my build Task:

```

Task("Build")
    .Does(() =>
    {
        Wyam(new WyamSettings
        { 
            OutputPath  = websitePath,
            Verbose  = true,
            LogFilePath = "wyam.log"
        });        
    });
```

If I exchange the Build Task with yours, it prints the help, and then frezes.

I was also able to reproduce this behavior by chance on my machine. When I use a Build task from VS code to start cake.cmd, it also stops working. I will put some print lines in the code to narrow it down.

**Comment by daveaglick** [comment]
> I was also able to reproduce this behavior by chance on my machine.

That's great! Being able to locally reproduce is so much easier. I'll try the same. Let me know if you find anything else...

**Comment by LokiMidgard** [comment]
Ok, at least I think I've found the Problem which cause the freeze localy. I still have to test if it also cause this problem on Azure.

`Console.IsInputRedirected` is true. And the call to `reader.ReadToEnd()` never returns.

**Comment by daveaglick** [comment]
Great sleuthing.

That makes a lot of sense as the culprit - now that you've triggered my memory, this was a problem back when this was implemented in #222. Looking back through the notes on that issues, the `Console.IsInputRedirected` flag was _supposed_ to indicate that there was already something waiting to be picked up so this exact problem wouldn't happen (there's also [this Stack Overflow question](http://stackoverflow.com/questions/35375826/how-do-i-capture-standard-input-if-it-exists-without-waiting-for-it)). Apparently that isn't a good indicator after all in certain situations.

This is going to require a little more digging, but now that you've found a repeatable use case I'll try some things to get it working. At worst, I'll just disable capturing standard input or make it a CLI option - getting the build to run in shelled-out environments is a much higher priority.

**Comment by daveaglick** [comment]
BTW - I have also been able to replicate in VS Code, been working on a resolution.

**Comment by daveaglick** [comment]
Thanks again for this report, and for pinning down the problem. It's now resolved using a bunch of ugly thread hacking, but it works. It turns out it's nearly impossible to handle fetching standard input in a safe non-blocking way. Since stdin is just a stream, if the caller opens it but doesn't pass anything (as it looks like both VS Code and Azure do), there's no good way to timeout the stream.

In any case, this is going to end up affecting anyone trying to build in VS Code, Azure, or any other environment that opens the stdin stream so I'm going to publish a new version first thing tomorrow morning or possibly later tonight (I've got to head out for a family thing right now).

**Comment by daveaglick** [comment]
0.12.3 has been released with the fix for this issue:
https://github.com/Wyamio/Wyam/releases/tag/v0.12.3-beta
