### ISSUE TITLE
56 Tests failing with UnauthorizedAccessException 

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#293]
Just wanted to run he tests. But 56 of them are failing. It seams like the local Fileprovider tries to write to VisualStudio installation directory. I don't think that's intended.

One of the Testresults:

```
Testname:   CombinesMetadata
Test FullName:  Wyam.Core.Tests.Modules.Control.MergeTests+ExecuteMethodTests.CombinesMetadata
Testquelle: C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core.Tests\Modules\Control\MergeTests.cs Zeile 45
Testergebnis:   Fehlgeschlagene
Testdauer:  0:00:00,607

Ergebnis StackTrace:    
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bei System.IO.DirectoryInfo.Create()
   bei Wyam.Core.IO.Local.LocalDirectory.<Create>b__9_0() in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core\IO\Local\LocalDirectory.cs:Zeile 36.
   bei Wyam.Core.IO.Local.LocalFileProvider.<>c__DisplayClass6_0.<Retry>b__0() in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core\IO\Local\LocalFileProvider.cs:Zeile 53.
   bei Wyam.Core.IO.Local.LocalFileProvider.Retry[T](Func`1 func) in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core\IO\Local\LocalFileProvider.cs:Zeile 41.
   bei Wyam.Core.IO.Local.LocalFileProvider.Retry(Action action) in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core\IO\Local\LocalFileProvider.cs:Zeile 51.
   bei Wyam.Core.IO.Local.LocalDirectory.Create() in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core\IO\Local\LocalDirectory.cs:Zeile 36.
   bei Wyam.Core.Execution.Engine.Execute() in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core\Execution\Engine.cs:Zeile 116.
   bei Wyam.Core.Tests.Modules.Control.MergeTests.ExecuteMethodTests.CombinesMetadata() in C:\Users\Patrick\Source\Repos\Wyam\src\Wyam.Core.Tests\Modules\Control\MergeTests.cs:Zeile 59.
Ergebnis Meldung:   System.UnauthorizedAccessException : Der Zugriff auf den Pfad "C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/output" wurde verweigert.
```

**Comment by daveaglick** [comment]
Hmm... This is probably caused by different working directories for the various NUnit test runners (I use Resharper, but it looks like you're running NUnit from either the command line or from the VS runner). Specifically, NUnit changed the way the working directory is handled - you're now supposed to get the test directory via `estContext.CurrentContext.TestDirectory`.

More importantly though, this has exposed a deeper problem. None of the tests should actually be writing to the file system in the first place. One goal of the new abstract file IO support was that we would be able to swap out the local file system during tests (and there are already classes in `Wyam.Testing` to help with this). I'll take a closer look.

**Comment by daveaglick** [comment]
Found the problem. Several of the tests in Core create an `Engine` instead of using mocks (which is by design - I wanted at least a few tests to behave more like integration tests than unit tests). However, there's a call in the `Engine` that creates the output directory if it doesn't exist and right now there's no way to turn that off. That's what's causing the crash - the engine tries to create the output directory while the working directory (and thus the parent of the output directory) is set to that VS one.

I don't like the behavior - there may be times when you want to run without outputting anything or run in an embedded more where you can't create a directory, especially now that alternate file providers are a thing. To resolve this I'm going to remove the code that creates the output directory eagerly and instead rely on the `IFile` implementations to create the directory only when they actually need to write to it.
