### ISSUE TITLE
Cloned repo -> Build fail.

### ISSUE THREAD

**Issue by StachuDotNet** [statiqdev/Statiq#32]
![](http://i.imgur.com/cPvMwFM.png)

Will look deeper into this tonight; wanted to give quick feedback since you just released.

**Comment by StachuDotNet** [comment]
Seems to be specific to this project: Wyam.Modules.Razor

![](http://i.imgur.com/eU3Sg8f.png?1)

Let me know if I can help at all.
Running VS2013, Win 8.1

**Comment by daveaglick** [comment]
Before I add a note to the docs and readme, do you mind testing if adding the Roslyn nightly feed from MyGet as an alternate package source helps (Should be under Options -> Package Manager -> Package Sources in VS)? The feed is at `https://www.myget.org/F/roslyn-nightly/`

**Comment by StachuDotNet** [comment]
That feed was already configured. Maybe I'm missing something.

**Comment by daveaglick** [comment]
Hmm - it could end up being a little more complicated. I need to use the Roslyn nightly feed because the RC on the official NuGet feed is missing some scripting capabilities I use. Unfortunately the nightly feed doesn't maintain older versions. So when I reference a particular nightly build package, it's only good for that point in time. I can continue to build locally because I've already pulled down the packages, but anyone else trying to build is going to have problems.

I've already seen this issue when sending to AppVeyor for CI, but I just got in the habit of updating to the latest nightly before pushing to master and triggering a build. It never occurred to me that this is also going to cause a problem for anyone else building from source...

What I'll probably end up doing is committing the nightly packages to the repo until the official NuGet feed gets an updated RC. Thanks again for pointing this out! I probably won't get it sorted out until tomorrow...

**Comment by StachuDotNet** [comment]
Sounds good. I look forward to playing with the software :)

**Comment by daveaglick** [comment]
If you're still around and have a minute (if not, there's certainly no rush), do you mind trying one more time from a clean clone? I checked in the packages from the nightly feed and was able to build from scratch on both my own system and on a clean VM.

**Comment by StachuDotNet** [comment]
Clean build attempt:

![](http://i.imgur.com/AV8eK9H.png)

Maybe I'm doing something weird on my end? This isn't my normal dev machine.

**Comment by StachuDotNet** [comment]
Do NuGet packages get cached anywhere else, maybe?

**Comment by daveaglick** [comment]
Not that I know of - it should all be in the local packages folder. I'm also guessing this isn't just your system - there's enough bleeding edge here it's probably some weird mix of VS or NuGet version, package version, and dependency resolution.

The one you're having trouble with is on the main NuGet feed, but it's part of all the Asp.Net v5 stuff which can be goofy. What version of VS are you on? I'll try to stand up a matching VM in Azure tomorrow and see if I can repro.

Thanks again for the help troubleshooting.

**Comment by StachuDotNet** [comment]
Vs2013, win 8.1.
Will try on work machine in the morning and let you know. That machine has 2013 and 2015.

-----Original Message-----

**Comment by StachuDotNet** [comment]
At work. Have coffee.
Clone -> open in vs2013 -> same failure.
git clean -fd -> open in vs2015 -> success!

Now that it works, I can play around with it a bit :)

**Comment by daveaglick** [comment]
I'm going to go ahead and close this issue out. Let me know if you have any more problems. Hope your first experiments were worth the trouble :)

**Comment by RobAMills** [comment]
I just built the latest version with no issues using both VS 2013 Community and VS 2015.

**Comment by daveaglick** [comment]
@ramsoft - Great, thanks for the update. Always nice to get independent confirmation on hard-to-replicate issues like build problems.
