### ISSUE TITLE
Crash when loading packages without network access

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#326]
See #317

**Comment by LokiMidgard** [comment]
I reproduce this following:
1. I run the build command,
2. disconnect from internet
3. build again

I expect the second build works, because everything was downloaded for the first. Do I need to specify some extra parameter. I can't find the downloaded packages in the current folder. Most likely they are in the global cache.

**Comment by daveaglick** [comment]
Your expectation is correct, the second build should work. Wyam now uses the global NuGet package cache by default, so you can find where they're going with `nuget locals -list all` (look for the `global-packages` value).

**Comment by daveaglick** [comment]
I was able to repro this and added more broad exception handlers with retries that exclude remote resources.
