### ISSUE TITLE
Tree Module usage

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#350]
The Tree module only returns the roots of the trees as Output documents. All other documents get consumed.

Is this change intended? I haven't found this mentioned in the documentation.

And how is the intended use now?

**Comment by daveaglick** [comment]
Yeah, this change is still in flux. It changed recently in the develop branch due to work for the docs recipe. Creating things like navigation bars are much easier if the tree is already nested.

There's a new `Flatten` module that can flatten any document tree structure, so it can just be used after the `Tree` module to get the old behavior. I've also not totally settled on the new behavior - planning to either add a `Tree.Flatten()` fluent method to flatten the tree right in the `Tree` module or reverse the behavior and revert the `Tree` module to how it was with a `Tree.Nested()` method to nest the structure.

Thoughts?

**Comment by LokiMidgard** [comment]
I think i would prefer the `Nested()` Method. I assumed that a Metadata module would most likely change the metadata and would not consume some of the documents. If you stick with the Flatten approach, it should be highlighted in the docs.

Maybe the Docs could have a section (Like Metadata) where the output the module creates is described.
- All Input Modules
- all Input modules that are Roots
- all Input Modules and the Output modules of Module X

**Comment by daveaglick** [comment]
Sounds reasonable - I'll go back to the old behavior and add an additional `.WithNesting()` fluent method to nest the tree if desired.
