### ISSUE TITLE
Example of using CopyFiles().To()

### ISSUE THREAD

**Issue by randalvance** [statiqdev/Statiq#362]
Are there any examples of using CopyFiles().To() to copy certain files to a custom output path. I searched the examples in this repo and found none. 

Do I have access to IExecutionContext within the wyam config file?

**Comment by daveaglick** [comment]
Happy to help -

> Are there any examples of using CopyFiles().To() to copy certain files to a custom output path.

Probably not. It's certainly useful, but I don't think any of the examples use it. Here's how it would look if you had a pipeline that copied all of the `.png` files from your `input` folder to `C:\Temp`:

```
Pipelines.Add("CopyToTemp",
    CopyFiles("**/*.png")
        .To(originalFile => new DirectoryPath("C:/Temp").CombineFile(originalFile.Path.FileName))
);
```

The `.To()` method accepts a delegate where the input is an [`IFile`](http://wyam.io/api/Wyam.Common.IO/IFile) of each file that matches the globbing pattern giving in the `CopyFiles` constructor and the output is a [`FilePath`](http://wyam.io/api/Wyam.Common.IO/FilePath) where you want that file copied to.

> Do I have access to IExecutionContext within the wyam config file?

Not directly. Since the configuration is read before actually running any pipelines, there's no execution context yet. The job of the configuration file is to set everything up prior to execution of the pipelines. That's why so many modules accept delegates that do contain the `IExecutionContext`, so that you can access it "at execution time" and return the correct value. The configuration script is essentially derived from [`ScriptBase`](http://wyam.io/api/Wyam.Configuration.ConfigScript/ScriptBase) so you can see all the properties available inside the script from there.

In the case of `CopyFiles.To()`, the delegate doesn't have a `IExecutionContext` input so there's no direct way of getting the execution context while calculating the output path. There is a workaround though. The `Execute` module is designed (among other uses) to provide an execution context for modules that don't have delegates which directly expose one.

You would use it like this if you wanted to access the `IExecutionContext` at execution time, for example to calculate the relative path for each file. Since the `IFile.Path` is an absolute path, you would need to make it relative to your input folder in order to copy the whole hierarchy to the temporary folder starting from there:

```
Pipelines.Add("CopyToTempWithHierarchy",
    Execute(context => 
        CopyFiles("**/*.png").To(originalFile =>
        {
            DirectoryPath inputPath = context.FileSystem.GetContainingInputPath(originalFile.Path);
            FilePath relativePath = inputPath.GetRelativePath(originalFile.Path);
            return new DirectoryPath("E:/Temp/CopyTest").CombineFile(relativePath);
        })
    )
);
```

Just let me know if you have any more questions about how this all works.

**Comment by daveaglick** [comment]
I'm going to ahead and close this issue for now. Feel free to reopen it (or open a new one) if you have any more questions.

**Comment by randalvance** [comment]
Thanks for the response!
