### ISSUE TITLE
Allow the Razor Module to have the ViewStart.cshtml file set rather than using a magic string

### ISSUE THREAD

**Issue by mschumaker** [statiqdev/Statiq#37]
Currently the ViewStart used by the Razor Module is magic filename "_ViewStart.cshtml".  Rather than using a magic filename, have it set via the constructor.  This allows the more than just directory level organizing of the cshtml files.  For example, on your site, rather than having a separate _ViewStart.cshtml in each subdir, you could have PostViewStart.cshtml, and you can specify a path to it, so you don't have to have such long Where predicates in your FileReader Module since all those files can live in a different subdir.

**Comment by daveaglick** [comment]
Thanks for the suggestion. This is certainly possible - the magic string for the ViewStart file name is buried, but it's in there and can be changed to accept alternate or custom names without much trouble. I would like to understand how this should work and what the use case is a little better...

So right now, when a page is rendered by the Razor module, it looks in the folder where the page is located for `_ViewStart.cshtml` and then crawls up the folder hierarchy if it doesn't find one. You're suggesting that as an alternative, you could hard-code a ViewStart path for all Razor pages handled by a given instance of the Razor module by supplying it in the module constructor, correct? I can see this being helpful if you have multiple Razor module instances - is that the case here? I'm also not sure I follow the problem with Where predicates in the FileReader module - would you be able to post an excerpt of your config file so I can better understand?

**Comment by mschumaker** [comment]
For example this

```
Pipelines.Add("Posts",
    ReadFiles(@"posts\*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Replace("<pre><code>", "<pre class=\"prettyprint\"><code>"),
    Concat(
        ReadFiles(@"posts\*.cshtml").Where(x => Path.GetFileName(x)[0] != '_' && Path.GetFileName(x) != "index.cshtml"),
        FrontMatter(Yaml())     
    ),
    Razor(typeof(RazorPage)),
    WriteFiles(".html")
  );
```

would turn into

```
Pipelines.Add("Posts",
    ReadFiles(@"posts\*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Replace("<pre><code>", "<pre class=\"prettyprint\"><code>"),
    Concat(
        ReadFiles(@"posts\*.cshtml").Where(Path.GetFileName(x) != "index.cshtml"),
        FrontMatter(Yaml())     
    ),
    Razor(typeof(RazorPage),"razor\PostViewStart.cshtml"),
    WriteFiles(".html")
  );
```

Any cshtml files referenced by PostViewStart.cshtml would be relative razor\  in your case your _Layout.cshtml could be moved.

**Comment by daveaglick** [comment]
Ah, I see now - the idea is that if you can specify an alternate location (and name) for ViewStart, you don't have to put it in the same folder structure as the actual Razor pages and therefore don't need to exclude it when reading files. Good idea.

I like the flexibility of being able to specify an alternate ViewStart location/name, so I'll definitely add it.

I'm not sure it resolves this specific problem in all cases, though. For example, if I had a subfolder under `posts` for posts about a specific topic and I wanted it to have a slightly different layout (to include a link at the top of the post, for example) this wouldn't help me. I would normally just add an extra `_ViewStart.cshtml` file to the subfolder with the alternate layout. However, if I specify a ViewStart to use for all Razor pages processed by the Posts pipeline, it wouldn't pick up on the extra ViewStart I added to the subfolder.

I think what's really going on is that there are certain files that _look_ like normal Razor pages (in that they have the same extension), but actually aren't and shouldn't be processed and output as such. I've attempted to address this in my own sites by supplying predicates to ReadFiles so those files don't make it into the pipeline. There are probably a few other ways to address this:
-  Allow `_ViewStart` and `_GlobalImport` (without an extension) by default in addition to `_ViewStart.cshtml` and `_GlobalImport.cshtml`. That way, a ReadFiles for the `.cshtml` extension wouldn't bring them in.
- Make the Razor module ignore documents with a `SourceFileName` of `_ViewStart.cshtml` or `_GlobalImport.cshtml`.
- Provide an option for the Razor module to ignore any document that has a `SourceFileName` starting with an underscore.

I'll have a think on which of the ideas to implement above (in addition to your suggestion of explicitly specifying location and name). Thanks for pointing this out.

**Comment by mschumaker** [comment]
In regards to your 3rd paragraph "'m not sure it resolves this specific problem in all cases, though...".  You are correct, but then again I'm not sure there is anyway you could reduce the number of razor files.  I mean, if you have a slightly different layout, you need a new file.  But you wouldn't need to put that file in your directory structure, and if you wanted to share the same layout, you now can.

When I first started looking at Wyam, I was very puzzled how you got the markdown out formatted.  So I then looked through the code and found the ViewHierarchyUtility class and it started to make sense.  Then I read the documentation, since after all else fails, read the documentation.  So there was an aspect of "By what magic does this work" for me personally.

I think it useful to be able to separate your content from view, In regards to your subfolder.  In regards to your subdir, I would use ReadFiles(@"posts*.md").TopDirectoryOnly() then setup different pipelines for each subdir.  

I'll try to do some work on this on my fork.  If I get something working, I'll do a pull request.

Cheers

**Comment by daveaglick** [comment]
Very cool - any suggestions documentation-wise to make the learning curve a little easier now that you've gotten past it?

After thinking about this issue, I'm pretty sure I want to do all of the following:
- Add a fluent method to the Razor module: `SetViewStart(string path)` - allows you to set an alternate ViewStart for all Razor files processed by that module instance by specifying a path.
- Add a fluent method to the Razor module: `SetViewStart(Func<IDocument, string> path)` - allows you to set an alternate ViewStart for all Razor files processed by that module instance by specifying a path based on the current document (I.e., base it on document name, folder, some metadata, etc.) - returning null will result in the normal `_ViewStart.cshtml` search. The cool thing here is that you could use something like metadata to determine the "type" of each page and then use a different ViewStart (and thus layout) accordingly.
- Change the default behavior of the Razor module so that it ignores (does not return an output document for) files that have a `SourceFileName` metadata value starting with an underscore - this will ignore `_ViewStart.cshtml`, `_GlobalImport.cshtml`, and any partials (which usually use the underscore convention too).
- Add a fluent method to the Razor module: `IgnoreUnderscoreFiles(bool ignore)` that allows you to override the new default behavior for that module instance.

The fluent methods are because I try to stay away from overloading the module constructors for optional configuration. That keeps the constructors clean and avoids overload explosion as you get more and more options. The combination of specifying alternate ViewStart files and ignoring underscore files by default should make the Razor module easier to use in nearly all cases. And since you have the option of doing either or both, it should be really flexible too.

Thanks a lot for working through this with me. This kind of feedback is exactly the kind of thing I always hope to receive when putting a new project out there.

**Comment by mschumaker** [comment]
I like the fluent interface.  It works well for this.  How about the below?  if you pass null or empty string to the SetSourceFileNameIgnoreSuffix it doesn't ignore any files.

```
public class Razor : IModule 
{
    public Razor(Type basePageType = null){...}
    public Razor SetViewStart(String path){...}
    public Razor SetViewStart(Func<IDocument,String> pathFunc ){...}
    public Razor SetSourceFileNameIgnoreSuffix(String suffix = "_" ){...}
}
```

**Comment by daveaglick** [comment]
I like your idea (setting any prefix to ignore) even better. This is all now implemented in the develop branch, though I changed `SetSourceFileNameIgnoreSuffix` to `IgnorePrefix`. It may be a few more days until I get a couple more changes I had in mind ready to roll and release a new version. Thanks again for the feedback - keep it coming.
