### ISSUE TITLE
Best method for multiple pipeline outputs?

### ISSUE THREAD

**Issue by JonDouglas** [statiqdev/Statiq#374]
I'm currently working on getting wyam working in a `netcore` mvc project and I'm partially successful. One thing I'm trying to do is create an `Index.cshtml` inside my `Views/Blog/` folder so the overall theme can be applied. However I want my actual md->html blog posts to go inside of a `Blog/` folder at the root of the website(or other location). However I haven't found much documentation on how I can specify two different `FileSystem.OutputPath` for a pipeline. Is there a way to specify the `OutputPath` for an individual pipeline? That way I can have one pipeline sent to the `Views/Blog/` folder and the other to the `Blog/` folder?

Here is my current `config.wyam` based on the aspnetmvc sample:

```
#n -p Wyam.Markdown
#n -p Wyam.Yaml
#n -p Wyam.Razor
#n Microsoft.AspNetCore.Mvc.TagHelpers
#n Microsoft.AspNetCore.Identity

#a **/*

FileSystem.InputPaths.Add("ImprovForAll.Web/Posts");
FileSystem.OutputPath = "ImprovForAll.Web/Views/Blog";

Pipelines.Add("Posts",
	// Read all Markdown files under the "Posts" directory
	ReadFiles("*.md"),
	// Load any frontmatter and parse it as YAML markup
	FrontMatter(Yaml()),
	// Render the Markdown content
	Markdown(),
	// Compile and render the page layout template
	Razor(),
	// Write the files as HTML
	WriteFiles(".html"),
	// Order the files by publish date
	OrderBy(@doc.Get<DateTime>("Published")).Descending()
);

Pipelines.Add("Index",
	// Read all non-layout Razor files under the "Posts" directory
	ReadFiles("**/{!_,}*.cshtml"),
	// Evaluate the Razor page(s)
	Razor(),
	// Write the file(s) as HTML
	WriteFiles(".cshtml")
);
```

I'd like to help document this in anyway I can via a blog post or updating the existing documentation with a better MVC sample.

Thank you!

**Comment by daveaglick** [comment]
Cool use case!

What you want to do is easy if you specify a relative path to `WriteFiles` instead of just an extension. The `WriteFiles` module starts from the default output path, so you'll just need to take it up a level and then back down into your root-level `Blog` folder. It would look something like this:

```
Pipelines.Add("Posts",
    // ...
    WriteFiles("../Blog/" + @doc.FilePath(Keys.RelativeFilePath).ChangeExtensions(".html").FullPath),
    // ...
);
```

Long-term, there's an open issue to do exactly what you were thinking with regard to changing output paths (and other paths) per-pipeline: https://github.com/Wyamio/Wyam/issues/270#issuecomment-206600037. Since this is now the fourth request for per-pipeline path adjustments, I'll probably move that issue a bit higher in the queue.

**Comment by daveaglick** [comment]
Checking in - did the approach above resolve your immediate issue? If so, I'll go ahead and close this one since there's already another issue tracking the more general pipeline path adjustment feature.

**Comment by JonDouglas** [comment]
@daveaglick This will work well! Feel free to close this out. Once netcore RC4 tooling becomes a bit more stable, I should have a blog about this topic. However that might be awhile!
