### ISSUE TITLE
Generating Json Feed

### ISSUE THREAD

**Issue by oliverw** [statiqdev/Statiq#381]
I'm struggling to generate a Json Feed for all posts similar to the output of <code>GenerateFeeds()</code>. Before I keep trying is this even possible?

**Comment by daveaglick** [comment]
It's definitely possible. One of the fundamental design goals of Wyam is to make it flexible enough to handle any generation scenario. More of a toolkit than a "Xyx Generator".

That said, the default recipes don't inherently support outputting JSON from your posts, so it'll take a little bit of customization. What you'll probably want to do is place an extra [pipeline](https://wyam.io/docs/concepts/pipelines) in your `config.wyam` file. That pipeline can read the documents that were generated by the posts pipeline and then create and output your JSON file.

What data do you want the JSON file to have? If similar to an RSS feed, I'm assuming title, date, link, excerpt, and content? Instead of using the existing [GenerateJson module](https://wyam.io/modules/generatejson) that creates a JSON representation of a specific metadata value per-document, you'll probably want to use a small custom module that can aggregate all of the documents together.

I expect the final `config.wyam` might look something like this (assuming you're also using the blog recipe):
```
public class GetJsonDocument : IModule
{
    public IEnumerable<IDocument> Execute(
        IReadOnlyList<IDocument> inputs, IExecutionContext context)
    {
        StringBuilder json = new StringBuilder();
        json.AppendLine("{");
        foreach(IDocument post in inputs)
        {
            // Use calls like post.String("Title") to get the values
            // and place them in the StringBuilder as JSON data
        }
        json.AppendLine("}");
        return context.GetDocument(json.ToString());
    }
}

Pipelines.Add("CreateJson",
    Documents(BlogPipelines.Posts),  // Fetch the post documents
    new GetJsonDocument(),
    WriteFiles((doc,ctx) => "feed.json")
);
```

Hopefully that's enough to get you going. Let me know how you get along.

**Comment by oliverw** [comment]
Hmm that didn't work:

> 3 errors compiling configuration:
> Line 22: CS0246: The type or namespace name 'StringBuilder' could not be found (are you missing a using directive or an assembly reference?)
> Line 22: CS0246: The type or namespace name 'StringBuilder' could not be found (are you missing a using directive or an assembly reference?)
> Line 35: CS0103: The name 'BlogPipelines' does not exist in the current context
> Error while compiling configuration

**Comment by daveaglick** [comment]
Yeah, the code was just from memory - only three errors is pretty good :smile:.

Looks like you might need a `using System.Text;` at the top of the file - that should clear the first two errors. `BlogPipelines` should be automatically in scope if you're using the [blog recipe](https://wyam.io/recipes/blog/overview). Are you calling Wyam with the `-r Blog` flag on the command line?

**Comment by oliverw** [comment]
Nope. I'm using a custom pipeline but nevermind I've figured it out. My only remaining problem is getting the name of the generated output file from the Document's Metadata. In the code below Filename is alway null in the generated Json. Any suggestions?

```
public class PostMetaData
{
    public string Title { get; set; }
    public string Filename { get; set; }
    public DateTime Published { get; set; }
    public string Tags { get; set; }
}

public class GetJsonDocument : IModule
{
    public IEnumerable<IDocument> Execute(IReadOnlyList<IDocument> inputs, IExecutionContext context)
    {
        var result = new List<PostMetaData>();

        foreach(IDocument post in inputs)
        {
            result.Add(new PostMetaData
            {
                Title = post.String("Title"),
                Filename = post.String("Filename"),
                Published = post.Get<DateTime>("Published"),
                Tags = post.String("Tags"),
            });
        }

        var json = Newtonsoft.Json.JsonConvert.SerializeObject(result, Newtonsoft.Json.Formatting.Indented);

        return new[] { context.GetDocument(json) };
    }
}
```

**Comment by oliverw** [comment]
Nevermind. Figured that out as well. 

`Console.WriteLine(string.Join(", ", post.MetadataAs<string>().Keys));`

Proved to be handy. :)

**Comment by daveaglick** [comment]
Awesome! Glad you got everything figured out. Happy to assist if you have any more questions.

**Comment by danjacka** [comment]
Note for anyone referring to this code: following [this change](https://github.com/Wyamio/Wyam/commit/4536fffbf15d40f67f98dadb50f20684722648c9), the last line of oliverw's example should be:

`return new[] { context.GetDocument(context.GetContentStream(json)) };`
