### ISSUE TITLE
Executing Wyam from C# simply deletes the output directory

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#387]
I'm trying to execute Wyam from C# code in LINQPad. I have added both the Wyam.Core and the Wyam.Common Nuget packages.

My code looks like this:

```
var engine = new Wyam.Core.Execution.Engine();
engine.FileSystem.RootPath = @"[my desktop]\wyam\";
engine.Execute();
```

In the "wyam" folder on my desktop, I have the following structure:

```
input
  hey.txt
output
config.wyam
```

The Wyam config file contains this:

```
Pipelines.Add(
    CopyFiles("*.*")
    );
```

I think this is as simple as I can make it. By my reading, execution of this should simply copy `hey.txt` from input to output. I don't see a place to configure where to read the config file from, but it's in the default location, so I assume it picks it up from there.

But it doesn't. What it does is _delete the output directory_. It throws no errors, just deletes the output and exits.

I do not explicitly clean the output directory (remember, I only have the three lines of C#, listed above), but it deletes the directory anyway.

**Comment by daveaglick** [comment]
Looks like there's two different things going on. Here are my guesses (*disclaimer* - I'm not at a computer so I can't verify this just yet).

Cleaning the output path: this is on by default, which makes sense in the majority of use cases since you'll be regenerating whatever it is you're outputting on every build. This behavior can be turned off with `engine.Settings.CleanOutputPath = false;`.

The `CopyFiles` module isn't doing anything because the input path(s) need to be specified. `input` is set as the default input path by the CLI Wyam application, but the engine itself makes no assumptions about input paths. You can set the input path(s) with `engine.FileSystem.InputPaths.Add(...);`.

**Comment by deanebarker** [comment]
First, yes, cleaning the output path was deleting the directory. Doing this...

````
engine.Settings.CleanOutputPath = false;
````

...leaves the output directory alone.

Second, setting the `InputPaths` doesn't seem to do anything new. No file gets copied.

My code now:

```
var engine = new Wyam.Core.Execution.Engine();
engine.Settings.CleanOutputPath = false;
engine.FileSystem.RootPath = @"[my desktop]\wyam\";
engine.FileSystem.InputPaths.Add(@"[my desktop]\wyam\input\");
engine.Execute();
```

What's the trick to get logging or output? The system runs silently, and outputs nothing, so I have no idea if the config file is even being executed or not.

**Comment by deanebarker** [comment]
Tried setting the `OutputPath` too:

```
engine.FileSystem.OutputPath = @"[my desktop]\wyam\output\";
```

**Comment by daveaglick** [comment]
Next step will be to enable some logging. All the logging functionality is exposed through a static [Trace](https://wyam.io/api/wyam.common.tracing/trace/) class. You can add listeners with a call to `Trace.AddListener(TraceListener)`. As with the paths, no assumptions are made about tracing when implementing your own engine. [TraceListener](https://msdn.microsoft.com/en-us/library/system.diagnostics.tracelistener(v=vs.110).aspx) is actually from the .NET Framework, so you can add any of the built-in listeners you like. Easiest to start is probably the [ConsoleTraceListener](https://msdn.microsoft.com/en-us/library/system.diagnostics.consoletracelistener(v=vs.110).aspx).

If you rig up the tracing and paste your output back here, I can help troubleshoot further.

**Comment by deanebarker** [comment]
Okay, progress. This code:

```
Wyam.Common.Tracing.Trace.AddListener(new System.Diagnostics.TextWriterTraceListener(Console.Out));
```

Results in this output:

```
Wyam Information: 0 : Executing 0 pipelines
    Wyam Information: 0 : Executed 0/0 pipelines in 10 ms
```

There _is_ a pipeline in the config file in the root.  It's this:

```
Pipelines.Add(
    CopyFiles("*.*")
    );
```

So it would seem to me that Wyam is not finding the config file. Do I need to explicitly set the path to that somewhere, or should it infer the path from the root path that I set?

**Comment by daveaglick** [comment]
Ah, I see the problem now.

Reading, compiling, and evaluating the configuration file are all outside the scope of the core library. Design boundary was to make the core library as lightweight as possible with minimal dependencies. Operating on the config file requires Roslyn, NuGet, and a bunch of other stuff.

There's two options here:
- Add the package and a reference to [Wyam.Configuration](https://www.nuget.org/packages/Wyam.Configuration/0.15.8-beta). That library has the references to Roslyn, etc. and knows how to compile and evaluate a config file. If you go this route you'll need to instantiate a [Configurator](https://wyam.io/api/wyam.configuration/configurator/) and use it's `.Configure(string)` method to compile and evaluate the config file content.
- Configure the pipelines directly on your `Engine` instance. In this case you'll add code that looks like the following:
```
engine.Pipelines.Add(
    new CopyFiles("*.*")
);
```

Notice that this looks very similar to the config file - that's because the config file is basically just doing this same thing with a little syntactic sugar on top. I would recommend you go this route unless you're intending on swapping out config files. The Roslyn parsing can be expensive and if the pipelines won't change, writing them in code is just as effective.

**Comment by deanebarker** [comment]
Perfect. Makes sense, and it works great.

**Comment by deanebarker** [comment]
As an additional note, I could see writing Wyam scripts in LINQPad like this and just running it out of here. Gives you more natural coding style, syntax help, compiler errors, and it's easier to code pre- and post-build stuff inline. Plus, it's even easier to code and execute than the command line.

**Comment by daveaglick** [comment]
Yep - since the first line of code that's always been a use case I've envisioned. Config files, path conventions, etc. are all just convenience layers. Would love to get more exposure for the "Wyam-powered custom generator application" idea, just haven't had the time to explain it quite as much as I'd like.

**Comment by deanebarker** [comment]
In the `ForEach` module, I'm having some trouble. This is what it looks like in the config file:

```
ForEach(
  Meta("WritePath", $"books/{@doc.String("SourceFileBase")}/index.html")
)
```

I understand that it has to be `new ForEach` and `new Meta` now, but the `doc` reference is a problem. In this syntax, how do I access the document if I don't have the `doc` variable?

**Comment by daveaglick** [comment]
That was actually the most difficult "magic" to get right in the config files. I thought maybe the functional style of C# with delegates would be confusing for non-developers, so I invented this `@doc` syntax to hide it. `@doc` and `@ctx` are shorthand for an implicit `Func<IDocument, IExecutionContext, object>`. Fun fact: this makes the config files a true domain-specific superset of C#.

The translation to actual C# should look like this:
```
new ForEach(
  new Meta("WritePath", (doc, ctx) => $"books/{doc.String("SourceFileBase")}/index.html")
)
```

**Comment by deanebarker** [comment]
I seriously don't know that I will ever execute Wyam from a config ever again...

**Comment by deanebarker** [comment]
I wish I had done this from C# before. I feel like I understand the platform just a little better now. The config system is neat, but it makes it feel like voodoo. This feels so much more natural.
