### ISSUE TITLE
Better user experience for recipes

### ISSUE THREAD

**Issue by stevebeauge** [statiqdev/Statiq#388]
Hello,

I want to evaluate Wyam. But I'm facing a first issue.

I tried to scaffold a new blog, just to see how it works.

I ran `wyam new -r Blog`. It produced some files (`about.md` and `input` folder).

If I run `wyam` (no argument), I was expecting to get a minimal but working blog (one page, one post).

However, I got errors (missing config file).

For completely new beginners like me, it's a bit frustrating not to have this working without further work.

1. Did I missed any step ?
2. Shouldn't scaffolding include a standard and minimal config file?

thx

PS: I have in mind how jekyll works. Simply run `jekyll new` and you have something that works.
PS2: I tested using 0.15.7-beta and 0.15.8-beta

**Comment by daveaglick** [comment]
Wyam is more general than purpose-specific generators like Jekyll and so if you are using a recipe, you need to specify the recipe for each operation (otherwise, it doesn't know if you're building a blog, a documentation site, etc).

The command to run Wyam with the blog recipe after scaffolding it is:
```
wyam -r Blog
```

This is covered at the top of the recipe overview page in our documentation:
https://wyam.io/recipes/blog/overview

Not generating a config file when scaffolding a recipe is a conscious decision. The goal of using a recipe (versus writing your own configuration file) is to eliminate the need for configuration files in the most common scenarios. The only thing you have to do is tell it which recipe you're using.

**Comment by stevebeauge** [comment]
Ok got it.

What was puzzling me is that I have to specify recipe both at scaffolding and building. I was only specifying the recipe with the new command.

That said, shouldn't the recipe be stored when scaffolding? (guessing there's a design choice behind it).

**Comment by daveaglick** [comment]
> That said, shouldn't the recipe be stored when scaffolding?

Yeah, it's something I go back and forth on. I like that scaffolding a new recipe-backed folder structure doesn't require a configuration file. There's a certain satisfaction to it being "configure-less".

That said, your observation is certainly a valid one - perhaps it would be clearer if the scaffolding operation did output a nearly-empty `config.wyam` configuration file with the recipe specified:

```
#recipe Blog
```

I'll leave this issue open for a while and will consider adding that.

**Comment by daveaglick** [comment]
As more folks try out Wyam with a perspective of Jekyl or other static generator which are already purpose-specific, they're hitting problems and confusion with regard to recipes. I.e., the idea of a more general generator that requires some input to know what you're trying to build is new. There's a few ways we can better support the user experience around recipes and eliminate confusion:
- Display an error if you try to scaffold without specifying a recipe
- Add a new `config.wyam` when you scaffold a recipe that specifies the recipe, eliminating the need for the `-r` argument when building the scaffolded site
- Display an error and abort the build (before clearing the output folder) if you build without either a recipe or a config file with pipelines
