### ISSUE TITLE
Syntax Highlighting for config.wyam file

### ISSUE THREAD

**Issue by kamranayub** [statiqdev/Statiq#392]
Is there a syntax highlighting language people are using for Wyam? I know the config is C# but it's a special flavor. I am using VS Code and was wondering what others are doing. A VS code extension wouldn't be a bad thing... having Intellisense and such for the configuration would be pretty stellar.

**Comment by daveaglick** [comment]
I tend to use VS Code for my config files and would love some Intellisense too :smile:. So far we haven't gotten far enough into tooling for Intellisense support though. Part of the problem is that the config file format is actually a special-purpose DSL that is a superset of C#. I do a couple things (like the implicit delegates when you use `@doc`) that wouldn't compile in a standard C# compiler.

There's actually a few tickets regarding tooling already open: #153, #100, and #91. It's something that's on my radar but probably won't happen until after we hit 1.0 sometime later this year.
