### ISSUE TITLE
Styling of nav with dropdown

### ISSUE THREAD

**Issue by n-develop** [statiqdev/Statiq#393]
I am using the standard styling of the blog recipe.
When I create a Dropdown in the navigation, the background and the font are both white inside the dropdown.

![2017-01-19_10h49_35](https://cloud.githubusercontent.com/assets/13137880/22102135/9e2773a6-de36-11e6-93bf-ec07025d90b9.png)

If I scroll down a bit, the font is black in the sticky navigation. 

![2017-01-19_10h49_47](https://cloud.githubusercontent.com/assets/13137880/22102134/9e25cbdc-de36-11e6-94b2-f90ed212f368.png)

This is not a big problem, as I can override the styles, but I think it should be styled correctly out of the box.

**Comment by daveaglick** [comment]
Good catch. The fix would need to be specific to each theme since the blog recipe doesn't explicitly call for multi-level drop-downs. Some themes like Phantom don't even have support for them AFAIK.

So far the themes have mostly had feature parity (there's only two after all). I suspect as additional themes are developed, we'll start to get theme-specific features in much the way Jekyll, Hugo, etc. themes occasionally have special functionality. This really has nothing to do with this specific issue though :smile:.

I'm going to mark this as up for grabs right now. If you get the styles for dropdowns in the CleanBlog theme, send them over and I'll be happy to incorporate (or submit a PR - either is fine).

**Comment by daveaglick** [comment]
Resolved by #409
