### ISSUE TITLE
Why "Wyam --preview" cleans (or zaps) the output directory once it builds it?

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#402]
I am trying to preview my site with a command like below:

```
..\Wyam\Wyam --preview
Wyam version 0.15.8-beta

   ,@@@@@       /@\        @@@@@
   @@@@@@      @@@@@|     $@@@@@h
  $@@@@@     ,@@@@@@@    g@@@@@P
 ]@@@@@M    g@@@@@@@    g@@@@@P
 $@@@@@    @@@@@@@@@   g@@@@@P
j@@@@@   g@@@@@@@@@p ,@@@@@@@
$@@@@@g@@@@@@@@B@@@@@@@@@@@P
`$@@@@@@@@@@@`  ]@@@@@@@@@`
  $@@@@@@@P`     ?$@@@@@P
    `^``           *P*`
**BUILD**
Could not find configuration file at file:///C:/DELTMP/wlab/config.wyam
Installing NuGet packages
    Installing packages to C:/Users/xyz/.nuget/packages (using global packages folder)
    NuGet packages installed in 32 ms
Recursively loading assemblies
    Assemblies loaded in 4 ms
Cataloging classes
    Classes cataloged in 20 ms
Root path:
  file:///C:/DELTMP/wlab
Input path(s):
  theme
  input
Output path:
  output
Cleaning output path output
Cleaned output directory
Executing 0 pipelines
    Executed 0/0 pipelines in 1 ms
Error while running preview server: C:\DELTMP\wlab\output\
Hit any key to exit

```

Wyam cleans the output directory, then tries to run the preview server on the erased directory. The result is the error message shown above.

**Comment by daveaglick** [comment]
The default behavior is to clean the output directory on every build. That makes sense for most use cases since you wouldn't want old files hanging around in the output directory if the build no longer produces them. You can customize this behavior by passing the `--noclean` flag on the command line (documented at https://wyam.io/docs/usage/command-line).

I'll go ahead and resolve this issue since I've hopefully answered your question. Feel free to reply and I can reopen it if needed.

**Comment by daveaglick** [comment]
On closer inspection of your issue, you may also want to check out the command `wyam preview` (instead of `wyam --preview`). The former uses "preview" mode without triggering a build and should not clean the output folder. The latter indicates you want to run a build followed by using the preview server and the output folder should be cleaned first.

The distinction is that not using a `--` prefix indicates the "command" to run while using the `--` prefix without a command implies the `build` command with the `--preview` argument. Hopefully that made sense...

**Comment by AllanXu49** [comment]
Hi David,

So, how `Wyam --preview` would ever work or become useful? It always cleans the output. Therefore, there is nothing to preview.  Perhaps I am missing something?
