### ISSUE TITLE
Is it easy to add nice diagrams we have in Wyam.io to a Wyam blog ? 

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#423]
When I go through the following page built by Wyam Doc Receipt, I see quite nice diagrams created by Wyam: 

https://wyam.io/docs/concepts/modules

I like to have similar diagrams in CleanBlog theme. However, when I include the syntax like below in a Markdown: 

`graph TD I1(I1)-->Module I2(I2)-->Module Module-->O1(I1) Module-->O2(I2)
`

```
<div class="mermaid">
    graph TD
        I1(I1)-->Module
        I2(I2)-->Module
        Module-->O1(I1)
        Module-->O2(I2)
</div>

```

It does not render to a diagram.

Is it easy to add such diagrams to a Wyam blog?

**Comment by LokiMidgard** [comment]
I'll think you need to use following JS library: [mairmaid](https://knsv.github.io/mermaid/#mermaid-cli8).

Never used it myself.

**Comment by daveaglick** [comment]
Yep, @LokiMidgard is right. The diagrams are all provided by [Mermaid](https://knsv.github.io/mermaid) and rendered on the client. The JavaScript code to include this on your pages is baked into the Docs recipe but not the Blog recipe since diagrams probably aren't something the majority of people will use (and there's a code for every JavaScript library you include).

Here's a good article on adding JavaScript libraries to the blog themes: http://www.digitaltapestry.net/posts/wyam-anchors-and-code-copy. It's not specific to Mermaid, but the concepts are the same. You basically need to add the appropriate JavaScript files to the head and then initialize in the body.

**Comment by daveaglick** [comment]
Closing for now, will reopen if there are follow-up questions.
