### ISSUE TITLE
Can I define --output and --log command line switches in the config.wyam ?

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#424]
I like to have a self-sufficient config.wyam file that include the output folder location and the log settings.

I tried below lines in the config.wyam, but it did not work as expected

```
#output ..\output
#log log.txt

```

**Comment by daveaglick** [comment]
The short answer to this is no. The configuration file doesn't have preprocessor directive support for every command line switch.

The long answer is that there's usually a way to get to settings that the CLI changes directly from within the configuration file. In this case, you can change the output folder like this:

```
FileSystem.OutputPath = "..\output";
```

Unfortunately you can't change the log path from the configuration file. That's because the logging trace listener is embedded into the CLI runner. A future enhancement might be to move this to Wyam.Common so it's available from the config file.

**Comment by daveaglick** [comment]
Closing for now, will reopen if there are follow-up questions.

**Comment by AllanXu49** [comment]
Thanks David. I like the long answer approach :)
