### ISSUE TITLE
Errors compiling configuration: The name 'xxx' does not exist in the current context

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#426]
Hello,

I downloaded the latest version of Wyam (0.16.1) and I am trying to execute the following config file:

```
#a **/*

Pipelines.Add("Posts",
	ReadFiles(@"posts\*.md"),
	FrontMatter(Yaml()),
	Markdown(),
	Razor(typeof(RazorPage)),
	WriteFiles(".html")
);
```

To my dismay the follwing error happens:

```
Loading configuration from file:///C:/_dev/mysite-web/config.wyam
Installing NuGet packages
    Installing packages to C:/Users/hecto/.nuget/packages (using global packages folder)
    NuGet packages installed in 27 ms
Recursively loading assemblies
    Assemblies loaded in 200 ms
Cataloging classes
    Classes cataloged in 263 ms
Evaluating configuration script
    4 errors compiling configuration:
Line 5: CS0103: The name 'Yaml' does not exist in the current context
Line 6: CS0103: The name 'Markdown' does not exist in the current context
Line 7: CS0246: The type or namespace name 'RazorPage' could not be found (are you missing a using directive or an assembly reference?)
Line 7: CS0103: The name 'Razor' does not exist in the current context
Error while compiling configuration
```

I too downloaded the source code and I have similar errors building the Examples.

Could you please point me towards the best direction to solve this issue? 
Best Regards,
Hector HERNANDEZ

**Comment by daveaglick** [comment]
Thankfully this is an easy one to resolve.

Every module in Wyam that requires dependencies is packaged as a separate library and NuGet package. That allows users to decide exactly what they need for their particular generation requirements. It also means that the appropriate libraries/packages need to be made available in the config file. The errors you're seeing are because some of these libraries/packages are missing and so the config file can't find the referenced modules.

I'm going to guess you saw the `#a **/*` directive in one of the examples? The example config files are set up out of the box to run under a unit testing framework with the most recent local build of Wyam. The `#a` directive essentially means "load these assemblies". You'll notice that in the example config files there's a comment about commenting out the `#a` directive and instead uncommenting the provided `#n` directives if you want to run the example outside the unit tests. That's what you need to do here. Instead of the `#a` directive, you should have a series of `#n` directives which instruct Wyam to install specific NuGet packages (note that the installation may take a while the first time you run Wyam):

```
#n Wyam.Yaml
#n Wyam.Razor
#n Wyam.Markdown
```

Try that and let me know if it gets you up and running.

**Comment by alfadormx** [comment]
I feel so dumb, I rather read first before asking. 
I appreciate your help and I am sorry for wasting your time.

**Comment by daveaglick** [comment]
Not a problem at all. The issues here serve as a kind of knowledge base for future users, so there are no pointless questions. Who knows when someone else might stumble on this.
