### ISSUE TITLE
Simplify command line arguments parsing

### ISSUE THREAD

**Issue by karthik25** [statiqdev/Statiq#43]
Nice project! May I suggest using Command Line Parser library to simplify argument parsing? https://github.com/gsscoder/commandline

If there was a reason for creating the method to parse the command line args the way its done in Program.cs, pls. ignore!

**Comment by daveaglick** [comment]
Good suggestion, thanks! There's no reason for the current imementation other than it was easy to get up and running when there was only a couple arguments. There's obviously a lot more now, and a good command line parser is going to become important when recipes get implemented (see #1 and #2) because it'll just get even more complex. I'll remember to come back and check it out once I get a chance to re-examine the command line parsing.

**Comment by daveaglick** [comment]
Note to also check out https://github.com/dotnet/corefxlab/pull/280 which is being considered for inclusion in CoreFx

**Comment by daveaglick** [comment]
Also consider how the CLI could be extended by adding and support additional non-generation commands. I.e., a command to scaffold a new site or to generate a deployment script for a specific CI server. When one of these "commands" is used, it would have a different set of flags and would take the system out of generation mode (or should generation just be another "command"). Would also want to make these commands extensible.

**Comment by daveaglick** [comment]
With regard to thoughts on "commands" above - the System.CommandLine library being used already has the concept and support for commands. It can also be easily extended by adding new commands, so that shouldn't be a problem down the road.
