### ISSUE TITLE
Hosted in a virtual directory

### ISSUE THREAD

**Issue by pauldotknopf** [statiqdev/Statiq#438]
Is there a way to host the generated output on a sub directory (http://somewhere.com/build-output/)?

All absolute urls should be prefixed with this directory, automatically.

**Comment by pauldotknopf** [comment]
Found it.

```engine.Settings.LinkRoot```

**Comment by daveaglick** [comment]
Yep, this one's easy :smile: 

Just set the `LinkRoot` setting:

```
Settings[Keys.LinkRoot] = "/project";
```

**Comment by daveaglick** [comment]
Beat me to it!

**Comment by pauldotknopf** [comment]
On another note, when parsing markdown, and the user uses "/images", should we add the link root? It doesn't seem to be doing that.

**Comment by daveaglick** [comment]
Note that you'll want to use the dictionary style of setting it instead of the `.LinkRoot` property (the latter is deprecated and will eventually be removed).

Good question on Markdown links - the link root *will not* automatically be added to links created by the Markdown renderer. I can see cases for going either way on this. On the one hand, I don't know that I want to overwrite what the user puts in their Markdown - maybe they've got a good reason for not using the link root explicitly. On the other hand, it does mean users will have to remember to add the link root to any relative links in their Markdown content as appropriate.

**Comment by pauldotknopf** [comment]
Relative links should be ok, it is the absolute links that the user should worry about.

**Comment by daveaglick** [comment]
Ah, right, of course. Relative links will stay relative to the current location, subfolder or not.
