### ISSUE TITLE
CopyFiles("**/*{!.cshtml,!.md,!.json,}") is copying Rant.h into Output folder

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#464]
Hello,

I copied the following Pipeline from the Blog recipee code:

```
Pipelines.Add("Resources",
	CopyFiles("**/*{!.cshtml,!.md,!.json,}")
);
```

It is my impression it is causing the following output in console:

```
Watching paths(s) file:///C:/Users/hecto/.nuget/packages/Rant.2.0.354/content, theme, input
```

And is responsible for the following files in my Output folder:

```
- Rant License.txt
- Rant.h
```

These issues don't happen when I remove the Pipeline from my config file. I would appreciate any feedback on this matter.

Thanks,
Hector HERNANDEZ

**Comment by daveaglick** [comment]
Pretty sure I know what's going on here - I'll verify and post an update tomorrow.

**Comment by daveaglick** [comment]
So here's what's going on:
- When Wyam uses a NuGet package, either from the `-n`/`--nuget` command line argument or with the `#n`/`#nuget` preprocessor directive, it checks that package for a "content" folder in the package.
- This is true for any package Wyam installs, whether it's directly referenced by the command line argument or preprocessor directive or if it's a dependency of one that is (more on this point in a minute).
- If a "content" folder is found in the NuGet package, it's added to the set of input folders for the build. That's why you're seeing that string of watching paths that includes Rant. You'd see that part whether or not the "Resources" pipeline is removed.
- The "Resources" pipeline (and more specifically, the globbing pattern passed to the `CopyFiles` module) copies any file that doesn't end in ".cshtml", ".md", or ".json" to the output folder *from all input folders*.
- Since the Rant package contains a "content" folder with the two files you mentioned, those get copied to the output folder.

You have a couple options to resolve this:
- Adjust the globbing pattern in the "Resources" pipeline to additionally exclude ".txt" and ".h" files (though that doesn't work if you have legitimate text or header files you want to copy to output).
- Manually delete those files as part of a broader bootstrapping script after Wyam build (I.e., if calling Wyam from Cake, delete those files as a follow-on Cake action).
- Manually delete those files as a pipeline called after the "Resources" pipeline using the `Execute` module and something like `context.FileSystem.GetOutputFile(...).Delete()`.

This behavior is by design. When NuGet packages are used to deliver web resources such as CSS or JS files they are often placed in the "content" folder of the NuGet package. Wyam themes are also distributed this way. It's a fundamental design concept of Wyam to use content folders in NuGet packages this way. We could consider only including content folders from directly referenced packages and not dependencies, but I'm not sure that actually resolves this underlying concern since you could have easily just added Rant directly. One could argue that Rant should have actually put those files in something other than "content" (like "artifacts") but it is what it is.

**Comment by alfadormx** [comment]
Understood; Thank you very much for your time. I will go out with one of the approaches you mentioned to clean up those files.
