### ISSUE TITLE
Wyam command line can't handle paths with trailing backslash.

### ISSUE THREAD

**Issue by wekempf** [statiqdev/Statiq#472]
Discovered using PowerShell tab completion, which includes the trailing backslash.

```wyam.exe -i '.\another input folder\'```

```Wyam version 0.17.1

   ,@@@@@       /@\        @@@@@
   @@@@@@      @@@@@|     $@@@@@h
  $@@@@@     ,@@@@@@@    g@@@@@P
 ]@@@@@M    g@@@@@@@    g@@@@@P
 $@@@@@    @@@@@@@@@   g@@@@@P
j@@@@@   g@@@@@@@@@p ,@@@@@@@
$@@@@@g@@@@@@@@B@@@@@@@@@@@P
`$@@@@@@@@@@@`  ]@@@@@@@@@`
  $@@@@@@@P`     ?$@@@@@P
    `^``           *P*`
Error while parsing command line: Illegal characters in path.
```
Remove the trailing backslash and this works fine.

**Comment by daveaglick** [comment]
I cannot replicate on a normal command line. Was this run from within PS?

**Comment by daveaglick** [comment]
Never mind, finally got the problem to replicate but *only* when called from inside PowerShell. The same command works fine on a normal command shell.

**Comment by daveaglick** [comment]
It also appears dependent on the path having a space. A path without spaces but with a trailing slash works fine.

**Comment by wekempf** [comment]
Wow, complicated. Wonder why it's so particular. Anyway, glad you could repro.

**Comment by daveaglick** [comment]
And now I can replicate on the normal command line, just have to use normal quotes:
```
wyam -i ".\input space\"
```

It looks like in both cases, the .NET CLI arg parser is treating the final `\'` or `\"` as an escape for the quote character:

![2017-03-14_14h47_35](https://cloud.githubusercontent.com/assets/1020407/23917375/77f462de-08c5-11e7-882a-1d9186b89860.png)

Not sure what I can/should do about that. The "invalid character" is actually the trailing quote. I could try to trim invalid path characters from the end of the path, but I'm worried that would miss valid error conditions.

Since the path actually is invalid based on what's given to Wyam from the CLI layer, I'm leaning towards marking this as won't fix. If a trailing slash needs to be used, it should be double-escaped:
```
PS e:\Temp\test> wyam.exe -i '.\input space\\'
```

Thoughts? Pleas for me to reconsider?

**Comment by wekempf** [comment]
I get wanting to do nothing here, but tab completion is an extremely important feature in PowerShell, and this kills the experience. Not sure what to say.

________________________________

**Comment by daveaglick** [comment]
It surprises me that PS adds that extra trailing slash given that it'll definitely be intrepreted as an escape by anything using the standard .NET args parsing.

Let me chew on this - maybe there's a middle ground between always totally ignoring all invalid trailing path characters and keeping the current behavior...

**Comment by daveaglick** [comment]
Did some more research on this. The good news, it's not Wyam. The bad news, it's baked into the framework. Specifically, it's a "feature" of the escape rules in the Windows `CommandLineToArgvW` API. See these links for more details:
- http://stackoverflow.com/questions/9287812/backslash-and-quote-in-command-line-arguments
- https://msdn.microsoft.com/en-us/library/system.environment.getcommandlineargs.aspx
- https://weblogs.asp.net/jongalloway/_5B002E00_NET-Gotcha_5D00_-Commandline-args-ending-in-_5C002200_-are-subject-to-CommandLineToArgvW-whackiness

Specifically:
> "Most apps (including .Net apps) use CommandLineToArgvW to decode their command lines.  It uses crazy escaping rules which explain the behaviour you're seeing."

And it looks like we're not the only ones having this problem, the CoreFx team has even hit it: https://github.com/dotnet/corefx/issues/4720#issuecomment-266596072

So that leaves us with two choices:
- Leave the argument parsing as-is and rely on the standard `CommandLineToArgvW` behavior. That might mean slightly different command line interpretation on other platforms, but maybe that's okay since they may be expected to work a bit differently.
- Implement our own command line parsing algorithm that takes the raw command line string and splits it into arguments.

I'm still leaning towards leaving it as-is, especially since this is no longer our problem, but a design consideration. The escape behavior was added to `CommandLineToArgvW` for a reason, even if it causes some wackiness.

That said, I'll add some very case-specific processing to look for a `"` or`'` at the end of a path and strip it if found. That should get rid of the problems with PowerShell tab completion.

**Comment by daveaglick** [comment]
The special handling is now in develop
