### ISSUE TITLE
Razor RenderBody issues in 0.17.1

### ISSUE THREAD

**Issue by elvogel** [statiqdev/Statiq#478]
I have an index and other pages on my main site. The Index page uses a template file called `_default1.cshtml`. I have this in my `index.cshtml` file:

```
Title: ...
---

@{
    Layout = "_default1";
}
```
My `_default1.cshtml` file looks like this:

```
    @Html.Partial("partials/_head")
    <body>
    @Html.Partial("partials/_menu")
    @RenderBody()
    @Html.Partial("partials/_footer")
    </body>
```

When Wyam builds the site with 0.17.1, The index.html page renders everything except the body contained in `default.cshtml`, in which case the Razor code and HTML show up literally. 

my `config.wyam`:
```
#n Wyam.Markdown
#n Wyam.Razor
#n Wyam.Yaml
#n Wyam.Html 
#a **/*

Pipelines.Add(
    "News",
    ReadFiles("news/**.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Razor(),
    WriteFiles(".html")
);

Pipelines.Add(
    "Blog",
    ReadFiles("blog/**.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Razor(),
    WriteFiles(".html")
);

//now that our news & blog posts have been proc'd, let's index the entries & build out the rest of the site
Pipelines.Add(
    "Content",
    ReadFiles("**/{!_,}*.cshtml","*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Razor(),
    WriteFiles(".html")
);

//copy all of our style resources over
Pipelines.Add(
    "Resources",
	CopyFiles("**/*{!.cshtml,!.md,!.yaml,}")
);

```

**Comment by daveaglick** [comment]
After some quick testing trying to reproduce this, I'm guessing it's because of the `Markdown()` module right before the `Razor()` module in the "Content" pipeline since it loads ".cshtml" files. Specifically, that pipeline takes a ".cshtml" file and sends it through the `Markdown()` module before processing as Razor code. Because `@` has special meaning in Razor and we often run Markdown documents through Razor after rendering the Markdown, the Markdown module assumes all the content it's processing is actually Markdown and any `@` should be HTML escaped so any following Razor modules won't pick it up. All of this is by design (not sure why it was working for you in the past, it probably never should have).

You have two options:

Use `Markdown().EscapeAt(false)` in your "Content" pipeline. This will not escape the `@` characters when the ".cshtml" files are run through the Markdown module, but you will be unable to actually use an `@` inside any real ".md" files (because they won't get escaped and will get treated as Razor code when run through the Razor module later).

Even better, don't run the Razor files through the Markdown module. Since Razor is by definition not Markdown, you want to process *only* the Markdown files with the Markdown module and then send both kinds of files through the Razor module. That would look something like this:

```
Pipelines.Add(
    "Content",
    ReadFiles("**/{!_,}*.cshtml","*.md"),
    FrontMatter(Yaml()),
    If(
        @doc.FilePath(Keys.RelativeFilePath).Extension == ".md",
        Markdown()
    ),
    Razor(),
    WriteFiles(".html")
);
```

Give that a try and let me know if it works for you.

**Comment by elvogel** [comment]
That was exactly what I needed. Thank you!
