### ISSUE TITLE
inheritdoc doesn't work over multiple assemblies

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Statiq#481]
Consider assembly `A` containing a fully documented `IFoo` and assembl `B` containing class `Foo` implementing `IFoo`. Methods on `Foo` using `<inheritdoc\>` doesn't seem to get documented.

Example:
Methods on https://cake-contrib.github.io/Cake.Prca.Website/api/Cake.Prca.PullRequests.Tfs/TfsPullRequestSystem/

**Comment by daveaglick** [comment]
I *think* this would work as long as both assemblies are included in the generation. All of the code and assemblies get lumped into a single Roslyn compilation and the logic for processing `<inheritdoc />` references searches the entire compilation.

This may be some other issue...or perhaps a problem with how the logic is choosing which symbols to check for inherited comments. Let me do some research and get back to you.

**Comment by daveaglick** [comment]
Found the problem here. It's not that the inherited documentation exists in another assembly, it's that the methods in question are both overrides *and* interface implementations. This is a bug in Wyam - it's currently checking for one condition or the other but not both as it should. A fix will be included in the next release.
