### ISSUE TITLE
Inheritance diagram missleading for interfaces from base classes

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Statiq#482]
In the following example `TfsPullRequestSystem` inherits from `PullRequestSystem` which implements `IPullRequestSystem`. The diagram looks like `TfsPullRequestSystem` implements `IPullRequestSystem` directly.

![grafik](https://cloud.githubusercontent.com/assets/2190718/24172039/1281206e-0e87-11e7-9e8d-fd916ac06d14.png)

Site: https://cake-contrib.github.io/Cake.Prca.Website/api/Cake.Prca.PullRequests.Tfs/TfsPullRequestSystem/

**Comment by daveaglick** [comment]
That's actually the way Roslyn sees it. Unlike class inheritance which establishes a clear chain, interface implementation trickles down from any base classes so that the lowest class in the hierarchy always implements all interfaces, either directly or indirectly. You can see this in action really well on the MSDN docs in many of the generic collection classes like `IList<T>` where the class has a huge implementation list even though they may not explicitly declare those interfaces as being implemented.

**Comment by daveaglick** [comment]
Given that this is how Roslyn is designed to work, and technically the base of the hierarchy does implemented all interfaces, direct and inherited, I'm going to close the issue. Feel free to comment if you think we should re-open this and consider changing the behavior.
