### ISSUE TITLE
Parse less files in imported order

### ISSUE THREAD

**Issue by lmberry** [statiqdev/Statiq#513]
We are using wyam to build a docs site and I get warnings when generating the site:

> 17:50:38 warning : extend '.clearfix' has no matches on line 11 in file '../bootstrap/mixins/grid.less':
> 17:50:38  [10]:   padding-right: ceil((@gutter / 2));
> 17:50:38  [11]:   &:extend(.clearfix all);
> 17:50:38        --^
> 17:50:38  [12]: }
> 17:50:38 warning : extend '.close' has no matches on line 87 in file 'mailbox.less':
> 17:50:38  [86]: .mailbox-attachment-close {
> 17:50:38  [87]:   &:extend(.close);
> 17:50:38        --^
> 17:50:38  [88]: }

These are files out-of-the-box from the recipe so its a shame that they generate warnings.

Digging into the code, these are returned by dotless.  I noticed that wyam parses all the less files in the folder in 'random' order, in parrallel.  

This can cause issues with extend and variable dependencies between files.  Perhaps that is what's going on?  Ideally, wyam should parse out the imports from override.less and parse out the files as a browser would, or not generate errors at all and have the verification done in a post-step.

**Comment by daveaglick** [comment]
Unfortunately that's expected behavior right now. The parser we use, DotLess doesn't support some of the syntax the Bootstrap Less files for the theme are using. That's where the warning is coming from. The ordering of parsing isn't a problem because the include statements are all processed in order recursively and cached for the next time that include is used.

I could suppress the warnings, but then you might not see warnings about other more serious issues. I agree having warnings from an out-of-the-box recipe isn't ideal. Issue #419 is already open to address swapping out the Less parser.

Totally unrelated to the warnings, but somewhat related to your comment about ordering, the next release version will adopt a new convention where any Less files prefixed with an underscore will get skipped unless they're included in another Less file. Right now the recipe is explicitly only parsing the top-level Bootstrap files, so the change should let us get away from indicating specific Less files to parse and instead rely on the underscore convention to indicate partial/variable Less includes vs. top-level Less files. See #507 for more details.
