### ISSUE TITLE
Blog theme is case sensitive

### ISSUE THREAD

**Issue by adamclifford** [statiqdev/Statiq#520]
When setting up a simple template for a blog theme, the template index.cshtml file is case sensitive. 

The model is not passed correctly to the page if the file is named Index.cshtml, and the call to ```Model.DocumentList(Keys.PageDocuments)``` returns a null value. This then causes a compilation error.

Should the files that are being looked for ignore case?

**Comment by daveaglick** [comment]
That's a great question - I'm not sure. Until now I've always just deferred to the underlying file system APIs. If it says a file is available, then we use it. If not, we report it missing. Because the file system stuff is all abstracted, we certainly could enforce case-insensitivity if we wanted to. I'd want it to be consistent though, and not user configurable (otherwise I could see it becoming confusing).

**Comment by adamclifford** [comment]
The issue with index.cshtml vs Index.cshtml comes down to the blog recipe explicitly looking for index.cshtml. Then the Pages module picks the Index.cshtml file up.

My suggestion is to use an _Index.cshtml name for the file in the theme, this brings consistency with the rest of the file themes and is automatically excluded by the globbing functionality within the Pages module. 

I know its another change to the way themes are being implemented, however it is a very small change, and it would remove the need to explicitly add index.cshtml to the ignore paths setting in the Pages module.

**Comment by daveaglick** [comment]
This is a great idea. Renaming the archive template from "index.cshtml" to "_Index.cshtml" follows the convention of the other template files and lets us remove "index.cshtml" from the ignore paths so that an alternate index file can be supplied if the user changes the generated index path (see #541).
