### ISSUE TITLE
Don't generate empty namespaces

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Statiq#526]
Currently in the API documentation namespaces are generated even if they didn't contain a public member.
Example: https://cake-contrib.github.io/Cake.Prca.Website/api/Cake.Prca.PullRequests.Tfs.Authentication/

It would be nice to have an option to suppress generation of namespaces if they don't contain a public member.

**Comment by daveaglick** [comment]
Totally agree. I'd go so far as to say this is a bug (though not a show-stopper or anything). It's been on my reader but I haven't taken a closer look yet because this is a little bit of a tough one. Since including a member in the docs is based on a filter that by default only includes public members but can be set to anything, we'll have to evaluate the filter for every member in the namespace to know if the namespace should be included. I might be able to track this as we go and do namespaces last, but haven't looked close enough yet.

**Comment by daveaglick** [comment]
Finally got around to looking at this and it was less than a line of code to fix. Next release will hide namespaces that don't have any visible members.
