### ISSUE TITLE
Context.GetLink returns the original file extension in AdventureTime example 

### ISSUE THREAD

**Issue by hopla** [statiqdev/Statiq#527]
In the AdventureTime example Context.GetLink is used to generate links in the razor views. The resulting links, however have the resulting links have the .md extension of the original files, as opposed to the .html extension of the generated files.

Context.GetLink() should return a link to whatever the relative path of the document is without the extension (if specified) and hiding index files (if specified using Settings[Keys.LinkHideExtensions]).
In this case this does not work, because GetLink only hides the a pre-determined set of extentions. (only htm and html). 
The extensions of .md and e.g. .cshtml files are never hidden. - Maybe it would be better to hide all extensions?

I worked around this, by changing the extensions in the pipeline: 
`Pipelines.Add("Content",
	ReadFiles("**/*.md"),
	FrontMatter(Yaml()),
	Markdown(),
	Excerpt(),
    Concat(
        ReadFiles("index.cshtml")
    ),
	Meta(Keys.RelativeFilePath, Path.ChangeExtension(@doc.String(Keys.RelativeFilePath), ".html")),
	Razor(),
	WriteFiles(".html")
);    
`

However, if I now hide the extensions, they remain missing in the links. (WriteFiles changes the extension of the files written, but not of the links rendered by Razor.)
This works perfectly in the preview-browser, but is an issue with other webservers.

Is this something which should be fixed? If not, would it be possible add a way to retrieve the resulting link?

**Comment by daveaglick** [comment]
That work around was absolutely a good one. It turns out there's actually an easier way to do the same thing. If you call the `WriteFiles()` module with the `.OnlyMetadata()` fluent method, it will change the `RelativeFilePath` as well as all the other file path metadata keys as if you were writing the file without actually writing it. Then a subsiquent call to `WriteFiles()` will read this metadata and act accordingly.

So the final fixed pipeline looks like this:
```
Pipelines.Add("Content",
    ReadFiles("**/*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Excerpt(),
    Concat(
        ReadFiles("index.cshtml")
    ),
    WriteFiles(".html").OnlyMetadata(),  // Sets the .html extension before rendering pages and generating links
    Razor(),
    WriteFiles()
);
```

Thanks for the bug report! The examples are just as important as the executable code to get right. Fix going out now.
