### ISSUE TITLE
Inheriting a custom module doesn't run Execute on the child class

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#537]
I have created a custom module, then inherited it. The inherited class does some Magic Stuff before calling `Execute` on the base.

    public class MyModule : IModule
    {
      public IEnumerable<IDocument> Execute(IReadOnlyList<IDocument> inputs, IExecutionContext context)
      {
        // stuff here...
      }
    }

    public class MyExtendedModule : MyModule
    {
      public new IEnumerable<IDocument> Execute(IReadOnlyList<IDocument> inputs, IExecutionContext context)
      {
        // do some Magic Stuff, then call the base
        return base.Execute(inputs, context);
      }
    }

Even when using the `MyExtendedModule` module, it doesn't run `Execute` on `MyExtendedModule`. I've checked the stacktrace, and it's running it on `MyModule`.  So my "Magic Stuff" never executes.

Why would this be? Does it have something to do with how the `Execute` method is being called deeper in the library?  Does it have someting to do with the `new` keyword in the method declaration?

**Comment by daveaglick** [comment]
Yeah, it's the 'new' keyword. That indicates an entirely different (new) method that happens to have the same name as the base method. Since it's actually a different method, it doesn't implement the interface.

What you really want to do is use 'virtual' on the base method and then 'override' instead of 'new' on the derived method.

**Comment by deanebarker** [comment]
Have I mentioned that I'm not a developer?

**Comment by daveaglick** [comment]
Lol - points for creativity
