### ISSUE TITLE
Critical bug with the engine: option --watch and --preview break

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#54]
This is from the latest merge.

All output  text files will have 0 sizes until the program exit.

http://imgur.com/bme6i8v

`Wyam\wyam.exe --input Siwawi --output Output\Siwawi --noclean --watch --config Siwawi\config.wyam --preview`

**Comment by daveaglick** [comment]
Yikes! That's not good. Interesting that it only applies to the console app (possibly due to the way the engine is created and disposed). All the unit tests passed, so at least the core engine stuff is still okay.

**Comment by daveaglick** [comment]
I've identified the issue - I had removed Document disposal after each run of the engine so that the final documents for each pipeline would remain available until the engine itself was disposed. Unfortunately this means that when we hold on to an engine as both the --watch and --preview options do, the final documents generated by WriteFiles are not immediately disposed and thus hold a file lock and aren't always flushed to disk right away. It should be resolved shortly.
