### ISSUE TITLE
Set a culture for examples so they have the same outputs regardless of local culture

### ISSUE THREAD

**Issue by Daniel15** [statiqdev/Statiq#544]
Some of the example files committed to source control for this project (eg. https://github.com/Wyamio/Wyam/blob/develop/examples/CustomDocumentType/output/posts/a.html) vary based on locale settings. If you clone this repo and run a build on a system that uses a different date format to the person that originally added the file, you end up with a bunch of changes in the working directory:

![](http://ss.dan.cx/2017/07/GitKraken_23-18.17.32.png)

If these are build artifacts, does it even make sense to commit them to source control?

**Comment by daveaglick** [comment]
Having the build artifacts for the examples in source control is intentional. Granted it's a little strange, but pragmatically speaking it lets me quickly identify when a change has messed something up. If I refactor something, run the unit tests (which includes running all the examples), and then notice changes to example output files in the commit diff I know there's something about the refactoring that needs attention.

All that said, it hadn't occurred to me that this might result in difficulty when working on the code from another culture (though it makes perfect sense). Since having the example output in source control has already been helpful on several occasions for me, I don't want to remove those artifacts. What I'll probably do is lock-in the culture for the examples so they build the same artifacts regardless of local culture.

**Comment by Daniel15** [comment]
Sounds good to me.

For what it's worth, I've customized my locale settings. I'm using English (Australia) as the language, but I have the short date format set to yyyy-MM-dd rather than the default dd/MM/yyyy.
