### ISSUE TITLE
Create Rant2 module

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#55]
http://berkin.me/rant/

This will allow people to generate dummy texts to fill up their Work In Progress website.

**Comment by daveaglick** [comment]
I love this idea - good one.

**Comment by dodyg** [comment]
This module can actually be used to generate test input data. The most tedious part in testing wyam.io is putting in the pages or text inside the input folder. 

With this module, we can generate test web pages or blog post  files and generate massive amount of test texts quickly. We can then use the output as input folder.

**Comment by daveaglick** [comment]
In thinking about Rant, it could actually be used pretty easily without a dedicated module:

```
Packages.Install("Rant");
===
using Rant;
public static class RantHelper
{
    public static RantEngine GetEngine()
    {
        var rantEngine = new RantEngine();
        rantEngine.LoadPackage("Rantionary");
        return rantEngine;
    }
}
---
Pipelines.Add(
    Content(RantHelper.GetEngine().Do(@"The <adj> <adj> <noun-animal> <verb.s-walk> over the <adj> <noun-animal>.")),
    WriteFiles((d, c) => "rant.txt")
);
```

While it works, there are a couple problems with the configuration above.

The first is that it requires the Rantionary package to be downloaded separately and placed in the build directory. This actually wasn't all that easy to find. You could skip this step, but then you wouldn't have access to the collection of nouns, verbs, etc. that make up the dictionary and is kind of the whole point.

The other problem is that this only generates one document because the Content module just adds content to whatever inputs it's given and we always start with one initial document. Perhaps what we need to make this approach useful is some document generation modules (I.e., generate N number of documents starting with ID X and store the ID in the new document metadata). Then we could "seed" some number of initial documents and generate the content for each.

While it seems like the ideal resolution to both these things would be to create a Rant module, I do wonder how we would address different use cases with a single module. I can think of at least a few ways someone might want to use procedural text generation:
- To create new content for a document
- To create new metadata for a document
- To replace some placeholder in existing document content
- Inside a template such as Razor to create content in different spots in a document

Of these, the last use case (inside a template) seems like it would be the most common, but is also the one least likely to be addressed by a new module. We could create separate modules for the other use cases: `GenerateContent`, `GenerateMeta`, etc. and maybe that would help.

Another option might be to integrate Rant directly into Wyam.Core and provide a global method for procedural text generation that could be used with any module (I.e., `Content(GenerateText("..."))`) and within templates. This seems better from a usability standpoint and it addresses more of the use cases, but I'll need to think about whether the extra dependency is worth it. On the other hand, this project is all about content generation, so maybe a native procedural text generation capability makes sense.

Not sure where all this leaves us - mainly I just wanted to get it out there for discussion and so I don't forget my train of thought. Let me know if you have any reactions or additional thoughts on any of this.

**Comment by daveaglick** [comment]
After giving this some more thought, I'd really like to keep the extra dependency out of Core - it needs to be as lean as possible to support the greatest number of deployment scenarios.

So that leaves us with modules. I think we can hit nearly all the use cases with three modules:
- `CreateDocuments` This module will have the following constructors:
  - `CreateDocuments(int number)` which will create the specified number of empty documents
  - `CreateDocuments(IEnumerable<string> content)` which will create a document for each string in the enumerable and set it's initial content to the string value
  - `CreateDocuments(IEnumerable<Tuple<string, IEnumerable<KeyValuePair<string, object>>>> contentAndMetadata)` which will allow specifying initial content and metadata for the new documents
- `GenerateContent` which will have the same overloaded constructors as `Content` except the string value will be used for Rant generation
- `GenerateMeta` which will have the same overloaded constructors as `Meta` except the string value will be used for Rant generation

This way, even if you need to generate text for a template, you can generate it in metadata first and then the template can read that.

Still haven't decided how to handle the Rant dictionary. Thinking right now is to embed the default Rantionary as a resource and then provide fluent methods for specifying an alternate.

Don't think this will take very long, and it's something that would be very helpful while testing out new modules, etc. so I'll go ahead and tackle it next.

**Comment by dodyg** [comment]
I am not sure how this related to recipe #1, but I am thinking it will be great if we can do the following auto generated input:
- Generate blog posts from 2002 - 2015 with average 15 posts per month.
- Generate 10 top level pages and 3 of those pages should have 5 children, etc. 
  - Some of these pages shall have images.
- Generate a collection of text and have an index page.
- Generate RSS/OPML/Insert-XML-JSON-Soup 

Now we can run two wyamio consoles. One will generate to an `output` folder which another instance of wyamio will use an `input`. Now we can play insane benchmark game :)
