### ISSUE TITLE
API Search Does Not Display Generic Type Params

### ISSUE THREAD

**Issue by KallynGowdy** [statiqdev/Statiq#552]
![multiplereactivecommand](https://user-images.githubusercontent.com/5075285/29294966-f1eea540-811f-11e7-9baf-735c6b89a79a.PNG)
It looks like the API documentation does not display generic type parameters in the search results box.
This can make finding the correct one a little difficult, as you might imagine.

Is there something we can do to fix this?

**Comment by daveaglick** [comment]
Good catch - this is almost certainly a problem with the template (as opposed to the recipe code). The good news is that means it'll be easy to deploy a temporary patch prior to the next release once I figure out how to fix it. Can you tell if the generic type parameters are actually in the HTML and just getting hidden because they look like tags?

**Comment by KallynGowdy** [comment]
Looks like the type parameters are in the HTML, it just looks like they're not getting escaped.

![linkwithincorrecttags](https://user-images.githubusercontent.com/5075285/29295476-8fbf5326-8122-11e7-9076-5ecc0c8ea2b3.PNG)

The image above is from Chrome Dev Tools. You can see that Chrome interpreted the `TParam` and `TResult` type params as HTML tags.

**Comment by daveaglick** [comment]
Okay good, thanks. That's what I was hoping - should be able to get you a drop-in patch tomorrow.

**Comment by daveaglick** [comment]
Just pushed a fix for this. It'll go out with the next release (want to get in a couple more changes first). Then should be resolved downstream in ReactiveUI on the next publish after the release.
