### ISSUE TITLE
Broken Links (not including the .html)

### ISSUE THREAD

**Issue by mcapodici** [statiqdev/Statiq#556]
To reproduce:

wyam.exe new --recipe Blog
wyam.exe --recipe Blog --theme CleanBlog

Run in IIS Express
Open site in browser

First Post link is "http://localhost:62812/posts/first-post"

Should be "http://localhost:62812/posts/first-post.html"

**Comment by mcapodici** [comment]
I just noticed there is the option

Wyam.exe --preview --watch

It works under this web server. I guess because it is mapping the urls.

However I think this is not extensible to deploy on a simple file hosting.

**Comment by daveaglick** [comment]
That's by design. Since most static hosts hide the `.html` extension to allow static sites to present nice extensionless URLs, that's the default for Wyam generation and the preview server.

You can change this behavior with a [setting](https://wyam.io/docs/usage/settings). Add this to your `config.wyam` file:

```
Settings[Keys.LinkHideExtensions] = false;
```

Keep in mind if you also want to use the preview server with extensions you'll need to pass `--force-ext` on the command line to prevent extensionless URLs from being valid (thus replicating a server like IIS).

**Comment by mcapodici** [comment]
@daveaglick - thanks for the explanation. It might be worth mention this on the quickstart so that it doesn't confuse people.

**Comment by daveaglick** [comment]
Good call, I'll make this behavior more obvious in the getting started docs (https://github.com/Wyamio/Wyam.Web/issues/51).
