### ISSUE TITLE
SkipIfExists option

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#56]
@daveaglick, here's a problem: Image processing takes time and it is very annoying to have to wait for the image processing to be completed (again and again) when some texts get modified. I have to resort to commenting image processing pipeline, which creates a problem when I drop an image and it goes unprocessed.

So I hack up a new fluent method for Image module called `SkipIfExists` which skip the stream processing if the image already exist in destination path

```
Pipelines.Add("Catalog Images",
    ReadFiles("*").Where(x => x.Contains("images\\catalog\\") && new[] { ".jpg", ".jpeg", ".gif", ".png"}.Contains(Path.GetExtension(x))),
    Image().SkipIfExists()
        .SetJpegQuality(100).Resize(400,209).SetSuffix("-thumb")
        .And.SetJpegQuality(70).Resize(400*3, 209*3).SetSuffix("-medium")
    ,
    WriteFiles("*")
);
```

This way if I have 100 images as input, I don't have to reprocess all of them again when I drop an image at the input. This really improve the interactive experience in building a site using `--preview` and `--watch`.

My question is whether there is a better and more general way to solve this issue.

**Comment by dodyg** [comment]
Another idea is to allow the console to accept commands while running  in preview mode so one can quickly flick a shortcut and the console will skip files.

**Comment by dodyg** [comment]
Remove SkipIfExists method and make it a setting at construction instead

``````
Pipelines.Add("Catalog Images",
    ReadFiles("*").Where(x => x.Contains("images\\catalog\\") && new[] { ".jpg", ".jpeg", ".gif", ".png"}.Contains(Path.GetExtension(x))),
    Image(skipIfExists: true)
        .SetJpegQuality(100).Resize(400,209).SetSuffix("-thumb")
        .And.SetJpegQuality(70).Resize(400*3, 209*3).SetSuffix("-medium")
    ,
    WriteFiles("*f")
);```
``````

**Comment by daveaglick** [comment]
This is a really interesting problem - thanks for explaining it so well. I can see this being an issue for other long-running, seldom changed inputs as well. I've been trying to think of a general way to address it.

First, I'm not sure looking at the exisitance of a file in the destination is going to be broadly applicable. While it works fine for cases like images where there is usually a one-to-one input to output, that's not always the case. Even for images, you may output multiple versions for a single input (I.e., different sizes) - which one should be checked? There's also the matter of making sure the final result documents from each pipeline stay correct, even if we skipped some, because other pipelines may use them (for example, to get a total count of images for an index page or something). The skipping behavior also needs to be opt-in - it has some of the same complications as caching, mainly that there's no way to know if one of the modules uses metadata and therefore could produce a different output even given the exact same input. By making skipping opt-in we can leave it up to the user to decide if the optimization is safe.

My thinking right now is that we could rely on `IDocument.Source` to tell us if we've already processed a document, possibly also using a hash code of the content to verify it hasn't changed. If a pipeline has "skip mode" enabled, we would look at the output documents after each module. Any documents with a `Source` that matches one or more from the previous run will be removed from the pipeline until the very end and then the document(s) from the previous run with that same source will be placed in the pipeline results. This would be enabled at the pipeline level and would require doing a full initial execution to get the set of outputs for substitution (so the first run through wouldn't be faster) - after that first one, subsequent runs due to --watch should be lightning fast. Might even be able to add a check that throws an exception if a module in a pipeline in "skip mode" tries to look at metadata - that would provide some protection against inadvertently using skip mode for a pipeline that relies on metadata to change outputs.

Give me a day or two to see what I come up with for this and then we'll see if it meets your more specific use case.

**Comment by daveaglick** [comment]
This should now be implemented - it works by setting a `processDocumentsOnce` flag in an overload of `Pipelines.Add(...)`:

```
Pipelines.Add("Catalog Images", true,
    ReadFiles("*").Where(x => x.Contains("images\\catalog\\") && new[] { ".jpg", ".jpeg", ".gif", ".png"}.Contains(Path.GetExtension(x))),
    Image()
        .SetJpegQuality(100).Resize(400,209).SetSuffix("-thumb")
        .And.SetJpegQuality(70).Resize(400*3, 209*3).SetSuffix("-medium")
    ,
    WriteFiles("*f")
);
```

Let me know how this works for you.

Under the hood, it looks for the first occurrence of a given `IDocument.Source` and then caches all final result documents that have the same source. On subsequent executions, if a document with a previously seen `IDocument.Source` is found _and it has the same content_, that document is removed from the module outputs and therefore won't get passed to the next module. At the end of the pipeline, all the final result documents that have the same source as the removed one are added back to the result set (so later pipelines can still access them in the documents collection if needed).

**Comment by dodyg** [comment]
This solves the problem of not re-executing a certain pipeline when the console is in `--preview` mode.

However there is still one major unaddressed issue. When you start the console, all the pipelines will be re-executed again. Right now I have over 300 images in my input folders and it takes a while to start the console waiting for an already processed images to be reprocessed again.

**Comment by daveaglick** [comment]
Ah, okay - that should be pretty easy to address. I'll add a `IfFilesNotExist` module that has the same semantics as `WriteFiles`. Then just place the new module right after your `ReadFiles` and it will only pass through those documents that don't have a corresponding file on disk. The caution here is that unlike the pipeline flag, this will actually change the final result document collection from your pipeline so it should only be used if you're sure you don't need those documents from other pipelines.

**Comment by dodyg** [comment]
This won't work for module that rename output files such as Image module. Only the module posses the knowledge what's the output file name is going to be.

**Comment by dodyg** [comment]
One way to resolve this problem is to have `IfFilesNotExist` to set a specific metadata flag for modules further down in the pipeline. `Image` module then can check for existence and value for this metadata and act accordingly.

**Comment by daveaglick** [comment]
I just added the `UnwrittenFiles` module discussed above (decided that was a better name than `IfFilesNotExist`).

I've also been thinking about how to address the broader problem - that you can't preemptively skip files and avoid processing them if you don't know their name until after the processing is done. It's a chicken-and-egg problem, and I'm not sure there is a good general solution.

One approach would be to make sure modules don't make any assumptions about files, file names, etc. and stick only to transformations. For example, the `Image` module could be restricted to performing one operation at a time and if you wanted to perform multiple operations, you would have to do them in branches. Then you could set it up like this (BTW - also planning to address the ugly extension check needed for `ReadFiles` soon):

```
Pipelines.Add("Catalog Images",
    ReadFiles("*").Where(x => x.Contains("images\\catalog\\") && new[] { ".jpg", ".jpeg", ".gif", ".png"}.Contains(Path.GetExtension(x))),
    Branch(
        UnwrittenFiles(@doc.String("SourceFileBase") + "-thumb" + @doc.String("SourceFileExt")),
        Image().SetJpegQuality(100).Resize(400,209),
        WriteFiles(@doc.String("SourceFileBase") + "-thumb" + @doc.String("SourceFileExt"))
    ),
    Branch(
        UnwrittenFiles(@doc.String("SourceFileBase") + "-medium" + @doc.String("SourceFileExt")),
        Image().SetJpegQuality(70).Resize(400*3, 209*3),
        WriteFiles(@doc.String("SourceFileBase") + "-medium" + @doc.String("SourceFileExt"))
    )
);
```

That works well for alternate data sources too - for example, consider if the files were coming in from the new `Url` module. There would be no metadata key for `Image.SetSuffix(...)` to manipulate.

**Comment by dodyg** [comment]
Yup the `Branch` alternative could work. The only thing that bothers me about the configuration example is the repetition required `@doc.String("SourceFileBase") + "-thumb" + @doc.String("SourceFileExt")` for `UnwrittenFiles` and `WriteFiles`

**Comment by daveaglick** [comment]
Yeah, that was bugging me too. With the new `ReadFiles.WithExtensions(...)" method I just checked in along with the new interpolated string language feature, the whole thing can be simplified to:

```
Pipelines.Add("Catalog Images",
    ReadFiles("images\\catalog\\*").WithExtensions("jpg", "jpeg", "gif", "png"),
    Branch(
        UnwrittenFiles($"{@doc["SourceFileBase"]}-thumb{@doc["SourceFileExt"]}"),
        Image().SetJpegQuality(100).Resize(400,209),
        WriteFiles($"{@doc["SourceFileBase"]}-thumb{@doc["SourceFileExt"]}")
    ),
    Branch(
        UnwrittenFiles($"{@doc["SourceFileBase"]}-medium{@doc["SourceFileExt"]}"),
        Image().SetJpegQuality(70).Resize(400*3, 209*3),
        WriteFiles($"{@doc["SourceFileBase"]}-medium{@doc["SourceFileExt"]}")
    )
);
```

Or it could be simplified with the addition of a static helper in the declarations section:

```
public static class Helpers
{
    public static string AddSuffix(this IDocument doc, string suffix)
    {
        return $"{doc["SourceFileBase"]}-{suffix}{doc["SourceFileExt"]}";
    }
}
---
Pipelines.Add("Catalog Images",
    ReadFiles("images\\catalog\\*").WithExtensions("jpg", "jpeg", "gif", "png"),
    Branch(
        UnwrittenFiles(@doc.AddSuffix("thumb")),
        Image().SetJpegQuality(100).Resize(400,209),
        WriteFiles(@doc.AddSuffix("thumb"))
    ),
    Branch(
        UnwrittenFiles(@doc.AddSuffix("medium")),
        Image().SetJpegQuality(70).Resize(400*3, 209*3),
        WriteFiles(@doc.AddSuffix("medium"))
    )
);
```

**Comment by daveaglick** [comment]
I'm going to go ahead and close this for now - we can always reopen it or create a new issue later if it turns out the new support for this scenario isn't sufficient.
