### ISSUE TITLE
AnalyzeCSharp: Generic type definitions

### ISSUE THREAD

**Issue by jonasdoerr** [statiqdev/Statiq#564]
I'm currently exploring the `AnalyzeCSharp` module and i'm very impressed of its simplicity and its configurable implementation. I ran into problems with generic type definitions, where i'm not shure if the behavior is intended.

1. The `ImplementingTypes` meta collection is empty for *generic* interface symbols.
2. The document of a *generic* interface symbol contained in the `AllInterfaces` meta collection of another type is not the same document as the document that is rendered for that interface. Therefore, the `WritePath` meta value is not set. Therefore, `Wyam.Docs.Extensions.GetTypeLink` does not render a link for it.

Both issues also apply to generic *classes* and the `DerivedTypes` and `BaseTypes` collections, respectively. I took a quick glance at the code and figured out that the first issue is caused by the second as it is the inverse relation.

**Comment by daveaglick** [comment]
Great finds, thanks for the detailed bug report. I suspect all these issues may be related to #494. It turns out that Roslyn creates entirely new symbols for the definition of a generic type and it's use (open vs. closed). I'm pretty sure that explains both of your observations. If that's the case, then this is already resolved in develop but I'll keep the issue open until I have a chance to verify.

Glad to hear you're finding the module easy to work with. You may be the first person to actually use it outside the docs recipe :smile:

**Comment by daveaglick** [comment]
I can repro this - it's definitely related to #494 but will require that same fix in some other places.

**Comment by jonasdoerr** [comment]
I did not see the other issue before, sorry. Thanks for fixing!
