### ISSUE TITLE
Verify requested version spec for recipes is exact and matches current Wyam version

### ISSUE THREAD

**Issue by RichardJFoster** [statiqdev/Statiq#587]
This problem was observed using Wyam 1.1.0 (via Cake.Wyam v1.1.0 and Cake 0.23.0) to document a new project created in Visual Studio 2017 (specifically Visual Studio Enterprise, version 15.4.1) targeting .NET Framework version 4.7.

The initial problem (captured in the wyam.initial-problem.log file) manifested as an apparently successful build, but for which no API documentation was generated. Turning on verbose logging showed several messages like the following:

`Workspace diagnostic (failure): Msbuild failed when processing the file 'C:\SourceCode\SchedulableTasks_git\Actions.Core\Actions.Core.csproj' with message: The tools version "15.0" is unrecognized. Available tools versions are "12.0", "14.0", "2.0", "3.5", "4.0".  C:\SourceCode\SchedulableTasks_git\Actions.Core\Actions.Core.csproj`

Per discussions about similar problems else where, I tried setting the `VSINSTALLDIR`, `VisualStudioVersion` and `MSBuildToolsVersion` as applicable. This changed the error to the following (see full log file wyam.environment-variables-set.log):

`Exception while processing document Peek.Actions.Models.BooleanParameter in module Razor: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I also tried running Wyam directly from the command line, just in case there was some weirdness as a result of the Cake environment. The output from this run is available in the wyam.command-line.log file below.

[wyam.initial-problem.log](https://github.com/Wyamio/Wyam/files/1440907/wyam.initial-problem.log)
[wyam.environment-variables-set.log](https://github.com/Wyamio/Wyam/files/1440920/wyam.environment-variables-set.log)
[wyam.command-line.log](https://github.com/Wyamio/Wyam/files/1440925/wyam.command-line.log)

**Comment by daveaglick** [comment]
Finally got a chance to spend some time on this. I think I see the problem, I'm just not sure why it's happening yet. You're running Wyam 1.1.0 which *should* be referencing Microsoft.CodeAnalysis... 2.4.0 libraries. However, it's referencing 2.0.0 Roslyn assemblies.

My first guess is the problem has something to do with this:
```
Installing package Wyam.Docs 1.0.0
```

All the Wyam stuff is versioned together so Wyam 1.1.0 should be using Wyam.Docs 1.1.0 and not 1.0.0. That also explains the Roslyn version differences since those references were updated as of 1.1.0. Any idea why it's pulling down an old recipe package? Is the version pinned in the config file?

One other thing I did notice was a reference to `Microsoft.CodeAnalysis.Elfie.0.10.6`. By that I mean Wyam was referencing that package as part of the generation, not that it was referenced by your own project. That package looks like it's been entirely unlisted. Any idea how/why it was being brought into the generation process? Might not have anything to do with this problem - just thought it was odd.

**Comment by RichardJFoster** [comment]
Sorry for the slow response. I was away from the computer holding the code in question.

I can't explain why Wyam.Docs 1.0.0 is getting pulled in. The header section of build.cake looks like this:

```
#tool nuget:?package=GitVersion.CommandLine&version=3.6.5
#tool nuget:?package=NUnit.ConsoleRunner&version=3.7.0
#tool nuget:?package=OpenCover&version=4.6.519
#tool nuget:?package=ReportGenerator&version=3.0.1
#tool nuget:?package=ReportUnit&version=1.2.1
#tool nuget:?package=Wyam&version=1.1.0
#addin nuget:?package=Cake.Wyam&version=1.1.0
```

Just in case the problem is related to how I'm configuring Wyam, here is the complete (but sanitized) wyam.config file too.

```
#recipe Docs

Settings[DocsKeys.Title] = "Internal Documentation";
Settings[DocsKeys.SourceFiles] = null;

// Add any pipeline customizations here

// Overide the API processing to include internal items.
Pipelines["Api"].Clear();

Pipelines["Api"].Add(
	AnalyzeCSharp()
		.WithWritePathPrefix("api")
		.WithSolutions((string)Settings[DocsKeys.SolutionFiles])
		.WhereNamespaces(s => !(s.Contains(".Tests")))
		.WithAssemblySymbols()
		.WithImplicitInheritDoc()
		.WithDocsForImplicitSymbols()
);
```

`Settings[DocKeys.SolutionFiles]` gets set by the cake script to the single solution being analysed.

I did a `git clean -fdx` before running each of the test scenarios, and also confirmed that there are no textual references to Wyam anywhere in the source tree except for the build.cake and config.wyam files.

As far as the weird reference is concerned... The only thing I can think of is that the project being documented uses the Nancy framework. Nancy in turn uses TinyIOC to wire things up at runtime. I don't think it's very likely, but is it possible there is some sort of conflict with any IOC container used by Wyam?

**Comment by daveaglick** [comment]
> is it possible there is some sort of conflict with any IOC container used by Wyam?

Nope, because Wyam doesn't use IoC :smile: I'm not a huge fan of introducing containers until they're really needed.

I would have guessed the `git clean` would get you back to square one, but perhaps the Cake `tools` directory is sticking around for some reason? Both the Cake script header and the Wyam config look fine to me. What does the part of the Cake file look like where you run the Wyam addin?

**Comment by RichardJFoster** [comment]
It looks like this:

```
Task("Publish-Documentation-Internal")
	.Does(() =>
{
	var buildFrom = Directory("Documentation") + Directory("Internal");
	var buildTo = Directory("C:\\WyamOutput\\[ProjectName]");
	
    Wyam(new WyamSettings {
		ConfigurationFile = MakeAbsolute(buildFrom + File("config.wyam")),
		Verbose = true,
		InputPaths =  new[] { 
			MakeAbsolute(buildFrom + Directory("input")) 
			},
        OutputPath = buildTo,
		Settings = new Dictionary<string,object>()
			{
				{ "SolutionFiles", solutionPath },
				{ "LinkRoot", "[ProjectName]" },
			},
		});
});
```

BTW, the git clean removes everything but the packages.config file (specifying Cake 0.23.0) from the tools folder (which is what I would expect as that is a controlled file).

**Comment by daveaglick** [comment]
I took a look at the logs again and I noticed something else that looks interesting. Normally I'd expect to see a bunch of entries from the NuGet client that look like:

```
GET https://api.nuget.org/v3/registration3-gz-semver2/wyam.docs/index.json
```

There should be a ton of these in the verbose log as the NuGet client queries the gallery for packages. I don't see any of those.

Is it possible this system isn't connected to the Internet (or wasn't at the time)? Or perhaps the NuGet gallery isn't configured - what do you see when running `nuget sources` from a command line?

**Comment by daveaglick** [comment]
Something else to try: add `UpdatePackages = true` to your `WyamSettings` in the Cake script. That'll force Wyam to query the NuGet server instead of relying on the local cache.

**Comment by RichardJFoster** [comment]
The system is (or should have been) connected to the internet throughout.

Nuget sources shows 4 registered sources. In order, those are:
1) Nuget.org
2) The company TeamCity build server
3) A local package folder used for testing with locally build pre-release packages
4) Microsoft Visual Studio Offline Packages

**Comment by RichardJFoster** [comment]
Setting UpdatePackages = true appears to have allowed everything to work correctly.

Interestingly, after building successfully, removing the UpdatePackages line, doing a git clean and running again also operates as expected. I guess this means that the local cache was borked in some way. Thanks for the assistance, I guess I can close this case now. :-)

**Comment by daveaglick** [comment]
Excellent! What that flag does is force Wyam to go back to the NuGet servers, even if it finds a matching version locally.

Your problem may indicate a broader issue that the version match isn't specific enough for the recipes. A given version of Wyam should definitely be trying to match the same version of the recipe. I'm going to reopen this issue since it's got all the background, but change the title to remind me to do some further investigation.
