### ISSUE TITLE
Combining Config Files

### ISSUE THREAD

**Issue by jonasdoerr** [statiqdev/Statiq#605]
The idea of combining multiple config files (with one separate input path per file) has arisen when I thought about integrating documentation from several projects into one single webpage. Most of the projects have domain-specific data sources which are pulled by custom `IModule` implementations or Wyam modules with some lines of extra code in the config file. My single config file becomes more and more messy, since I have to reference a lot of custom assemblies.

I had a quick look at the code and it seems that the goal can be achieved with little effort and [embedding the engine](https://wyam.io/docs/usage/embedding) works straightforward. Roughly speaking, I would create one `ScriptManager` instance per script, generate and compile the transformed scripts and finally run them sequentially on a single `Engine`.

@daveaglick Are there any gotchas?

**Comment by daveaglick** [comment]
This is something I’ve been wanting for a while but it just hasn’t risen high enough in the queue yet. Would be happy for you to take a look. See #228 for some thoughts on this - ideally I think it should be implemented as a preprocessor directive like `#include` (or maybe `#load` but since that directive is used by Roslyn scripting it might be best to use a new one).

One gotcha is this:
> Note to self: make sure to pass the context from one evaluation to the next (take a look at how Roslyn scripting does this for the REPL). I.e., if a global variable, class, etc. is defined in an included script make sure it's also available in the including scripts.

I.e., if I include a config file and it defines a custom module, I’d want to be able to use that custom module in the outer config script.

I’m going to close this issue in favor of keeping all the discussion in one place. I’ll copy your comment over to that issue and we can take it from there.
