### ISSUE TITLE
RedirectFrom url with . truncates redirect file name

### ISSUE THREAD

**Issue by wozzo** [statiqdev/Statiq#620]
In an .md file with the following in the metadata at the top of the page
```
RedirectFrom: using-asp.net
```
The output html file is called "using-asp.html" instead of the expected "using-asp.net.html"

**Comment by daveaglick** [comment]
Thanks - this should be a pretty easy fix

**Comment by wozzo** [comment]
Just been taking a look at the code, It looks like this is caused by the following line in Wyam.Core.Modules.Contents.Redirect.cs
```
FilePath outputPath = fromPath.ChangeExtension(".html");
```
And I'm assuming thats for if the redirect included the file extension e.g using-asp.net.php
in which case wouldn't this break the redirect anyway? It would only work if I directed the browser to using-asp.net or using-asp.net.html so can't that line just be removed or am I missing something?
I'll happily PR if you think removing the outputPath variable would work.

**Comment by daveaglick** [comment]
IIRC, the idea here is that you want to redirect from some other page on the same domain to the one where you’ve added the front matter. Since every output page in a static site is `.html` and the redirect takes the form of a JavaScript `document.location` change, the output document that handles the redirect should be a `.html` file.

For example, if your old site had a page at `/foo` but you want that to redirect to `/bar`, you’d add `RedirectFrom: foo` to your `/bar.md` page and that would trigger an output of `/foo.html` with a JS redirect to `/bar.html`, which is the output from your `bar.md` file.

Did that make sense? It’s a page-to-page redirect for if you change the file name or extension of a page. It’s not really for domain redirection - that would require support from the source host.

**Comment by wozzo** [comment]
Yup, that makes sense (I wasn't clear but the examples above were referring to the value you'd enter in the RedirectFrom field), so it sounds like instead of using ChangeExtension, it should be appending .html?

**Comment by daveaglick** [comment]
Yep, that’s my thought. With a check if the extension is already `.html` to leave it and not add an extra one.
