### ISSUE TITLE
Sitemap does not hide index pages

### ISSUE THREAD

**Issue by elvogel** [statiqdev/Statiq#622]
With the following settings configured:
```
Settings[Keys.LinkHideIndexPages] = true;
Settings[Keys.LinkHideExtensions] = true;
```
the "index" shows up. 

Initially, I thought there were two issues, one concerning the file extensions setting, but as it turns out it works -- but if you want to see the results in your Sitemap, you have to run the Disk Cleanup utility before running your wyam build. I think there's some caching going on in the back that's getting in the way.

**Comment by daveaglick** [comment]
Interesting - did you change the settings while Wyam was running in watch mode or was this on a totally fresh build? Wyam is supposed to clean the output directory on every build by default. If there’s anything hanging around in there between builds then something is odd.

**Comment by elvogel** [comment]
I did a combination of both, after trying over and over to get my changes to work. I'm not 100% sure what was going on in the background - and I have two Wyam sites, where it was only happening to the one.  ¯\_(ツ)_/¯

**Comment by daveaglick** [comment]
I'm having trouble replicating this. How are you calling the Sitemap module - with a delegate, a location metadata key, or a `SitemapItem`?

**Comment by daveaglick** [comment]
I think I see what's going on. By default the Sitemap module looks for a metadata key named "SitemapItem" and uses that to generate the sitemap. It's clumsy at best because you have to populate that metadata key yourself. Depending on how it's populated, the use of the settings may not be applied - those settings only have an impact when links are generated from the document using `IExecutionContext.GetLink()`.

I'll fix this _and_ make the Sitemap module more usable by adding a condition that if the "SitemapItem" metadata key doesn't exist or contain the right type of information, we'll get the sitemap link directly from the document using the `IExecutionContext.GetLink()` method. That should both remove the need to define a "SitemapItem" metadata key in most cases and ensure that in the default case the link correctly takes the settings into account.
