### ISSUE TITLE
Endless recursion in Replace module while using regexp

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#624]
Working with Replace module and its regexp based callback, came across a potential recursion issue.

Here is a config which aims to replace all `<a href=''></a>` in the documents:
```cs
public static WyamHelper {
    public static object Me(System.Text.RegularExpressions.Match match) {
        return String.Format("Hey, match value was: {0}", match.Value);
    }
}

Pipelines.Add("Markdown",
    ReadFiles("**/*.md"),
    FrontMatter(Yaml()),
    Markdown().UseExtensions(),
    Replace("<pre>", "<pre class=\"prettyprint\">"),
    Replace(@"(<a href=""_samples.*><\/a>)", WyamHelper.Me),
    Razor(),
    WriteFiles(".html")
);
```
That would result in endless loop. "Me" handler returns a new string containing the same matched value. Best guess is that Wyam creates an endless loop in the following line:
https://github.com/Wyamio/Wyam/blob/38ce1a8ca1a519bcaa3e9e612faf92e02569656d/src/core/Wyam.Core/Modules/Contents/Replace.cs#L120

The following change goes well
```cs
public static object Me(System.Text.RegularExpressions.Match match) {
        return String.Format("Hey, match value were:{0}", match.Value.Split(new []{ "href"}, StringSplitOptions.None )[1]);
    }
```

Totally understand that this is a rather stupid edge case but better leave it here for awareness. Spent some time before figuring out that issue was on my side :) 
Maybe, Wyam would be able to run provided matcher again to see if the number of matches in newly created document remained the same (so that the replacement didn't happen properly) and put a proper warning?

**Comment by daveaglick** [comment]
Very interesting. You're correct - it's the combination of putting the match check in a while loop while performing each subsequent match on the _full_ newly replaced content. There's an assumption that the new content won't match the regular expression and therefore the next match in the loop will be further down the document. The the replacement does still match, boom, we get the recursion. This should definitely be fixed.

One option would be to always perform the next match on a substring of the input document starting from where the previous match ended. That assumes matches are found sequentially (which I think is accurate but will need to check).

Another option would be to cache the match substitutions until all matches are found and then perform the replacements. That might be a little trickier because we'll need to do some mapping of the pre-replaced insertion point to the current insertion point based on previous matches. It could also get really ugly if we end up with two matches that overlap (which is probably why I do the incremental replacement right now).

**Comment by daveaglick** [comment]
It turns out this was easier to fix than I thought it would be. There's a `Regex.Replace()` overload that takes a delegate with the `Match` and replacement content - _exactly_ what the Replace module was trying to do by hand. Swapping out for that makes the code cleaner and has the added benefit of, you know, actually working.
