### ISSUE TITLE
Simple deployment scenario

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#64]
@daveaglick if someone wants to start a new blog or simple site using wyam, what would be the simplest deployment scenario for this person? Ideally one can just simply add a blog entry .md and an image and the resulting rendering will be uploaded somewhere.

**Comment by dodyg** [comment]
- https://developers.google.com/drive/web/publish-site
- http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html

There must be a simpler way somewhere.

**Comment by daveaglick** [comment]
Great question, and one I've been thinking about a lot recently now that the project is gaining some traction. The on-boarding experience could certainly use improving, especially for simple scenarios. This is a good place to collect my thoughts, so prepare for another of my epic brain dumps :)

The way I see it, there's actually two facets to getting new users up to speed with simple deployment scenarios: generation and hosting. I realize your original question is about the hosting part, but I also want to mention the generation part since the two together form a complete "get up and running quickly" capability. Here are some ideas I've had about improvements...

# Generation
- Provide some sort of pre-canned generation ability. Right now, Wyam will build a site using a simple hard-coded configuration if a custom one isn't provided. I've always had it in the back of my head that this could be a point of extension. In fact, issue #1 is about this exact thing. My current thinking is that "recipes" (I may use the name "themes" since that's more familiar) could be built that include a set configuration, resources, HTML/CSS templates, etc. and prescribe things like folder structure to generate a turn-key site without having to do customization. Some sort of theme directory could be provided on the site.
- A scafolding capability would be nice. This would set up your folder structure and some default documents. This would have to be tied into the theme/recipe system so that the scaffolded content matches.
- The install process could be improved. Maybe an MSI installer (with updating ability). Maybe a choco package. Should probably also provide a download link right on the site instead of linking to the GitHub releases page.
- Some sore of GUI would be cool. This is way off in the future, but I like the idea of providing a GUI to set up your pipelines - it could be represented as a series of blocks that can be dragged into a sequence. The Scratch UI could serve as a model (https://scratch.mit.edu/).

# Hosting
- Low hanging fruit here is to create some modules that automatically upload to specific hosts like Google Drive (using the APIs you linked), S3, Azure, or even FTP (#48) on every successful site build. Or perhaps this should be a flag on the command line (I.e., `--publish`). That (using the command line) also starts to get to the concept of passing information from the command line to the rest of the system (see #11 and #2). Or maybe these aren't really modules at all, but some sort of new post-processing interface. This also doesn't address the initial setup though, and I'm not sure there's a way around that. Every host is going to have at least a little groundwork that has to be done to prepare it for hosting.
- I've also toyed with the idea of making some sort of web-based service for building and publishing Wyam sites. This would be similar to what you can do with CI tools like AppVeyor, but already set up for Wyam.  You'd put your site in GitHub and register a commit hook and when the service receives the hook, it downloads the source, builds the site, and then uploads it to one of a number of different hosts.
- I've also been talking with the folks at https://www.netlify.com/ about getting Wyam on their system for automatic builds and hosting once Wyam gets a little more mature. This will be super cool once it gets off the ground.

**Comment by LokiMidgard** [comment]
I currently working on a deployment [script](https://github.com/LokiMidgard/nota/blob/master/deploy.cmd) for Azure that builds Wyam and then the website. similar to the way the Wyam site is build. It is working but need to be tweaked a little more. Like deleting the source files after Wyam was build.

This allows deployment with just one push (to the website directly or a service like git-hub).

Maybe we could provide for different services default deployment scripts like [appveyor.yml](https://github.com/Wyamio/Wyam.Web/blob/develop/appveyor.yml) file for the Wyam website. something like `--deploymentScript appveyor` and it creates all necessary files.

**Comment by daveaglick** [comment]
Excellent - modules that automate this would be great. I've also a sample AppVeyor script at http://wyam.io/knowledgebase/continuous-integration, but making deployment somehow better integrated would be great. I also like your idea of making the deployment script come out during the generation process as just another output file.

**Comment by LokiMidgard** [comment]
I'm not sure if it will work with a module. At least not for the workflow which Azure suggests.

Normally I don't have the output in my repo but the source files. So the deployment script is missing. Without the script the build will not be triggered and the script will never be build as the rest of the site.

**Comment by daveaglick** [comment]
Gotcha - so the idea would be to build a little scaffolding support into the app to generate a starter deployment script _instead_ of running the pipelines?

**Comment by LokiMidgard** [comment]
Something like this. I had the idea after I made the script for my website.
For Azure there is a npm module that makes exactly this for different frameworks you want to deploy.

`npm install azure-cli -g`

`azure site deploymentscript --node`

I found it very convenient. One statement in PowerShell and your Project is configured for continues integration. The next commit will trigger the build and your site is online.
I hope something like this also works for other services. If the user wants to publish to a service he just say `wyam --deplploymentScript [webservice of your choose]' and your build chain is ready on the server.

**Comment by avishnyakov** [comment]
Netlify looks like a good alternative to github pages but requires a nice CI/CD story.
Guess fully automated scenarios is one of the biggest stories around Wyam. 

All that leads to either have a bunch of builtin publishing modules or some kind of known 3rd part scripts. The last option might be a better one due to flexibility and full control around the publishing process.

**Comment by FMastro** [comment]
I'd love to host this on Azure. But seems daunting. It would be great if you utilized http://deploy.azure.com and made a deploy to azure button on this github site. Just like ghost blog does on theirs.

**Comment by LokiMidgard** [comment]
I'm not sure if this Button works for this Project like it works for ghost blog. When I get it correct ghost blog is some kind of cms and you install this cms using the button. After that you create your content using the websites ui. On the other hand wyam uses some source files to generate a static website. You would need to have your content in the place where you press the deploy button.

Maybe this could work for some kind of sample Project that someone can clone edit the content and then use the button of his (cloned) repo to deploy his content to Azure.

Or maybe I just misunderstand what this button does :)

**Comment by daveaglick** [comment]
Cake has been working very well as a deployment orchestration method and the details are now documented on the Wyam site along with other deployment approaches. In addition, since this issue was opened I've taken a position that deployment is out of scope for Wyam directly.

I think this becomes a documentation and examples question from here on and we can open new more specific issues for this as needed.
