### ISSUE TITLE
Using dotnet cli to build/deploy

### ISSUE THREAD

**Issue by pauldotknopf** [statiqdev/Statiq#643]
This is the first step to getting .NET Core support.

It can build full framework as well.

**Comment by daveaglick** [comment]
Using the `dotnet` build command to trigger builds using the SDK MSBuild targets is great, but I'd like to continue using Cake to orchestrate everything. Cake has a different set of aliases for .NET Core, so hopefully those should get the job done: https://cakebuild.net/dsl/dotnetcore/

**Comment by daveaglick** [comment]
Of course, being able to do a quick build without Cake as `dotnet build` would be a nice added benefit.

**Comment by pauldotknopf** [comment]
I don't think Cake supports .NET Core. That prevents us from using the docker sdk images from microsoft to do the building (in Travis CI).

**Comment by daveaglick** [comment]
Ah, gotcha - you're thinking the .NET Core _runtime_ (as opposed to the .NET Core SDK on top of .NET Framework). The very latest version of Cake does support .NET Core 2 (https://cakebuild.net/blog/2018/02/cake-v0.26.0-released) - what I don't know is what needs to change to shift the Cake build script to the new version and the .NET Core runtime. I suspect the Cake bootstrapper will have to change some.

If you just want to address building with the .NET CLI, that would still be helpful - I can figure out the Cake stuff once the build works from the CLI. Otherwise, getting it working with the new Cake stuff on .NET Core would be super-cool.

**Comment by pauldotknopf** [comment]
> Ah, gotcha

I was talking about both, but yeah. First step, *use* the cli.

This is going to be a big task, we probably need to do this in digestible stages.

- [ ] Remove scripty.
- [ ] Update ```build.cake``` to use ```dotnet``` cli.
- [ ] Ensure that builds (NuGet packages) still work/deploy in AppVeyor. You will likely need to test this.
- [ ] Slowly start switching core libraries to target .NET Standard.

**Comment by daveaglick** [comment]
Agree this will need to be incremental. One note: I do all the publishing to the NuGet Gallery and produce the official releases from my local system. AppVeyor only publishes prerelease packages to MyGet. Not sure that makes any difference, but something to keep in mind.

**Comment by daveaglick** [comment]
Closing as `dotnet build` now works and Cake can trigger the `dotnet` CLI commands as needed. Thanks for the help getting this going.
