### ISSUE TITLE
Scripty, .NET Core?

### ISSUE THREAD

**Issue by pauldotknopf** [statiqdev/Statiq#644]
I've been looking at the code base for converting things to .NET Core, and there are some build-level tasks that aren't compatible.

Scripty? How much is it being used? Can it support .NET Core? If not, can we remove it from Wyam?

**Comment by daveaglick** [comment]
The only use right now is to automatically populate the known recipes and themes (`KnownExtensionsGenerated.cs` and `KnownThemeGenerated.cs`). We could temporarily remove it and hard code those files until Scripty is compatible with .NET Core. I'd be fine with that. I've been very slowly doing a Scripty rewrite to support .NET Core and the new project system, but I don't want that work to hold this up since it's still a little ways off. I can always add it back in later once it's ready.

**Comment by daveaglick** [comment]
Closing since Scripty is no longer used (for now).
