### ISSUE TITLE
[Question] Blog recipe, putting posts in the root

### ISSUE THREAD

**Issue by hoetz** [statiqdev/Statiq#675]
Since I am migrating from Ghost, URLs of my posts are i.e. www.mydomain.com/this-is-a-post

Settings[BlogKeys.PostsPath] = ""; 
or
Settings[BlogKeys.PostsPath] = "/";

did not work and caused an exception. I've had no luck with IIS url rewrite either, probably a problem with the existing .html rule. If anyone could give me hint I'd really appreciate it.

**Comment by daveaglick** [comment]
That’s definitely doable - worst case we can customize the pipeline. I’m out, but let me get back to you later today or tomorrow with some tips.

**Comment by hoetz** [comment]
There's no hurry, thanks!

**Comment by hoetz** [comment]
~~I think I can solve this with the RedirectFrom MetaData key. Seems to do the trick!~~
Ok did not work :(

**Comment by daveaglick** [comment]
There's basically three ways you can do this:

One approach is to use `RedirectFrom` to place your actual posts in the location Wyam would normally place them and then generate a Netlify and/or empty pages with META-REFRESH tags to redirect from the old location to the new one. This is probably preferred unless you really need the posts themselves to the at the old location. What wasn't working for you? Were the placeholder pages being generated in the output (front matter like `RedirectFrom: this-is-a-post` should result in a `./this-is-a-post.html` file)?

Another approach is to tell Wyam to actually output the posts themselves to a new location. You were on the right track with `BlogKeys.PostsPath`, but that also changes where the posts are read from. You probably don't want to put all your post Markdown files directly in the root. The exception you were getting was also a bug with certain kinds of root-ish paths with the blog recipe (nice find).

Finally, we can fully customize the behavior by replacing the pipeline or individual module that reads in the posts (it gets set here and not when the posts are written because other pages like archives need to know where the post pages will eventually be output). This gives you total control to do whatever you want. For example:

```
Pipelines["BlogPosts"].Replace("RelativeFilePath",
    // Set the RelativeFilePath metadata which other modules use
    // to figure out where this post will eventually be output
    // In this case, just the file name (so it's at the root) with an .html extension
    new Meta(Keys.RelativeFilePath, (doc, ctx) =>
        doc.FilePath(Keys.SourceFileName).FileName.ChangeExtension("html")));
```

**Comment by hoetz** [comment]
Thank you for the explanation. I think I will go with the 3rd option!
