### ISSUE TITLE
Download/Fetch module

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#68]
All the XML based module will need remote resource download functionality. It is better to create a separate module for it and pass the data through the pipelines instead of implementing the features in the modules themselves.

Possible scenarios:

**Direct save to disk**

```
Pipelines.Add("RSS",
          Download("http://scripting.com/rss.xml"),
          WriteFiles("*")
);
```

**Comment by daveaglick** [comment]
Absolutely. All the modules should have a single responsibility. A module that transforms content should never be responsible for fetching the content to transform. That helps keep the system flexible in case you need to swap sources, make changes, etc.

This one shouldn't be hard to add - essentially just wraps `WebClient`.

**Comment by dodyg** [comment]
OK. Let me work on this.

**Comment by daveaglick** [comment]
Sure thing - just let me know if you need assistance or want to hand it off.

One thought I did have was that results should probably be heavily cached since they may take a while (using the universal `IExecutionContext.ExecutionCache`). Might even provide a `.CacheResponse(bool)` fluent method to control if caching is used or if the resource is fetched each time.

**Comment by dodyg** [comment]
Right now it has `Uris` and `CacheResponse` fluent methods. 

Metadata `SourceUri` contains the URI of the downloaded resource.
Metadata `SourceHeaders` contains a dictionary of strings of the resulting http GET request.

https://github.com/dodyg/Wyam/commit/d9fcd27f23377c7aa8d44ec4a4fa942082b5bd1d

Next is to write a test suite for this module.

**Comment by daveaglick** [comment]
Looking really good. I especially like the idea of taking multiple URIs and then fetching them all asynchronously.

Only suggestion at this point is to use the `IDocument.Clone(...)` overload that takes a source string as the first argument, passing the URI as the source. The document source was something I added recently to make error messages clearer and to help with caching in downstream modules. The idea is that every document that is retrieved via some I/O operation should have a unique source.

**Comment by dodyg** [comment]
The first test is passing. Now we are beyond `it compiles` stage. I also learn how to use NSubstitute, which is nice.

https://github.com/dodyg/Wyam/commit/688662e7827aabce71c3b09a1d720b694f6c1956

**Comment by dodyg** [comment]
Implement `UriWithRequestHeader`

This allows you to specify a large range of request header (e.g. Basic Authentication) when making a request to a resource. You can call this fluent method multiple times for batch calls.

https://github.com/dodyg/Wyam/commit/4374ed1df0f4998d10ffe2b6e44644e2e5b18dd1

**Comment by dodyg** [comment]
Alright let's start implementing modules again.

https://github.com/Wyamio/Wyam/pull/75

**Comment by daveaglick** [comment]
Excellent work. Really timely because I was thinking about automatically pulling in some info from GitHub for the project site. With this module I should be able to grab content like the latest RELEASE file (https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE) and then stick it right on the site.
