### ISSUE TITLE
Custom Theme Cannot Find Infobar

### ISSUE THREAD

**Issue by TheBrambleShark** [statiqdev/Statiq#682]
Hello,

Apologies if this is the wrong place for this. I'm creating my own theme, using the built-in Samson theme as a reference to learn how the theming engine works. It's going pretty well so far, save the sidebar and infobar. The sidebar issue I think I have figured out, but the infobar issue is eluding me.

When building my project, I get the following error message:

```
Exception while processing document file:///F:/Projects/LuzFaltex Privacy Website/input/legal/privacy/policy.md in module Razor: The layout page '/Shared/_LuzFaltex.cshtml' cannot find the section 'InfoBar' in the content page '/legal/privacy/policy.html'.
```

This error message is repeated for the small handful of my other pages, followed by a (very) long stack trace that I'll be more than happy to include if needed.

I had hoped that just including the line `@RenderSection("InfoBar", true)` would allow my theme to pull from Samson's store, but that doesn't seem to be the case. I went ahead and imported the entire Samson Shared folder into my project temporarily to see if that resolved the issue, but it did not. Setting that `RenderSection()` declaration to false allows the code to compile, but as expected, it does not display.

I have configured my `config.wyam` file to include the following setting key:
```
Settings[DocsKeys.BaseEditUrl] = "https://code.luzfaltex.com";
```

That site doesn't properly exist yet, but I own the domain and plan to host a GitLab instance on that host, so I dropped that in temporarily. If this is as simple as changing that to a Github address instead with my site's code uploaded to it, that's simple enough to do.

Any help with this would be appreciated. I've gotten along pretty far by myself but working with an unfamiliar platform can only get you so far. Unfortunately, the documentation here is rather slim in regards to making a new theme, though once I figure a few things out here I'll definitely be contributing to that. I plan to make my custom theme public as well, for use with the Docs recipe. It's a dark theme based off of [Slate by Bootswatch](https://bootswatch.com/slate/).

**Comment by daveaglick** [comment]
Glad to see you’re tackling the theme engine! There are plans to make this easier once version 2 is out, but that’s still a little ways off. In the meantime, I won’t have a chance to take a look for the next couple days but I’ll get back to you as soon as I’ve got some OSS time to take a look.

**Comment by daveaglick** [comment]
Sorry it took so long! Finally getting back to Wyam issues.

> When building my project, I get the following error message...

It looks like you're using the `InfoBar` section in pages of your site, but the layout at `/Shared/_LuzFaltex.cshtml` doesn't know about that section. The way Razor works, all upstream layout files need to declare a section or else you see similar errors. I _think_ you probably need to add the following to your `_LuzFaltex.cshtml` file and it'll start working:

```
@section Infobar {	
	@if (IsSectionDefined("Infobar")) {
		RenderSection("Infobar");
	}
	else { 			
		@Html.Partial("_Infobar") 
	} 
}
```

> I had hoped that just including the line `@RenderSection("InfoBar", true)` would allow my theme to pull from Samson's store

That's exactly how it should work. Razor doesn't know the difference between the Samson theme as provided by the NuGet package and your own theme files. Wyam presents a combined view to the Razor engine. Since it didn't work when you had the Samson theme locally, there's definitely something else going on.

> I have configured my `config.wyam` file to include the following setting key...

The `BaseEditUrl` setting is what controls the little "edit" buttons on documentation pages so that users can go to your GitHub page for the site and contribute changes with a single click. It should typically be set to something like "https://github.com/Wyamio/Wyam.Web/tree/master/input/". Also note that it doesn't have anything to do with the site generation other than providing a base for those "edit" links.

**Comment by TheBrambleShark** [comment]
Sorry for the late reply on this!

Adding the suggested code allowed it to work. The section was later renamed to `_editButton.cshtml` so changes have been made to reflect that. However, the edit button now works as expected. It's been relocated to the navbar for the moment but I may move it back into the sidebar once I've had a chance to get that working.

![image](https://user-images.githubusercontent.com/7003081/43987816-d99f0676-9cec-11e8-8744-3fa7de107477.png)

**Comment by daveaglick** [comment]
Awesome, glad you got it working! I actually really like the edit button in the navbar, might borrow that idea for a future theme :).
