### ISSUE TITLE
CMS + Wyam

### ISSUE THREAD

**Issue by rsantosdev** [statiqdev/Statiq#703]
Hi Guys,

First of all congratulations for the amazing job. I've been reading about static site generators and JAMStack latest days. When I searched static site generators for asp.net core came across the project.

I have a very particular user need and would like to ask if that's possible with Wyam, here's the scenario:

I need to build a static company site that is updated once in a while but my whole problem so far is that the blog (posts) update needs to be controlled by a content team, and they don't have git skill to clone the repo and update markdown files.

Are cms supported already? I mean, is it possible to have a content editor on top of the files that I can trigger a site update?

What I came so far is to build the editor with regular asp.net core / razor / javascript and on every update trigger the embedded Wyam package to generate the output folder.

Is that possible? Did anyone try so far? If not I'll start and will be sharing my findings with you guys

**Comment by daveaglick** [comment]
The short answer is yes, Wyam can do this but it’ll take a bit of customization.

The longer answer is that you’re probably looking for something called a _headless CMS_. This is a relatively new class of tool that can either be hosted or installed and used locally. The idea is that a traditional CMS style system is responsible for managing and editing content. However, instead of also being responsible for the rendering and output of the site, a headless CMS stores the content in a database that some other tool (like a static site generator) accesses via an API at generation time.

There are two types of headless CMS. Hosted ones are probably a bit more popular right now and includes services like [Contentful](https://www.contentful.com). On the other hand, there are also a number of local ones like [Netlify CMS](https://www.netlifycms.org/). Which style you choose depends heavily on who’s going to be editing the content, what their capabilities are, and the site regeneration workflow you want you use. Each headless CMS has different options for these, from kicking off a webhook to a CI server that triggers a rebuild to checking in new files to git in order to kick off your own CI process. There’s a whole big list of headless CMS tools at https://headlesscms.org.

Now...let’s look at Wyam. The built-in recipes in Wyam aren’t designed to work with a CMS so you’ll need to use a custom configuration (which sounds more intimidating than it is - the configuration is basically C# code in a script file). The idea is that you’ll use the code-based extensibility mechanisms in Wyam to fetch content (and maybe even site structure) from the CMS via it’s API instead of via Markdown files on disk. You can certainly code that up yourself by using the `Execute` module (or by writing your own module). Alternatively, Contentful also has a module you could use if you wanted to use their headless CMS service (which I would strongly consider - it’s great): https://www.contentful.com/blog/2017/03/07/contentful-loves-wyam/

Hopefully that gives you enough to start with. Your next step is probably to take a look at a more complex Wyam configuration so you get some ideas what’s possible. The most complex one I’ve built is for [Discover .NET](https://discoverdot.net) - that configuration file is at https://github.com/daveaglick/discoverdotnet/blob/master/config.wyam

**Comment by rsantosdev** [comment]
Thank you so much for the heads up @daveaglick.

I'll be posting my progress here for anyone that is interested in the topic.
