### ISSUE TITLE
First time user having some issues

### ISSUE THREAD

**Issue by SilentSin** [statiqdev/Statiq#714]
I've just used Wyam to build my first ever website and I'm loving it so far. I previously tried Doxygen but didn't like the look and it didn't seem nearly as customisable as Wyam.

Along the way I've run into a bunch of issues, some of which seem like bugs while others are likely just things I haven't been able to figure out how to do, so I figured I'd post them all in one go, then I can separate out any actual bugs into separate posts if necessary. I also saw here https://github.com/Wyamio/Wyam/issues/686 that v2.0 is coming and may address some of them as well.

Edit: separated everything into separate issues.

~~* All code within `#if` regions is ignored when generating the API documentation, meaning none of my debugging or editor-only stuff gets included. Presumably there should be a way to specify which symbols to include, but I haven't figured it out.~~
~~* I tried including my actual VS solution and project instead of just the `.cs` source files, but got the error described here: https://github.com/Wyamio/Wyam/issues/708.~~
~~* I managed to get around that error by removing the `<TargetFrameworkVersion>v3.5</TargetFrameworkVersion>` line from the project file, but then it seemed to have no effect on the output that was produced.~~ https://github.com/Wyamio/Wyam/issues/715

~~* The Wyam documentation doesn't seem to explain what linking solutions/projects actually does, so I'm not even sure if I'm looking in the right direction.~~ https://github.com/Wyamio/Wyam/issues/720

~~* The inheritance diagrams are quite nice, but for things with wide inheritance like my [AnimancerState](https://animancer.github.io/api/Animancer/AnimancerState/) (due to its interfaces) the diagram is so small it's barely readable. I tried looking for a way to put the diagram below the list instead of beside it, but couldn't figure it out.~~ https://github.com/Wyamio/Wyam/issues/718

~~* The links in the diagrams don't show the usual mouse cursor when you hover over them and they always open new tabs where nothing else does.~~ https://github.com/Wyamio/Wyam/issues/719

~~* Overrides of events show both the inherited version and the override, such as my [OnEnd](https://animancer.github.io/api/Animancer/ClipState/) event.~~ https://github.com/Wyamio/Wyam/issues/721

~~* Code tags and other formatting don't work in Front Matter page descriptions. Even using a colon gives me a warning about YAML.~~ https://github.com/Wyamio/Wyam/issues/728

~~* `<see>` tags in XML comments don't generate the correct HTML links when inside a `<list>`.~~ https://github.com/Wyamio/Wyam/issues/722

~~* `protected internal` members aren't listed even though they are visible to inheriting types just like regular `protected` members (as well as to everything in the assembly like `internal`).~~
~~* References to a `protected internal` field such as the `_BasePlayable` in the Remarks of my [AnimancerState](https://animancer.github.io/api/Animancer/AnimancerState/) link to the root of the site, though presumably that's only because the member didn't get a page of its own.~~ https://github.com/Wyamio/Wyam/issues/723

~~* In nested documents the Samson theme cuts off some of the text with the foldout arrow when it's expanded:~~ https://github.com/Wyamio/Wyam/issues/724

~~* Is there a way to use markdown instead of `cshtml` for index pages (without losing the table of sub-sections from the `@Html.Partial("_ChildPages")` command)?~~ https://github.com/Wyamio/Wyam/issues/725

~~* I also tried using #a to include the UnityEngine.dll in the hopes that it could maybe do something with my `<see>` tags for things in that assembly, but it seemed to have no effect on the output and the documentation isn't really clear on what it's supposed to do.~~ https://github.com/Wyamio/Wyam/issues/720

**Comment by SilentSin** [comment]
Found another one:

~~* The Archive links in the sidebar of my blog don't work, presumably because they contain spaces: https://animancer.github.io/blog/.~~ https://github.com/Wyamio/Wyam/issues/726

**Comment by daveaglick** [comment]
This is all really excellent feedback, thanks! Sorry it's taken a little while to get to it.

> so I figured I'd post them all in one go, then I can separate out any actual bugs into separate posts if necessary

Please do - I'll often scan the open issues for low-hanging fruit to tackle prior to getting a release out, particularly ones classified as bugs. Having them separated out makes it easier to tackle as time allows.

> I also saw here #686 that v2.0 is coming and may address some of them as well.

Yep - I've unfortunately been in the weeds on a related project for the last couple months trying to make sure that Wyam knows how to build arbitrary MSBuild project files for the docs recipe. That turned out to be surprisingly difficult. Done with that for now though, so focus is shifting back here.

> All code within #if regions is ignored when generating the API documentation, meaning none of my debugging or editor-only stuff gets included.

That's essentially by design. Wyam uses MSBuild and Roslyn to try and get a semantic model of your code that most closely matches what users would see. That means all `#if` directives, conditionals, etc. are processed just like they are during actual compilation (because essentially, it is an actual compilation).

Wyam can read your projects in a couple different ways:
* When loading a project file, it'll behave just like VS or the `dotnet build` CLI. The same directives will apply as if you had compiled on the command line. This is the most reliable way of making sure Wyam's view of your code matches your project. If you're documenting from source files, try pointing Wyam to the project file(s) or solution file instead and see if that helps.
* When loading as a collection of source files, Wyam doesn't know about the project file or any preprocessor definitions so `#if` behavior and the like might not be as expected. One thing we could do is add global settings inside Wyam to set preprocessor directives for the compilation phase. I created #715 to track this.

> The inheritance diagrams are quite nice, but...

Both bits of feedback here are very good - mind creating new issues for them?

> Overrides of events show both the inherited version and the override, such as my OnEnd event.

At first glance that looks like a bug - can you file a new issue for this as well?

>  Code tags and other formatting don't work in Front Matter page descriptions

YAML can be surprisingly complicated. Had you tried a block-style scalar (see https://stackoverflow.com/a/21699210/807064)? If so and it didn't work, please go ahead and open a new issue and I'll take a closer look.

> ...

The other points all look like bugs and are good candidates for new issues as well. Don't worry about opening up too many issues - I'm of the mind that I'd much rather have everything well tracked.

Thanks again! And glad it's working for you despite some of the issues above.

**Comment by daveaglick** [comment]
Thanks a bunch for going through and converting all of these into new issues. That's exactly what I was looking for. I'll try to go through and triage them later today. Some really good stuff in there, both bugs and feature requests.
