### ISSUE TITLE
Wide Inheritance Diagrams are too small to read easily

### ISSUE THREAD

**Issue by SilentSin** [statiqdev/Statiq#718]
Inheritance diagrams for classes with lots of children or parents such as my [AnimancerState](https://animancer.github.io/api/Animancer/AnimancerState/) class get scaled down too small to read (especially on small screens).

I can see several possible solutions:

- Put the diagram below the list instead of beside.
- Put it below only if it passes a certain width.
- Is the list even necessary? Apart from the namespace, everything else is shown in the diagram.

**Comment by daveaglick** [comment]
I've been playing around with the graph layout and placement to see if there's a better way of handling very wide graphs and I just can't come up with anything.

> Put the diagram below the list instead of beside.
> Put it below only if it passes a certain width.

For the graphs where they're too wide to read, this only buys a little extra width and most are still too wide to read after dropping them down.

> Is the list even necessary? Apart from the namespace, everything else is shown in the diagram

True, but since some graphs are going to be too wide to read well regardless, the list provides a cleaner way to see all the relationships and links. Even if all graphs could be readable, I like the list as an alternate presentation. I don't think I want to get rid of it.

I also tried making the graph vertically based instead of horizontal since our depth is likely to grow less than our width. That works to make everything readable, but it results in a very long graph for types with lots of derivatives/implementations. 

My final thought was to keep the diagrams as-is - like you said, most of the information is replicated in the list, so the large graphs can just serve as a quick visual reference and you don't need to really read them. Then I integrated https://github.com/ariutta/svg-pan-zoom to add pan/zoom support in case someone really wants to examine the larger graphs. This seems to strike a good middle ground to me.
