### ISSUE TITLE
Can relative links in markdown files be relative to the specified LinkRoot?

### ISSUE THREAD

**Issue by SilentSin** [statiqdev/Statiq#735]
I've read through [Serving from a subdirectory](https://wyam.io/docs/deployment/serving-from-a-subdirectory) and I can use `Context.GetLink` in my custom `_Navbar.cshtml`, but all my regular links in markdown files are wrong if I set a `LinkRoot`.

Is there a way for markdown files to generate the correct links relative to the specified root?

And if not, would such a feature request be feasible? Maybe links starting with a double slash could be transformed to be relative to the root or something?

**Comment by tbolon** [comment]
I am trying to transform links from relative to absolute in certain cases, which also requires to manipulate the markdown module rendering.

It is supported on markdig through two properties on the HtmlRenderer, see [this test code](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/TestRelativeUrlReplacement.cs) and [this one](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/TestLinkRewriter.cs)

Making this feature available in Wyam would require two changes:
* Upgrade the markdig package to something more recent. Currently, the referenced version is [0.10.6](https://github.com/Wyamio/Wyam/blob/3ec7e77578bffae83fb8da11b9e7a8efd0483900/src/extensions/Wyam.Markdown/Wyam.Markdown.csproj#L15) (which is from early 2017). I don't think it will be a breaking change, since no specific features are exposed.
* Update the markdown module to apply the wyam settings to the markdig renderer

I have created a [branch](https://github.com/tbolon/Wyam/tree/update-markdown) on top of the develop branch ~~with custom methods to allow replacing the default markdig HtmlRenderer with a custom one. This could allow to apply the settings to the HtmlRenderer via a custom LinkRewriter~~.

~~But I think we should simply apply wyam settings to the HtmlRenderer by default, or disable it by default for now, and consider enabling it by default for the next major version~~.

**Comment by tbolon** [comment]
I changed my mind to simply add a new fluent method on the [Markdown module](https://github.com/tbolon/Wyam/blob/update-markdown/src/extensions/Wyam.Markdown/Markdown.cs) to use the LinkRoot setting when set.

As is, for compatibility purposes, this setting is set to false, but you can enable it by using the `PrependLinkRoot()` method.

Perhaps the default value could be inverted in the next major version ? Or not ? I don't know where is the LinkRoot setting used (cshtml I suppose). Perhaps there are cases where the user expects the razor links to use the LinkRoot setting, but the markdown to ignore it and keep the root-relative links unmodified ?

**Comment by daveaglick** [comment]
That’s awesome @tbolon - this new Markdown module fluent method is in your branch? Any chance you want to submit a PR? If not, I’ll yank it out - always like to give folks the merge credit if they want it though :smile:

**Comment by tbolon** [comment]
I submitted the PR #748 rebased against develop. I don't know if the quality is high enough to be merged. Basically I have done two things: updating markdig package (required) then added a new setting to use LinkRoot setting. I did not want to change the default behavior.

**Comment by daveaglick** [comment]
@tbolon I'll take a look, thanks! And leaving the default as-is was correct, modifying links would probably be a pretty big breaking change.

**Comment by daveaglick** [comment]
Merged the PR and added a `MarkdownPrependLinkRoot` setting to the recipes. It'll all ship in 2.1.0.
