### ISSUE TITLE
Please zip releases inside of a folder

### ISSUE THREAD

**Issue by ryanleecode** [statiqdev/Statiq#736]
Please put the contents of releases inside of a folder. Nothing is worse when unziping an archive and having the entire contents spill over a directory.

**Comment by daveaglick** [comment]
Personal thoughts aside (I actually prefer zipped files _not_ to be in a subfolder), it would be a breaking change at this point since people might have tooling that assumes the current archive layout. There's also precedent for a root-level layout - Cake for example ships their archives with the files in the root.
