### ISSUE TITLE
A petition to Wyam developer team: Please help with breaking changes 

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#741]
Firstly I wanted to thank you for such a great static content generator. Having both Razor and Markdown available for blog posts or content development is a big advantage for asp.net developer community. 

Besides many great things, the challenge that I have with Wyam is its frequent breaking changes.  Last time I upgraded to the version 1.5.0, I had to spend a day to figure out the changes that I need to apply to my them to make it working again. It is tedious since I want to focus on what to blog, rather than how to blog. 

I am referring to the type of problem that Dave Glick faced here: https://youtu.be/ylqeogadFyE?t=39m11s

Here are a few breaking changes that I had to fix, that cost me a beautiful weekend:

Broken:  foreach(IDocument doc in Model.DocumentList(Keys.PageDocuments).Take(ForntPagePostCount))
Fixed: foreach(IDocument doc in Documents[BlogKeys.Posts].Take(ForntPagePostCount))

Broken: @if( Model.DocumentList(Keys.PageDocuments).Count()>ForntPagePostCount)
Fixed: @if( Documents[BlogKeys.Posts].Count()>ForntPagePostCount)

Broken: @foreach(IDocument doc in Model.DocumentList(Keys.PageDocuments).Skip(ForntPagePostCount).Take(OlderPostsCount))
Fixed: @foreach(IDocument doc in Documents[BlogKeys.Posts].Skip(ForntPagePostCount).Take(OlderPostsCount))

Broken: index.cshtml 
Fixed1: _index.cshtml ==> Spent so much time on this. The exception was misleading
Fixed2: _Index.cshtml  ==> another two hours,  the letter I is case sensitive :(

... I can keep going, but I hope you get my point

Is there any way for theme developers (like me) to have a better track of breaking changes? 
When I go through the list of release here: https://github.com/Wyamio/Wyam/releases 
I can see [Breaking Change] tags, but comments are very brief. A page with code samples like I showed above would help and save lots of time for theme developers.

I expect release 1.7.0 would break many themes again and I am hoping we get a few code sample of breaking changes rather than burning another weekend to fix the broken themes or blog files.

Finally, I wanted to highlight the fact that a product manager perspective should be different than a developer perspective. Developers care about clean and refactored code; whereas a successful product managers care about the adoption of a product. With such a rate of painful breaking changes, it might be difficult for Waym to climb the ladder here: https://www.staticgen.com/

**Comment by LokiMidgard** [comment]
I know what you mean. I only get every few month time to work on an project of mine. And then you need to figure out what is breaking. 

I currently stuck at version `0.18.4`.
There were some modules removed for .netStandard compability that I need.

My plan is for now wait for version `3.0` when the generation process changes. So I can use a deebugger and it is easier to include own modules without deploying them as nuget package.

**Comment by daveaglick** [comment]
This is fair and honest criticism and I appreciate it. I also understand breaking changes can be really frustrating, and that there have been a lot of them recently. I have a couple thoughts on this primary oriented around being different sources of breaking changes.

# Types of breaks

## Breaks because of dependency updates

You're correct that 1.7.0 has some breaks. In that version, they're of the variety that comes from updating a dependency (in this case ASP.NET Core/Razor from 1.x to 2.x). The only way to avoid those breaks is not to update the dependency (or in some cases add proxies/wrappers/etc., but that creates additional development and maintenance burdens). For example, in 1.7.0 any Razor code that contains `@page` (I.e., where `page` is a variable) will break because it gets interpreted as a Razor Pages directive instead of a variable. This can be fixed by adding parenthesis like `@(page)`, but I only discovered that via my own experimentation and there's probably other breaks I don't know about.

This kind of break is tough - it's a balancing act. I don't want to keep Wyam on older versions of dependencies forever (and sometimes can't, as in this case where I _had_ to update Razor due to assembly conflicts with `Wyam.Hosting` updates). I think the best we can do here is provide better documentation (more on that below).

## Breaks because of API changes

A different type of break is the ones I intentionally make to the Wyam API. That's the variety it looks like you had the most trouble with above. These are also tough, but for different reasons. I don't want anyone spending entire weekends having to react to changes, so that's on me and the project and needs to be addressed (again, more on this below). On the other hand, Wyam is still relatively young and I'm still working through what a static generator in .NET can and should look like (and what _I_ want it to look like - perk of being the maintainer :smile:).

Over time I've made some bad API decisions and I've discovered some better ways of doing things. I tend to lean towards correcting and moving the API forward rather than let API technical debt build up, even if it means publishing regular breaking changes. There's certainly an argument to be made that I'm too lax in this regard, but it is what it is. That said, I understand why this can be painful for users. I'm hopeful that the vNext client story, essentially replacing the scripting engine and `wyam.config` files with normal .NET projects that hold your Wyam code, will result in better discoverability of changes due to Intellisense, built-in documentation, etc. I.e., if something breaks after an update your custom Wyam application will fail to build and you'll get squiggles, etc. where the API has changed at design and compile time.

## Breaks because of tooling

There's also a third category of problems that you noticed from the DevChatter stream which is caused by trying to get all these various versions, dependencies, Wyam libraries, and themes to work together. Everything has to line up _just right_ or else the whole thing crashes and burns. That's one of the other motivations for shifting to project files - I can stop worrying about the NuGet API, binding redirects, etc. and let the .NET project system handle all that. I'm optimistic that this change alone will mostly eliminate this category of problem.

One of the other changes in my vNext strategy is to move away from deploying themes as packages and instead follow the lead of other static generators and just have them be plain old files on disk in a special subfolder. I'm hoping this reduces some confusion and in the process make them easier to read, debug, and modify.

# How to do better?

One thing I probably can't promise is that I'll stop breaking things. I have a pretty clear and strong vision for how I want to see Wyam evolve and that includes making changes, both big and small to get there. That said, some improvements could certainly be made that make these changes easier to react to.

> Is there any way for theme developers (like me) to have a better track of breaking changes?

Knowing that there are several big changes and breaks around the corner as the .NET Core port wraps up and work on the vNext client story begins, I've been considering firing up a blog on the Wyam docs site and writing a blog entry for each release (like the Cake team does). That'll provide some space for more in-depth explanations of changes beyond what I can put in release notes. I can also commit to putting a section in each post with before/after examples for breaking changes.

Hopefully being more explicit about breaks and providing migration instructions for each release will help. I'm open to other suggestions as well (as long as they're not "stop breaking things" :wink:)

> With such a rate of painful breaking changes, it might be difficult for Wyam to climb the ladder

To be honest that's not really a motivation of mine. It used to be, but over time I've come to accept that I need to pursue the vision I have for the tool with my entire effort. That's not to say I don't care about users - I very much do and probably spend more time doing support than actual coding, but I don't want to peg the success of Wyam to it's relative adoption among other generators. It does what it does because that's what I want it to do, and if other people find that valuable, want to help, and like using it, that's awesome.

**Comment by AllanXu49** [comment]
Hi @daveaglick,

Thank you for the quick response. 

Is there any way to keep breaking-change-fixes in separate commits for your blog and themes listed below. 

https://wyam.io/recipes/blog/themes/

A page with a list of commit hashes would help us to track what it takes to fix the breaking changes

**Comment by daveaglick** [comment]
@AllanXu49 That’ll be easier in the near future. Each of the themes are going to move to their own repositories with independent release schedules and release notes. Basically, themes will be moving to a model similar to other static generators and that should improve visibility of changes and breaks.

**Comment by daveaglick** [comment]
I’ve started blogging releases [on the main Wyam site](https://wyam.io/blog) with the intent of writing more details for each release so I’ll go ahead and close out this issue. Thanks for raising your concerns and pushing for improvements in this area. Feel free to open a new issue if you think there’s more we could do here.

**Comment by AllanXu49** [comment]
Thanks @daveaglick . If there is a way for us to look for the a commit with label "fixes version xyz breaking chnages" then we can nail what exactly needs to be changed in out themes.
