### ISSUE TITLE
NullReferenceException when generating BookSite recipe

### ISSUE THREAD

**Issue by gaelian** [statiqdev/Statiq#758]
Hello there,

I've just installed Wyam v2.1.0 as a .NET Core global tool. Ran `wyam new --recipe BookSite` which seemed to go OK, but then when running `wyam --recipe BookSite --theme Velocity` I seem to be getting a NullReferenceException. Output is below:
```
Executing 15 pipelines
    Executing pipeline "Chapters" (1/15) with 5 child module(s)
                Error while executing module Execute
            Error while executing module ModuleCollection
        Error while executing pipeline Chapters
Exception during execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Wyam.Common.Configuration.ConfigExtensions.Invoke[T](ContextConfig config, IExecutionContext context, String error
Details) in C:\Code\Wyam\src\core\Wyam.Common\Configuration\ConfigExtensions.cs:line 34
   at Wyam.Web.Pipelines.Pages.<>c__DisplayClass5_0.<GetModules>b__4(IExecutionContext ctx)
   at Wyam.Core.Modules.Extensibility.Execute.<>c__DisplayClass3_0.<.ctor>b__0(IReadOnlyList`1 inputs, IExecutionContext
 context) in C:\Code\Wyam\src\core\Wyam.Core\Modules\Extensibility\Execute.cs:line 93
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 in
putDocuments) in C:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 144
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in
C:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 189
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 in
putDocuments) in C:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 144
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId) in C:\Code\Wyam\src\core\Wyam.Core\
Execution\ExecutionPipeline.cs:line 85
   at Wyam.Core.Execution.Engine.Execute() in C:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 247
```

I'm not familiar enough with your codebase to easily trace this through. Any ideas?

**Comment by daveaglick** [comment]
Thanks for the report. Offhand it looks like the recipe is trying to use a config value that doesn’t exist. BookSite doesn’t get as much love as it should since it’s more lightly used than the other recipes. That’ll get better soon once they’re all combined into a single recipe. In the meantime this should hopefully be a quick fix - I’ll take a look in the next day or two.

**Comment by gaelian** [comment]
No worries, appreciate the quick reply.

Yeah, I was looking to try and make use of the BookSite as a starting point because I wanted to use Wyam for a more generic "brochure" style site, rather than a blog or documentation site as such, so BookSite looked to me the closest to what I was wanting.

I was reading your [future plans issue](https://github.com/Wyamio/Wyam/issues/668), sounds like `dotnet new celilo-site` would be exactly what I would be hoping for. :grinning:

**Comment by damccull** [comment]
@gaelian I'm having the same issue running on an ubuntu gitlab shared runner. On my windows box it works fine though. What platform are you running it on?

**Comment by damccull** [comment]
@daveaglick The troubleshooting I've done that hasn't worked:

#n Wyam.All -- no good
Switching between different dotnet docker images -- no good
I thought it was a bad reference to the build in theme so I used #theme ./theme to override the nuget package -- no good

I linked this in gitter but I'll link it again here to consolidate information: https://gist.github.com/damccull/9afa14d53d63e5caf352785632ae7d8e

That's my full, verbose, output from the runner.

**Comment by damccull** [comment]
Well, I tried, and succeeded, in attaching a remote debugger to a docker container I own to try to simulate everything as well as I could, but I just get the same output and no breaks in by debugger on the exception.  I suppose I'd have to debug the wyam or booksite source rather than my own project. That's beyond me at the moment. I'll wait for your expertise.

**Comment by gaelian** [comment]
@damccull I'm running Wyam in a Windows 10 VM on MacOS. So I'm surprised `wyam --recipe BookSite --theme Velocity` works on your Windows machine as it doesn't work on my Windows VM.

I did try running `wyam --recipe Blog --theme CleanBlog` as a test and that worked fine for me on my Win 10 VM. So I took that to mean that the problem was application-level and recipe and/or theme specific.

**Comment by damccull** [comment]
Yep, @gaelian, I agree. I am unable to get a trace on the actual issue because I'm not sure how to run the recipe in a debuggable way, but I am starting to believe it's an environment variable, although I'm not sure what I have set on my two computers that a window VM and an ubuntu machine wouldn't have...

**Comment by damccull** [comment]
@gaelian So I was able to run it on my windows PC because I had an old version of Wyam on my PATH and it was using that....so yeah now that I'm upgraded to the right version it's breaking just like yours and my linux box.

**Comment by daveaglick** [comment]
Problem resolved. The trouble started with this commit: https://github.com/Wyamio/Wyam/commit/70294d04f90d9372878bc8224b595d474c2490d8. Specifically, these two properties should have had default implementations like `_ => false` but instead defaulted to `null`:

https://github.com/Wyamio/Wyam/commit/70294d04f90d9372878bc8224b595d474c2490d8#diff-09446b1f5fb0b3ba7a38ac9932ad1d13R48

https://github.com/Wyamio/Wyam/commit/70294d04f90d9372878bc8224b595d474c2490d8#diff-06cdd097172fb66d3843d78a0d26aea7R67

The `NullReferenceException` happens because the common `Wyam.Web` `BlogPosts` and `Pages` pipelines, both of which are used by BookSite, don't set a value for the `PrependLinkRoot` function mentioned above themselves, so the default value (which was `null`) gets used and boom! The bug didn't show up in Docs or Blog recipes because they set that property before calling the common pipelines. I gave the setting a default value to prevent future problems and also added `PrependLinkRoot` support to the BookSite recipe.
