### ISSUE TITLE
Some Razor code no longer working with new version

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#786]
It may be a relatively restricted issue but with the new 2.2.2 version, some razor code is no longer working on my Wyam site.

I have a code sample (a weird one) that is working in 2.1.1 but not in 2.2.2. Using this code in a *cshtml* file (I have replicated the bug with a new docs recipe by putting this file, test.cshtml, in the *docs* folder):
```
Title: t
---

<table>
    <tbody>
        @{
            var p = new List<int>(){1};
            foreach (var t in p.OrderBy(x => x))
            {
                <tr>
                    <td><code>gg</code></td>
                </tr>
            }
        }
    </tbody>				
</table>    
```

The build fails with:
```
       Error RZ1026: Encountered end tag "int" with no matching start tag.  Are your start/end tags properly balanced?
            Error while executing module Razor
```

The error is also in 2.2.0.

**Comment by k94ll13nn3** [comment]
Sorry, found the bug, was missing a `</strong>`.
Was lucky that it was working before.

**Comment by k94ll13nn3** [comment]
Sorry again, got another case that is closer to my first bug. I edited the first post.

**Comment by daveaglick** [comment]
Thanks for the detailed reproduction - I’ll take a look. At first glance I don’t see anything that would obviously be causing a problem - though the versions where it worked and didn’t work would suggest it has to do with the new shortcode parser.

**Comment by daveaglick** [comment]
I can reproduce - debugging now

**Comment by daveaglick** [comment]
This is a really interesting bug. It seems to be triggered by _both_ the `.OrderBy()` clause _and_ the presence of `<code>` blocks. Without other inner tags besides `<code>` it seems to compile fine. Other predicates like `.Select()` also trigger the bug. But no predicate compiles fine. Also, the type of collection doesn't seem to matter.

Here's a more minimal repro:
```
@{
    var p = new int[]{1};
    foreach (var t in p.Select(x => x))
    {
        <code>
        </code>
    }
}
```

**Comment by daveaglick** [comment]
Here's what Razor is seeing:

```
<html><head></head><body>@{
    var p = new int[]{1};
    foreach (var t in p.Select(x =&gt; x))
    {
        <code>
        </code>
    }
}</body></html>
```

So it looks like something is escaping the `>` inside the lambda which is understandably confusing the Razor engine.

**Comment by daveaglick** [comment]
Looks like this is actually related to some of the `AutoLink` changes that were introduced in #766. I suspect that the `AutoLink` module isn't correctly limiting replacements to inside `<code>` blocks (that also explains why we're getting wrapping `<html>` etc. tags).

**Comment by daveaglick** [comment]
Honestly, I'm surprised this ever worked. The problem is that `AutoLink` using AngleSharp to identify the `<code>` elements and then perform replacements within them. But AngleSharp is standards-conforming and so it processes the C# code inside the `@{ ... }` block as if it were a text node, escaping the `=>` text content as `=&gt;` within it's internal DOM (as any standards-compliant HTML parser would). Then when the final version is output from the AngleSharp DOM (only if a `<code>` element was found), the output HTML from the DOM contains the post-escaped version of the lambda.

You managed to catch this behavior with a lambda, but I would envision there are other C# code cases that would also trip up AngleSharp's standards-compliant DOM parsing. It's a wonder this hasn't been a problem in more situations. I'm going to need to think about the best way to handle it... In the meantime you can get around the problem by setting `DocsKeys.AutoLinkTypes` to `false` which will bypass the `AutoLink` module.

One thought I have is that maybe `AutoLink` should be run _after_ `Razor` which will ensure it's just processing pure HTML. I'll need to see what the implications of that change are though.

**Comment by daveaglick** [comment]
> Honestly, I'm surprised this ever worked.

Confirmed that is does indeed work fine in 2.1.2 and breaks in 2.1.3, which surprised me. It confirms that it's probably due to the `AutoLink` changes, but my first look through the code confuses me as to why.

**Comment by daveaglick** [comment]
Okay, I get it now. There's two things going on:
* There's a bug in the new `AutoLink` code that makes it think it needs to perform replacements when it really doesn't. That triggers AngleSharp output to a new document when in the past it would have just output the original document, which is why these cases worked before.
* That said, the deeper underlying problem that this exposes is that if replacements _are_ performed we'll still hit this bug and would have before as well.

**Comment by k94ll13nn3** [comment]
Thanks for the quick fix 👍
