### ISSUE TITLE
AutoLinkDictionaryCreation Module

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#82]
The Module search in the metadata of documents for entry's with specific keys and adding the values as keys to the dictionary that  will be consumed by AutoLink.

Example:
    Document:
        Title: Modules
        Url: /site/Modules/index.html

The Module would then add ("Modules", "/site/Modules/index.html") to the dictionary, assuming that it was configured to search for Title and find the url in Url.

There should also be a conflict resolution strategy, maybe like [Wikipedia](https://en.wikipedia.org/wiki/Game_%28disambiguation%29)

**Comment by LokiMidgard** [comment]
I made a prototype but I don't like the class design. I haven't seen a way to send the dictionary created by the module to the AutoLink module. My prototype gets the dictionary in the constructor and then fills it, but I would prefer if the module could create the directory.

**Comment by dodyg** [comment]
Can you somehow use it with Yaml module (http://wyam.io/modules/yaml) ?

**Comment by LokiMidgard** [comment]
If I see it correctly the Yaml module converts the Document.Content to Metadata. What I thought of was a converter from multiple Metadata to Dictionary that can be consumed by AutoLink.

**Comment by dodyg** [comment]
Right now the mechanism to pass data from one module to another is via http://wyam.io/api/idocument, which are essentially Metadata, Content and GetStream. 

Since I assume Content and GetStream are already been used by `AutoLink` to get the input documents, I think your way forward is through Metadata data mechanism.

**Comment by LokiMidgard** [comment]
So you suggest instead of  

``` C#
IDictionary<string, string> keywordDirectory = new Dictionary<string,string>();
Pipelines.Add("renderOutput",
    Documents("renderInput"),
    Markdown(),
    GenerateLookupTest(keywordDirectory, "Title", "Alias"),
    AutoLink(keywordDirectory)
);
```

something like this.

``` C#
Pipelines.Add("renderOutput",
    Documents("renderInput"),
    Markdown(),
    Meta( "keywordDirectory", new Directory()/*Fill with metadata*/ ),
    AutoLink((@doc, @ctx)=> @doc["keywordDirectory"])
);
```

That's way better then this constructor hack. And if I want to I could use different Dictionary's for each document.

Is there a way to get the Metadata of all Input documents and then create a single dictionary out of it?
Something like Execute, but that's not working on single Documents but all documents at once.

**Comment by daveaglick** [comment]
### Concept

Interesting request. Let me make sure I understand it. Given the following documents and their metadata:

Document A
Color: Red
Shape: Circle

Document B
Color: Blue
Shape: Square

Document C
Color: Green
Shape: Circle

What we want to do is create a dictionary using the values of a specific metadata key as keys in a new dictionary, and values of another metadata key as values in the new dictionary. In other words, we want to take document A, B, and C described above and end up with this dictionary, assuming we use Color as the key and Shape as the value:

Red: Circle
Blue: Square
Green: Circle

### Duplicate Keys Problem

I see a complication. What if, in addition to the documents above, we also have:

Document D
Color: Blue
Shape: Circle

Now we have two documents with a value of Blue for their Color metadata key. That would result in duplicate keys in the constructed dictionary, which isn't allowed. Perhaps the values of the constructed dictionary should actually be a sequence of values for each matching key? In this case, given documents A, B, C, and D, we would end up with the following constructed dictionary:

Red: { Circle }
Blue: { Square, Circle }
Green: { Circle }

### Implementation

The initial use case is to feed the constructed dictionary to the AutoLink module. I.e., if in the examples above, Shape was actually a URL, then we would want to link each textual occurrence of a specific Color value in the AutoLink input documents to the corresponding URL.

I actually think we're already mostly there. First, this type of behavior strikes me more as something that's appropriate for an extension method rather than an actual module because we're trying to get a specific object (the dictionary) as opposed to transforming the input. Then we want to use this object to configure a module.

It turns out there's already an extension method that does something very similar:
https://github.com/Wyamio/Wyam/blob/develop/Wyam.Common/Documents/DocumentCollectionExtensions.cs#L23

The documentation isn't great on `.ToLookup(this IEnumerable<IDocument> documents, string key)` yet, but hopefully that'll get better in the next release when API docs are generated from code comments. In any case, this extension method is designed to look for documents with a specified key and to create an `ILookup` of each value of that key to all documents that contain the key with that value. `ILookup` is a built-in .NET interface in the LINQ namespace and is essentially a dictionary with each key mapping to a sequence of values.

You need this to go one step further though:
`.ToLookup(this IEnumerable<IDocument> documents, string keyMetadataKey, string valueMetadataKey)`

This new extension method would do the same thing, but instead of returning a `ILookup<T, IDocument>`, it would return a `ILookup<T, object>` where the lookup values are all the values for the metadata key `valueMetadataKey`.

An additional generic overload, `.ToLookup<TValue>(this IEnumerable<IDocument> documents, string keyMetadataKey, string valueMetadataKey)` could also be created to perform conversion on the metadata values before adding them to the dictionary, which would make the result even easier to use (no casting of values needed).

These new methods shouldn't be difficult to create - I'll give it a shot later today.

### Usage

Which brings us to how to use these new extension methods. Your pipeline config would look something like this:

```
Pipelines.Add("Content",
  ReadFiles("*.md"),
  FrontMatter(Yaml()),
  Markdown(),
  AutoLink(@ctx.Documents
    .FromPipeline("Content")  // Get documents from our current pipeline
    .ToLookup<string>("Color", "Shape")  // Use our new ToLookup extension
    .ToDictionary(x => x.Key, x => x.First()) // Collapse the ILookup down to a single value per key
  ),
  WriteFiles(".html")
);
```

Note that I'm using the AutoLink constructor that takes a `ContextConfig` with the optional `@ctx` simplification syntax.

Hopefully all this made sense. If not, feel free to ask questions. I'll try to get the new `ToLookup(...)` extensions into the develop branch today - I don't think they'll be hard. Then you should be good to go.

**Comment by LokiMidgard** [comment]
I didn't know I could use FromPipeline(...) to get the Documents in the current pipeline. I always thought I could only use it to get the result of a pipeline after the last Module executed.

Just to get this straight, in your sample FromPipeline() returns the documents that where output by Markdown() Module before AutoLink will get executed?

**Comment by daveaglick** [comment]
Yes indeed! The `IDocumentCollection` you get from `IExecutionContext.Documents` is updated after every module:

``` C#
Pipelines.Add("Foo",
  ModuleA(),
  // IDocumentCollection.FromPipeline("Foo") now contains outputs from ModuleA
  Branch(    
    // IDocumentCollection.FromPipeline("Foo") now contains outputs from ModuleA
    ModuleB()
    // IDocumentCollection.FromPipeline("Foo") now contains outputs from ModuleB
  ),
  // IDocumentCollection.FromPipeline("Foo") now contains outputs from Branch
  // (which are the same as ModuleA because Branch just passes through it's inputs)
  ModuleC()
  // IDocumentCollection.FromPipeline("Foo") now contains outputs from ModuleC
);
```

**Comment by LokiMidgard** [comment]
Just tried it. And it is less confusing than before.

``` C#
     AutoLink(@ctx.Documents
    .FromPipeline("content")  // Get documents from our current pipeline
    .ToLookup<string>("Title")  // Use our new ToLookup extension
    .ToDictionary(x => x.Key, x => (string)x.First()["TargetUrl"]) as IDictionary<string,string> )

```

thanks ;)

**Comment by daveaglick** [comment]
No problem! That's one of the great things about a non-opinionated architecture like this - there's a ton of different ways to accomplish stuff.

**Comment by daveaglick** [comment]
The new extensions are now in the develop branch. I also added some `ToDictionary()` extensions that should make this even easier. With the new extensions, you should now be able to write it like this:

``` C#
AutoLink(@ctx.Documents
    .FromPipeline("content")
    .ToDictionary<string, string>("Title", "TargetUrl")
)
```

**Comment by LokiMidgard** [comment]
cool :+1:
