### ISSUE TITLE
Clueless Coder

### ISSUE THREAD

**Issue by ohlawdie** [statiqdev/Statiq#862]
Hey Wyam team,

I realize you are not the purveyors of Appveyor but I was wondering if someone could help explain what this means in my Appveyor output I'd be obliged.

![image](https://user-images.githubusercontent.com/30779615/63547566-6eb90c80-c4fa-11e9-9d48-43d5fe4d6906.png)

I believe I've configured the access token and the appveyor.yml correctly...probably not. It looks like it's looking for some sort of local relative path as a fallback but this is not where I have my wyam project.

Anyways, thanks!

**Comment by gep13** [comment]
@evanricard can you confirm what version of Wyam you are using?

@daveaglick recently pushed out a new version of Wyam that should have fixed this issue.  See here: https://github.com/Wyamio/Wyam/releases/tag/v2.2.7 for more details.

**Comment by ohlawdie** [comment]
Ah ok I will try that Gary - thank you; I am using v2.2.5

**Comment by ohlawdie** [comment]
Had the chance to run an uninstall and do a dotnet tool install -g Wyam.Tool --version 2.27. Is that the correct command to get going? 

_Unforunately_ the only files that come with a wyam new --recipe Blog in this version of the tool only give me a config.yml and an input directory....I'll inspect the tool more in the morning.
![image](https://user-images.githubusercontent.com/30779615/63561981-e4889c80-c529-11e9-82a9-aabb2be8b439.png)

**Comment by gep13** [comment]
>@evanricard said...
Is that the correct command to get going?

Yes, I believe so.  If you run `wyam --version` do you get 2.2.7 in the output?

>@evanricard said...
wyam new --recipe Blog in this version of the tool only give me a config.yml and an input directory.

now we are into the realm of things I can't really help with, sorry 😢 Hopefully @daveaglick will be able to add more here.

**Comment by ohlawdie** [comment]
Yes, 2.2.7. I have the source code, the zip, and the Nuget package/tool!

**Comment by daveaglick** [comment]
@evanricard The error you were originally seeing seems like it's a known bug that was fixed in 2.2.7. Given that you were able to run `new --recipe Blog` I think the update fixed your original problem.

> the only files that come with a `wyam new --recipe Blog` in this version of the tool only give me a `config.yml` and an `input` directory

That's exactly what you should see! :smile: Wyam places all the files that contribute to the site generation in an `input` folder and all the stuff that it generates (I.e., what should be uploaded to your server) in an `output` directory. Running `wyam -pw` should now produce a simple blog and allow you to preview it. The `input` directory contains a sample blog post and you can add more posts and/or pages in that folder.

**Comment by ohlawdie** [comment]
Oh yes that worked! Thank you Dave 👍  

Looking forward to working through the rest of your code :)

**Comment by daveaglick** [comment]
Awesome!
