### ISSUE TITLE
Exclude Certain Files from Input Folder

### ISSUE THREAD

**Issue by hawkerm** [statiqdev/Statiq#871]
I have some template helpers I put in an `_include` directory.  Put wyam copies this over to the output and tries to generate the template as another file as well.

Did I miss an easy way to configure ignoring this directory as input?  Thanks!

**Comment by daveaglick** [comment]
Wow, sorry for the _late_ reply. In answer to your question, unfortunately not - the best option for ignoring files is to place them alongside the input directly and refer to them with a relative path (I.e., "../_include/helpers.cshtml". Razor should be just fine with that since it doesn't actually know about the Wyam virtual file system and just uses the normal folder structure.

FWIW, this is totally changed in Statiq Web - it has (or at least will have shortly) the ability to specify globbing patterns to include/exclude for the various pipelines.

**Comment by daveaglick** [comment]
I'm slowly working on cleaning up some of the issues that came over from Wyam. Since this one is pretty old I'm going to go ahead and close it. Please don't hesitate to comment or open a new one if it turns out this issue is still relevant in Statiq.

**Comment by hawkerm** [comment]
Still using wyam, but did try moving the folder outside the `input` directory. This worked pretty well, though changes to those files don't get picked up by the default watch now, so just a thing to note with that solution.
