### ISSUE TITLE
Shorcodes 

### ISSUE THREAD

**Issue by nobels** [statiqdev/Statiq#924]
Hello, 

I did test with YouTube shortcodes
and i used your example → <?# YouTube u5ayTqlLWQQ /?>

But when i add these shortcodes i notice that the size of the movie is not equal in dimensions.
<?# YouTube ONFmxemS-Qo /?>
<?# YouTube 5g4HeYXfNwA /?>

Can i add 1200x900 as size  extra property ? just some idea :-)
<?# YouTube 5g4HeYXfNwA  1200x900 /?>

**Comment by daveaglick** [comment]
The YouTube shortcode uses YouTube's [oEmbed](https://oembed.com/) endpoint to get the embed code. While some oEmbed implementations support passing extra parameters to customize the return embedded code, YouTube does not as far as I know. If there are additional parameters we can pass to the YouTube oEmbed endpoint, let me know and those can be added! Otherwise there isn't much we can do with this particular shortcode unless it gets totally rewritten to use something other than oEmbed.
