### ISSUE TITLE
Add flag to cache config assembly

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#97]
In console app, write generated config assembly to disk (by default?). Store hash of config file and regen if different. Need to figure out how or if this should be supported in embedded scenario.

**Comment by Silvenga** [comment]
@daveaglick On my blog, config generation is taking around 4 seconds to run - would love to optimize that. I can write a pull for this - it looks straightforward:

- Mirror the implementation of `ConfigOptions.OutputScript`.
- When requested (or when not opted out), write the emitted config code to a dll, and store hash of config file.
- When requested and hashes match, use the compiled dll rather than compiling a new.

Hardest part is where to store the dll and hash (preferably in a self-cleaning way) and if this should be opt-in or opt-out. What are your thoughts?

File storage:
* User temp folder.
  * Harder to keep clean.
  * Needs considerations to prevent messing with other unknown instances of Wyam.
  * Keeps the files out of sight of the user.
* Hidden folder within the source directory (Like VS2017). 
   * Very easy to keep clean.
   * User has to deal with it (which might be a good thing).
   * Scoped to a single project, won't mess with others.

Opt'ing:
* I would be propose an opt-out flag unless hashing isn't capable of detecting if a regen needs to occur.

What do you mean by "supported in embedded scenario"?

**Comment by daveaglick** [comment]
@Silvenga Your plan sounds perfect and would love a PR for this.

> where to store the dll and hash (preferably in a self-cleaning way)

I would prefer them to be somewhere in the source directory. Perhaps right alongside the config file. I.e., if the config file is `config.wyam` then generated assembly would be `config.wyam.dll` and hash could be `config.wyam.hash`. That way it's obvious which generated artifacts go with which config file in case there are more than one (which there might be in complex sites). Also allows moving them all as a unit to another source folder if you want to, since there's a 1-to-1 between config file and generated assembly that should be totally valid.

> if this should be opt-in or opt-out

I'm fine with it being opt-out. There's little chance of this causing problems since we're just writing the same thing we would be generating in memory anyway (as long as the hashing works), and it's a performance boost. Can't imagine there are enough downsides that anyone would choose not to cache the assembly except for niche scenarios.

We'll need to make a note somewhere about not checking the `.dll` and `.hash` (or whatever/wherever the files are) into source control. There's already another artifact that shouldn't be checked in (the `packages.xml` file) so it's probably time I make a special page in the docs about what to add to your `.gitignore`.

> What do you mean by "supported in embedded scenario"?

There are several users (myself included) who bypass the Wyam CLI and config script altogether and instantiate the engine in code (this works really well in LINQPad BTW). In these cases there is no config file and `Wyam.Configuration` isn't even used. In other embedded scenarios the config script might not be coming from a file but from a string and the user is calling stuff in `Wyam.Configuration` directly. Basically there just needs to be a check that if the config came from a script file on disk we're good to cache, otherwise skip the caching.

**Comment by daveaglick** [comment]
Resolved with #557.
