### ISSUE TITLE
Deploy pipeline failure results in exit code 0

### ISSUE THREAD

**Issue by SteveDesmond-ca** [statiqdev/Statiq#972]
Steps to reproduce:
- create a Statiq site that deploys to GitHub Pages via GitHub Actions
- find a way to cause the site to build successfully but the deployment to fail
- run `dotnet run -- deploy` from the app root dir

(I'll try to find a more minimal repro, but for now [here](https://github.com/ecoAPM/ecoAPM.com/runs/4251794018?check_suite_focus=true)'s the most recent time I've hit this)

Expected result:
- process finishes with an error exit code to indicate failure

Observed result:
- process finishes with exit code 0, so CI shows success even though deployment failed

Notes:
- I found [tests](https://github.com/statiqdev/Statiq.Framework/blob/main/tests/core/Statiq.App.Tests/Bootstrapper/BootstrapperFixture.cs#L72-L92) that indicate that this should be working as expected, so maybe there's something funky specifically with the deploy?

**Comment by SteveDesmond-ca** [comment]
Minimal repro is just about as minimal as it can get!

`Program.cs`:
```cs
using Statiq.App;
using Statiq.Web;

await Bootstrapper.Factory
    .CreateDefaultWithout(args, DefaultFeatures.Pipelines)
    .AddWeb()
    .DeployToGitHubPages("test", "test", "test")
    .RunAsync();
```

Deployment fails but exit code of `dotnet run -- deploy` is 0

**Comment by daveaglick** [comment]
Interesting. I think there are two things going on (both are bad!):
- I can see the deployment actually did fail with the message `[ERRO] Deployment/Output » ExecuteIf » ExecuteIf » DeployGitHubPages » Server Error`. That's not very descriptive 😕. In general I've found GitHub Pages deployments to be wonky. Usually when they fail for me it's because I trigger API limits and get flagged as abuse. That happens more for big sites, and I've added some things like throttling to try and improve it, but still can't quite seem to entirely eliminate the possibility. But this doesn't look like that given the more vague error message. First thing I'll do here is add some better logging - look for a new release shortly with that.
- Second problem is that the build should have failed when the deployment did. It looks like Statiq is eating the failure and still returning a 0 result code. That's absolutely a bug. I'll look to see if it's impacting just the GitHub deployment module (I.e. is the module eating it) or all deployment modules (I.e. is the deployment pipeline eating it).

Stay tuned - I'll drop a note here when a new release is out (hopefully shortly). Hopefully with some better logging we can figure out _why_ the deployment is failing in addition to knowing _that_ it's failing.

**Comment by SteveDesmond-ca** [comment]
I found it -- the `async`/`await`s inside of `github.ThrottleAsync()` in `DeployGitHubPages.ExecuteConfigAsync()` ([link](https://github.com/statiqdev/Statiq.Web/blob/3ef69f0c2b1b09cb89badc756aca1649edbe09fa/src/Statiq.Web.GitHub/DeployGitHubPages.cs#L112-L126)) are swallowing the exception. Removing them (like is done at the bottom of the file) fixes this issue.

PR incoming later this afternoon for review.

**Comment by daveaglick** [comment]
Interesting! Now I've got to wrap my head around why that would be the case. The `ThrottleAsync()` method takes a `Task`-returning function, so when we omit the `async`/`await` it's passing in the actual `Task` from the called method, which then gets awaited inside the `ThrottleAsync()` method. However, when we pass in an async lambda like in the problematic code, we await the lambda itself within the `ThrottleAsync()` method, which then awaits the called method. My intuition is that shouldn't impact exception catching other than adding the extra lambda to the call stack.

I'm clearly missing something! Now I've been successfully nerd snipped and can't rest until I fully understand what's going on here.

**Comment by daveaglick** [comment]
Hmm...they both seem to throw correctly as I'd expect:

![image](https://user-images.githubusercontent.com/1020407/142480909-45d06b3c-644d-4bbe-b7c6-93f480262420.png)

![image](https://user-images.githubusercontent.com/1020407/142481007-81ac0c08-62bb-4147-98c4-31a3c6a17525.png)

**Comment by SteveDesmond-ca** [comment]
lol it's like we're pairing and finding the same issues simultaneously...indeed, I think the problem may be in my code

**Comment by SteveDesmond-ca** [comment]
Yep, there's even a corresponding problem in my "minimal" repro -- it's a little too minimal:

`Program.cs`:
```cs
using Statiq.App;
using Statiq.Web;

await Bootstrapper.Factory
    .CreateDefaultWithout(args, DefaultFeatures.Pipelines)
    .AddWeb()
    .DeployToGitHubPages("test", "test", "test")
    .RunAsync();
```
`Process finished with exit code 0.`

vs

`Program.cs`:
```cs
using Statiq.App;
using Statiq.Web;

return await Bootstrapper.Factory
    .CreateDefaultWithout(args, DefaultFeatures.Pipelines)
    .AddWeb()
    .DeployToGitHubPages("test", "test", "test")
    .RunAsync();
```
`Process finished with exit code 1.`

Apologies for the rabbit hole!

**Comment by daveaglick** [comment]
> I think the problem may be in my code

I'm not really seeing anything in the project that jumps out as suspect (unless this only started with some uncommitted code or code in a branch?). It all looks pretty straightforward, I.e. nothing exotic with changing inbox pipelines or anything.

**Comment by daveaglick** [comment]
Oh my gosh! Haha - so it just wasn't returning the exit code. It's always the blindingly obvious things :)

**Comment by daveaglick** [comment]
> Apologies for the rabbit hole!

No worries at all - async/await is tough enough to get right that validating assumptions and experimenting with it is an absolutely good exercise every so often.

**Comment by SteveDesmond-ca** [comment]
Plus if nothing else more supporting evidence for why I'm against top-level statements :grimacing:
