### ISSUE TITLE
Trouble with compilation of IDocument extension method

### ISSUE THREAD

**Issue by yetanotherchris** [statiqdev/Statiq#99]
I'm trying to write an extension method for IDocument, that will return an SEO friendly filename given a metadata key ("Title"), but having some problems with it not compiling. The extension method is (ignore the 2 in the method name for now, it's a work around):

```
public static class DocumentExtensions
{
    public static readonly string[] RESERVED_CHARS = new string[]
    {
                "-", ".", "_", "~", ":", "/", "?", "#", "[", "]",
                "@", "!", "$", "&", "'", "(", ")", "*", "+", ",",
                ";", "=", "}", ";"
    };

    private static readonly Regex _seoFilenameRegex = new Regex("^([a-zA-Z0-9])+$");

    public static string SeoFriendlyFilename2(IDocument document, string key = "Title")
    {
        if (string.IsNullOrEmpty(key))
            throw new ArgumentNullException(key);

        if (document[key] == null)
            throw new ArgumentException("The key " + key + " could not be found/is empty.");

        string fileName = document[key].ToString();

        if (string.IsNullOrEmpty(fileName))
            return "";

        string path = fileName;

        // Remove multiple dashes
        path = Regex.Replace(path, @"\-{2,}", "");

        // Remove reserved chars - doing this as an array reads a lot better than a regex
        foreach (string token in RESERVED_CHARS)
        {
            path = path.Replace(token, "");
        }

        // Remove multiple spaces
        path = Regex.Replace(path, @"\s+", " ");

        // Turn spaces into dashes
        path = path.Replace(" ", "-");

        // Grab letters and numbers only, use a regex to be unicode-friendly
        if (_seoFilenameRegex.IsMatch(path))
        {
            path = _seoFilenameRegex.Matches(path)[0].Value;
        }

        return path;
    }

    public static string SeoFriendlyFilename(this IDocument document, string key = "Title")
    {
        return SeoFriendlyFilename2(document, key);
    }
}
```

I'm happy to contribute this as a pull request and have about 10 tests behind it, but can't find the right place to put the method.

I'm using it like this:

```
Pipelines.Add("Posts",
    ReadFiles(@"posts\*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Excerpt(),
    Meta("Post", @doc.Content),
    ReadFiles("Post.cshtml"),
    Razor(),
    Meta("PostFile", @doc.SeoFriendlyFilename()),
    WriteFiles(string.Format(@"posts\{0}.html", @doc["PostFile"]))
);
```

**Comment by yetanotherchris** [comment]
One other thing, it'd be nice if the command line could output the code it's compiling to a text file as an extra option. I hacked it into `CompileScript()` using `File.WriteAllText(@"output.txt", code);` for now, but this is the biggest problems I've had with Wyam so far - trying to figure out what is being compiled by Roslyn.

**Comment by dodyg** [comment]
Oh this is awesome.

I think it will be better if you implement this functionality as a module that add a metadata to the each document e.g. "SeoFriendlyFieldName". It really hard to discover extension methods. 

```
Pipelines.Add("Posts",
    ReadFiles(@"posts\*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Excerpt(),
    Meta("Post", @doc.Content),
    ReadFiles("Post.cshtml"),
    Razor(),
    SeoFriendlyFilename(),
    WriteFiles(string.Format(@"posts\{0}.html", @doc["PostFile"]))
);
```

**Comment by daveaglick** [comment]
I agree with @dodyg, this would make a good module.

But let's back up a minute and address your original concerns first:
- What's the compilation error you get? Just reading through the code here, it looks like it should be okay. Maybe there's an issue with the automatic lambda expansion though - what happens if you replace `@doc.SeoFriendlyFilename()` with `(x, y) => x.SeoFriendlyFilename()`.
- I like your idea of outputting the generated config file - it should be easy, so I'll try to get it in today. I've tried to make the error messages be helpful (I.e., the line numbers always match up - which wasn't easy to do), but there may be times when it would be helpful to see exactly what Roslyn is getting. This would purely be for debugging though (#97 actually addresses caching the config for better startup performance).

Now let's take a look at making this a general-purpose module. I guess the idea here is that you may want to name the files something simple on disk, but output more complex SEO-friendly file names based on some other metadata (like "Title" taken from front matter)? I could also see using this module if your original file names aren't SEO-friendly (I.e., multiple dashes, etc.).

Here are some suggestions:
- If no other key is specified in the constructor, make the module use the RelativeFilePath key and preserve the path information while changing the existing filename.
- Provide a constructor override or fluent method to preserve the path information in RelativeFilePath (if it exists), even if an alternate key is specified, by writing the result to WritePath.
- Write the result to the metadata key WriteFileName by default so that you don't need to specify the output key in your WriteFiles call.
- Allow specifying an alternate metadata key for the result.

With that in mind, I suspect the module's public API would look something like:

``` C#
public class SeoFileName : IModule
{
    public SeoFileName()
    {
        // Sets metadata key WriteFile to optimized version of SourceFileName
    }

    public SeoFileName(string inputKey)
    {
        // Sets metadata key WriteFile to optimized version of the metadata
        // value of the specified inputKey
    }

    public SeoFileName(string inputKey, outputKey)
    {
        // Sets metadata for the specified outputKey to optimized version of
        // the metadata value of the specified inputKey
    }

    public SeoFileName PreservePath(bool preservePath)
    {
        // In addition to normal behavior, if preservePath == true, sets metadata
        // key WritePath to Path.Combine(RelativeFileDir, result)
        // Note: This should probably be the default behavior (I.e., call this
        // fluent method to turn it off, not turn it on)
        return this;
    }

    public SeoFileName PreservePath(string outputKey)
    {
        // Same as the other PreservePath call, but this specifies the
        // output key to use - no bool needed since it's assumed setting
        // this turns it on
        return this;
    }
}
```

The module should probably go in the core library since it doesn't have any external dependencies. If you've got any feedback or comments on the suggested design, just let me know - I'm not locked-in to it by any means.

**Comment by yetanotherchris** [comment]
My code is a bit less thought out (in Wyam terms, as I don't know the innards that well), it involves removing every URL reserved character, multiple dashes, and turning spaces into dashes while removing multiple dashes.

The specific problem I was having was commas and brackets, and multiple spaces. SeoFriendly is a bit of a misnomer as I think Google strip out punctuation anyway, but it could easily be put into Wyam.Core. It's really just the method above and these tests, with my eye on integrating it into Roadkill too as some point (and stealing your improvements :grin:):

https://raw.githubusercontent.com/yetanotherchris/SeoUrlSausage/master/src/SeoUrlSausage.Tests/PathSqueezerTests.cs

**Comment by daveaglick** [comment]
Okay, cool. I don't mind porting what you've got above along with the tests into Core - it shouldn't take more than a few minutes.

Did you get the compilation problems worked out, or are you still having trouble with that?

**Comment by daveaglick** [comment]
The first part of this is done. If you specify `--output-scripts` on the command line it will now output two files, one for the configuration and one for the setup (which gets run first). For example, if your config file is named `config.wyam` then specifying the switch will output `config.wyam.WyamConfig.cs` and `config.wyam.WyamSetup.cs` (`WyamConfig` and `WyamSetup` match the in-process assembly name). Note that these output files are exactly what Roslyn sees during the configuration process, but that they should be used for debugging only. They may not make sense and will almost certainly be poorly formatted.

**Comment by yetanotherchris** [comment]
`Meta("PostFile", string.Format(@"posts\{0}.html", @doc.SeoFriendlyFilename()))` now works fine, so I'm not sure what went wrong originally.

**Comment by daveaglick** [comment]
The module is now in the develop branch. I decided to call it FileName since, as you mentioned, it's good as a general-purpose module for getting good file names. I did have trouble with the one test that uses extended characters - I suspect something went wrong during copying and pasting the values. If you get a chance to look at it, go ahead and send a PR. Otherwise, it's good to go so I'm going to close out this ticket. Just let me know if you need any help figuring out how to use the new module for your scenario. Thanks for the idea and code!
